### ISSUE TITLE
Cannot update Python path

### ISSUE THREAD

**Issue by GBR-613** [pyscripter/pyscripter#1002]
I need to set specific Pathon path for some specific script.  
I change the necessary value in a dialog box from Tools menu, close the dialog, reopen it - the correct values still appear.
I then run the script - it fails like the it would be if the path was not updated.
I reopen the dialog box: really, the old values appear again.

As workaround, I would like to manually change these values out of the application.  I expected to find them either in regedit or in some ini file.  I did not find them anywhere.  A hint where the path value is stored would be highly appreciated.

**Comment by pyscripter** [comment]
From the help topic on Python Path:

> Note that the changes to the Python path apply only to the current session.  To permanently change the Python path you can either modify the PYTHONPATH environment variable or modify the HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\x.y\PythonPath registry setting.  You can also use the PyScripter startup script python_init.py to modify the path.

So every time the interpreter reinitializes the changes to the path are lost.

Another way to add paths to Python path when running scripts is to use the Project Manager.  If you right-click on the project name (top node) there is an option "Extra Python path".  The paths you have there are added at the top of the python path list, every time a script runs.
