### ISSUE TITLE
Batch file starter for Pyscripter fails with arguments

### ISSUE THREAD

**Issue by amr66** [pyscripter/pyscripter#1003]
I use a non regisitered, portable python installation along with PyScripter. Lately I discovered that starting PyScripter by running a batch file always opens a error dialog, saying "Pyscripter could not load a python engine (...)". I found out that if I use the start comand with a trailing %* for possible arguments, the error arise. Omitting that token, PyScripter starts with the correct python version.

This is the faulty one:
````
start "PyScripter" %~pd0\pyscripter\PyScripter.exe --PYTHON37 --pythondllpath=%OSGEO4W_ROOT%\apps\python37 %*
````

Am I doing the start command wrong?

**Comment by pyscripter** [comment]
There was a minor bug in the parsing the parameters which is now fixed.  

As a workaround use quotes in pythondllpath e.g.
```
start "PyScripter" %~pd0\pyscripter\PyScripter.exe --PYTHON37 --pythondllpath="%OSGEO4W_ROOT%\apps\python37" %*
```

**Comment by amr66** [comment]
Ah, that does the trick! Thanks you!
