### ISSUE TITLE
Pyscripter could not find a usable installation at the specified path

### ISSUE THREAD

**Issue by martinchez** [pyscripter/pyscripter#1005]
Pyscripter could not find a usable installation at the specified path
![Screenshot (299)](https://user-images.githubusercontent.com/31928456/84777421-3d11b480-afea-11ea-9b6e-338f377143d6.png)

**Comment by martinchez** [comment]
i have been trying by all means but it cant work anyone with how to solve it

**Comment by pyscripter** [comment]
**Before** using PyScripter, you must ensure that there is a version of Python 
greater or equal to 2.7 installed on your machine. Windows.  If you do not have one 
installed, you can download one from http://www.python.org/.

The 64-bit version of PyScripter (x64) works only on 64-bit Windows **and**
with 64-bit versions of Python.  The 32-bit version (x86) of PyScripter works on both
32-bit and 64-bit Windows with 32-bit versions of Python.

- Have you installed Python?  
- 32 bits or 64 bits?  
- Is PyScripter 64 btis?

**Comment by pyscripter** [comment]
Closed since there was no feedback for over three months.
