### ISSUE TITLE
Editor text appears wrong with some monospaced fonts 

### ISSUE THREAD

**Issue by GBR-613** [pyscripter/pyscripter#1009]
Editor text appears wrong with some monospaced fonts.

Attached are screenshots for Consolas (which is fine), the same editor with Courier (which is wrong) and with Terminus (which is wrong too).

This is Windows 10, Country or region is set to "Israel" but Regional format is English (US), and chcp command returns 65001.  
Probably that matters.  

![PS_bug20](https://user-images.githubusercontent.com/17687869/85680095-a8d2dc00-b6d2-11ea-97b2-c7abfa46fcfa.png)
![PS_bug21](https://user-images.githubusercontent.com/17687869/85680104-aa040900-b6d2-11ea-9952-a49f403e17c4.png)
![PS_bug22](https://user-images.githubusercontent.com/17687869/85680110-ab353600-b6d2-11ea-9730-b73f25717182.png)

**Comment by pyscripter** [comment]
Both Courier and Terminus are raster (bitmap) fonts, which is a rarity these days.  Raster fonts (https://docs.microsoft.com/en-us/windows/win32/gdi/raster--vector--truetype--and-opentype-fonts).  Raster fonts don't scale well and they don't look good in high-dpi monitors. 

Use instead open type or true type fonts such as Consolas, Courier New and many many others. (https://www.elegantthemes.com/blog/wordpress/best-programming-fonts)

**Comment by pyscripter** [comment]
I have committed a change that hides raster fonts from the list of available fonts.
