### ISSUE TITLE
The 'rpyc' package is not availble

### ISSUE THREAD

**Issue by slk1804** [pyscripter/pyscripter#1010]
After installing Pyscripter version 3.6.3 I get the message, that the package "rpyc" is not available. Please restart Pyscripter and try again. If the error persists reinstall Pyscripter.

The python version on the client is 2.7. Are the python and PyScripter versions not compatible? In the installation directory, there is a rpyz.zip file under C:\Program Files\PyScripter\Lib

Thanks a lot in advance.

**Comment by pyscripter** [comment]
The 64-bit version of PyScripter (x64) works only on 64-bit Windows **and** with 64-bit versions of Python.  
The 32-bit version (x86) of PyScripter works on both 32-bit and 64-bit Windows with 32-bit versions of Python.

-  [Is your Windows 64 bits](https://helpx.adobe.com/x-productkb/global/determine-whether-computer-running-32.html) (most likely these days).
-  If yes then from the location "C:\Program Files\PyScripter\" Pyscripter is also 64bits.
- Is your python 64-bits?

```
C:\Python\Python27>python
Python 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by pyscripter** [comment]
Closing, since there is no feedback.
