### ISSUE TITLE
Problem saving Layout

### ISSUE THREAD

**Issue by ocarillo** [pyscripter/pyscripter#1014]
Hi,

There are several bugs regarding to save layout in pyscripter 3.6.3 (I am using portable edition).

First, I like to have the "python Interpreter" window in right vertical panel. When I open the pyscripter for the first time, It is not possible to put it in this way directly. I have to put  it in left vertical side first over the file explorer. Then I can move it to the right side.

Second, when I save a layout in View - Layouts - Save layout, It does right. But, if I close pyscripter and open it several days after (It doesn't happen if I do in the same day), then the layout backs to the factory. I tried to save files pyscripter.ini and pyscripter.local.ini and restore them when I have this issue, but It doesn't work. It also disappear the Layout previously saved.

Thank you for this app, for me it is the best python editor. Please, keep improving.

**Comment by pyscripter** [comment]
> if I close pyscripter and open it several days after (It doesn't happen if I do in the same day), then the layout backs to the factory.

The time elapsed has not impact.  How could it?

What matters is the monitor resolution and configuration.   If you add/remove monitors and/or change the resolution of the monitors then the saved layout is not used.

**Comment by ocarillo** [comment]
So, in remote desktop can I have this issue too? It is true that I access from several computers to the one where pyscripter is installed, and the configuration of remote desktop can be different, so I supposed the resolution can be different. Thank you.

Any suggestion about the first problem whit the "python interpreter"?

Thank you very much.

**Comment by pyscripter** [comment]
With remote desktop what matters is the monitor configuration where PyScripter is running.

I cannot reproduce the first issue.  When I open PyScripter with the default configuration, I can drag the interpreter window and dock it to the right side.

**Comment by ocarillo** [comment]
Ok,

Thank you.
