### ISSUE TITLE
Looking for help opening Remote file

### ISSUE THREAD

**Issue by FlexMcMurphy** [pyscripter/pyscripter#1016]
Hello,

Pyscripter Version 3.6.3.0 x86 (32 bit)

I am running Pyscripter on Windows 7. I have python scripts on a linux OS.
I want to edit the Python scripts on the Linux OS from Pyscripter running on the Win 7 machine.
The linux OS has an SSHD server.
I  installed OpenSSH on to Win 7.
I demonstrated an ssh connection using public/private key from Win 7 command line to the Linux OS.

I don't know how to set these connection details in Pyscripter. Can someone advise me please?
I go in to File > Open Remote File > Edit SSH Server and have tried lots of variations in that form but nothing is working.
Here is what I currently have...
![image](https://user-images.githubusercontent.com/32464325/92331149-629fde80-f06c-11ea-95f7-90a777f2467e.png)

For example, a script I want to open is on the linux OS at /home/osmc/python/script.py
In Pyscripter, what do I enter for "File path"? Is it: /home/osmc/python/script.py ??
But I get a pop up with...

"Error in opening file /home/osmc/python/script.py".
Error: SCP Error:
Output: +
Error Output: +

Maybe it's better to try with Putty? Any help much appreciated.

Cheers,

Flex

**Comment by FlexMcMurphy** [comment]
I managed to get Pyscripter to make a remote connection by using Putty. I'm still curious what I was doing wrong above though?

Cheers,

Flex

**Comment by pyscripter** [comment]
Good to hear it worked with putty.
Were scp and ssh on the path?
Use the ssh agent for passing the keys to the server and do not add them in the options.

Make sure that from a command prompt:
>ssh root@192.168.1.3
works without a password.

**Comment by FlexMcMurphy** [comment]
Yes scp and ssh were added to my Windows PATH variable and OpenSSH installed correctly as evidenced by the ssh connection I can make from the local Windows machine to remote Linux machine from the Windows command line.

I have turned off password authentication in the sshd server on the remote machine so I have no choice but to use the public/private key exchange and that does work when I test from the Windows command line like this...

`C:\Windows\system32>ssh -i "C:\Users\Me\.ssh\PrivateKey-OSMC-18-Mar-20-OpenSSH.ppk" root@osmc`

I don't know what you mean by: 
_Use the ssh agent for passing the keys to the server and do not add them in the options._ ??

What settings do I need to put in the "Edit SSH Server" dialog box to make the connection using OpenSSH instead of Putty?

Cheers,

Flex

**Comment by pyscripter** [comment]
https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement
Look at the and
Also 
https://www.tecmint.com/ssh-passwordless-login-using-ssh-keygen-in-5-easy-steps/
and 
https://blog.rac.me.uk/2019/08/24/windows-10-openssh-storing-keys-using-the-ssh-agent/

**Comment by FlexMcMurphy** [comment]
Thanks for this, I had never heard about ssh-agent (ssh-add.exe) to store private keys.
Flex
