### ISSUE TITLE
Does Pyscripter support Python 2.7 still?

### ISSUE THREAD

**Issue by FlexMcMurphy** [pyscripter/pyscripter#1017]
I am trying to setup [python 2.7.13](https://www.python.org/downloads/release/python-2713/) with Pyscripter 3.6.3.0 32-bit.

I am downloading from the official sources... I go to.. Run > Python Versions > Setup Python versions.. In here I have tried the 32 bit and 64 bit versions. But in both cases when I try to add them in Pyscripter I get...
![image](https://user-images.githubusercontent.com/32464325/92332395-c4187b00-f075-11ea-89d7-e5bfe10f316f.png)

Am I doing something wrong?

Also.. a basic question.. when Pyscripter is set to run python scripts on a remote machine does it use the interpreter on the local machine or the remote machine? I want Pyscripter to run scripts that are on a remote machine that were written according to Python 2.7 so do I still need to set the Python 2.7 version in Pyscripter? I don't think you can point it to a Python installation on a remote machine??

Cheers,

Flex

**Comment by pyscripter** [comment]
Pyscripter is able to work with python 2.7.  Have you installed Python 2.7-32 bits?   The picture shows that PyScripter only finds Python 3.8-32 bits.

Can you use python 3.8-32bits?  If not what happens when you select that version and press the test button?  Enter the python shell and have a look at the top line.

Also check the registry. Which versions are available under the keys Computer\HKEY_CURRENT_USER\Software\Python\PythonCore 
Computer\HKEY_LOCAL_MACHINE\Software\Python\PythonCore?

**Comment by FlexMcMurphy** [comment]
Hello!

Yes I downloaded and installed the 32-bit and 64-bit versions of Python 2.7.13 [from here](https://www.python.org/downloads/release/python-2713/). 

I also installed Python 3.8.5 32-bit [from here](https://www.python.org/downloads/windows/).

python-2.7.13.msi
python-2.7.13.amd64.msi
python-3.8.5.exe

In this screenshot you can see the Python installation folders in:
c:\Python27
c:\Python27-64
c:\Python38-32

![image](https://user-images.githubusercontent.com/32464325/92334552-0ac2a100-f087-11ea-9b86-2855ced5c3b7.png)

Yes I was able to use... Run > Python Versions > Setup Python versions... to add Python 3.8.5 but when I try the same thing with Python 2.7 32 or 64 bit I just get that error message.

The screenshot also shows that the selected Python Interpreter is 3.8.5. I would like to be able to select 2.7.13 as well.

In my registry I have the versions...
Computer\HKEY_CURRENT_USER\Software\Python\PythonCore
Version 2.7 and the "Python Path" is C:\Python27\Lib;C:\Python27\DLLs;C:\Python27\Lib\lib-tk

Computer\HKEY_LOCAL_MACHINE\Software\Python\PythonCore
Version 2.7 and the "Python Path" is C:\Python27-64\Lib;C:\Python27-64\DLLs;C:\Python27-64\Lib\lib-tk

When I go to the command line and run the command `python --version` I also get Python 2.7.13

So my question is... how do I add 2.7.13 to PyScripter? I want to use that version with the scripts I have on the remote machine.

Cheers,

Flex

**Comment by FlexMcMurphy** [comment]
I am testing some more..

I switched to PyScripter 3.6.3.0 x64 on my Win 7 64-bit system. I also installed Python 2.7.13 64-bit and 3.8.5 64-bit.
As you can see from this sceenshot, PyScripter sees each 64-bit Python installation..

I can activate Python 3.8.5...
![image](https://user-images.githubusercontent.com/32464325/92336399-05218700-f098-11ea-9945-ff32fb7ca9db.png)

But when I try to activate Python 2.7.13 I get that error.
![image](https://user-images.githubusercontent.com/32464325/92336354-a3f9b380-f097-11ea-9589-441a821f920a.png)

Is this a bug? Can you add and activate Python 2.7.13? It doesn't work for me in 32-bit or 64-bit versions.

Cheers,

Flex

**Comment by pyscripter** [comment]
Does starting pyscripter with
pyscripter --PYTHON27 --PYTHONDLLPATH=C:\python27"
from the command line work?

If not does uninstalling the 64-bit version help?

**Comment by FlexMcMurphy** [comment]
_I would just unistall all 32 bit apps (python and pyscripter) and just use the 64 bit versions._

Yes that's what I did as mentioned in my last comment. But still PyScripter won't recognise Python 2.7.13 64-bit.

When  I run `pyscripter --PYTHON27 --PYTHONDLLPATH=C:\python27"` I get the error:
`"'pyscripter' is not recognized as an internal or external command, operable program or batch file."`

Are my registry settings correct?
This is the InstallPath for Python 2.7
![image](https://user-images.githubusercontent.com/32464325/92337356-dcea5600-f0a0-11ea-9f23-3daaba39f18a.png)

Is it missing ExecutablePath and WindowedExecutablePath ??

This is the InstallPath for Python 3.8
![image](https://user-images.githubusercontent.com/32464325/92337364-f390ad00-f0a0-11ea-9dc0-3b9c0efc68ae.png)

Also, do you think I am missing .dlls in my Python 2.7 installation directory compared with the 3.8 installation?
![image](https://user-images.githubusercontent.com/32464325/92337404-5f731580-f0a1-11ea-97db-fcec257d9fae.png)

So I am now completely using 64-bit only... I also tried Python 2.7.18 64-bit and PyScripter also won't recognise it.
![image](https://user-images.githubusercontent.com/32464325/92337534-4f0f6a80-f0a2-11ea-86a3-f0631b04baa4.png)

![image](https://user-images.githubusercontent.com/32464325/92337543-5c2c5980-f0a2-11ea-800a-d0aefff6fc55.png)


This is very frustrating. I have seen other people [with a similar problem](https://github.com/pyscripter/pyscripter/issues/881) that didn't get resolved.

Cheers,

Flex

**Comment by FlexMcMurphy** [comment]
OK I tried that command, PyScripter started up but gave the same error message:
![image](https://user-images.githubusercontent.com/32464325/92338686-e5935a00-f0a9-11ea-824f-2334d46dd6b7.png)
It's not able to see the Python 2.7 installation at all.

You took out a lot of useful information from my last post I was hoping it would help you to debug my problem, and maybe others who comes here with the same problem, I see I'm not the only one who has had this problem with PyScripter.

For instance, my C:\python27-64 directory doesn't have any .dlls. Should it? Am I missing registry settings for Python 2.7? Compared with 3.5 there is no mention of an ExecutablePath or a WindowedExecutablePath variable in "InstallPath". Should there be?

Maybe Python 2.7 just is not installing cleanly for me? Any idea how to make a totally clean install? Apart from re-installing Windows. I do add/remove programs each time to uninstall Python and PyScripter but maybe the registry isn't getting cleared?
Cheers, Flex

**Comment by pyscripter** [comment]
> For instance, my C:\python27-64 directory doesn't have any .dlls. Should it? Am I missing registry settings for Python 2.7? Compared with 3.5 there is no mention of an ExecutablePath or a WindowedExecutablePath variable in "InstallPath". Should there be?

You probably installed for all users.  In that case and only for python2.x the python27.dll is placed in C:\Windows\system32 (I think, do check).  And this explains why
"c:\Program Files\pyscripter.exe" --PYTHON27 --PYTHONDLLPATH=C:\python27-64
does not work.  PyScripter fails to find the python27.dll in that directory.
Can you use python2.7 64-bits from the command prompt?
Does 
"c:\Program Files\pyscripter.exe" --PYTHON27
work?
The rest do not matter.  They were added in recent versions of Python 3,x.

One more thing you can try is uninstall python 2.7-64 and install it again for the current user.  You should then be able to see pyhton27.dll in the installation directory. Then try again:
"c:\Program Files\pyscripter.exe" --PYTHON27 --PYTHONDLLPATH=C:\python27-64

**Comment by FlexMcMurphy** [comment]
Yes you are right!

I was googling about those .dlls and found [this thread on stackoverflow](https://stackoverflow.com/questions/24517754/python-official-installer-missing-python27-dll) which led me to copy C:\Windows\System32\python27.dll into C:\Python27-64. Now PyScripter finally recognises Python 2.7!

![image](https://user-images.githubusercontent.com/32464325/92341054-74a56f80-f0b4-11ea-88be-fe36e25aaf94.png)

Your explanation is better. So I understand about Current User vs All Users.

I guess Pyscripter needs that .dll. Maybe it should look for it in C:\Windows\System32 if it can't find it in the Python installation dir?

I was indeed installing Python each time for `All Users`. I figured that might be better practice although I am the only one using this laptop?!

I also checked and PYTHONHOME and PYTHONPATH are not set in my environment.

No, "c:\Program Files\pyscripter.exe" --PYTHON27 didn't work either.

Anyway thankfully I can go to sleep now and get back to debugging code tomorrow!

Flex

**Comment by pyscripter** [comment]
> I guess Pyscripter needs that .dll. Maybe it should look for it in C:\Windows\System32 if it can't find it in the Python installation dir?

It does!  I am not sure why it did not work in your case.

**Comment by FlexMcMurphy** [comment]
I checked and yes that directory is in my PATH... and ran the SET command and this is a section of the PATH...
`;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;`

I wonder is it case sensitive?... there is a lowercase "s" in the PATH but the folder starts with Uppercase "S".
`;C:\Windows\system32;`

When I view the PATH variable from Windows System Properties > Environment Variables, this is a portion of the string...
`;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;`

Flex

**Comment by pyscripter** [comment]
Thanks that looks OK.  In Windows the path is not case sensitive.

**Comment by ManPython** [comment]
https://github.com/pyscripter/pyscripter/issues/860
I have this same problem with Python38 and Python38-venv as limit 
Notice that Python38 is often registered as Python38-39.

**Comment by pyscripter** [comment]
@ManPython 
> Notice that Python38 is often registered as Python38-39.
No way, Are you sure it is python 3.8?

Could you please open a separate issue regarding python 3.8 and provide all relevant info (python version and distribution, pyscripter version, whether you python version is registered for all users, for the current user or not registered, environment settings if any (PYTHONPATH, PYTHONHOME) etc.)
