### ISSUE TITLE
Working with remote files

### ISSUE THREAD

**Issue by FlexMcMurphy** [pyscripter/pyscripter#1018]
Following on [from issue #1016](https://github.com/pyscripter/pyscripter/issues/1016) I have PyScripter on a Win 7 machine and Python scripts on a remote Linux OS (Raspberry Pi).

I managed to get PyScripter to open remote Python scripts into the IDE. PyScripter seems to be able to discover errors in the remote script fine. However when I go to run the remote script from within PyScripter in Win 7 I think it seems to believe the script is located locally on the same machine running PyScripter... for instance I get command not found errors for "sudo" like..

`'sudo' is not recognized as an internal or external command, operable program or batch file.`
and the script is never able to see a file in the same directory as the script itself. However when I run the same script from the command line of the remote host the script does work just fine.

Maybe I am misunderstanding something about what you helped me with in issue #1016?? Is it possible for PyScripter to run a python script that is located on a remote machine? So that when it's running in PyScripter on the Win 7 machine it is actually running on the remote Linux OS machine? Maybe this is actually not possible?!

I already have a Samba share on my Windows machine to the Linux machine and from there I can just drag and drop files into the PyScripter IDE on the windows machine and edit them there. I don't think I needed to do any of those instructions in issue #1016 after all, at least so I can EDIT the scripts. But I also want to run them on the Linux OS FROM PyScripter on the Windows OS.

Cheers,

Flex

**Comment by pyscripter** [comment]
There is a difference between files you open through the Samba share (these would be seen as Windows files) and files you open using the File, Open Remote command.  The latter would be run using the remote server (i.e. inside your Linux machine).

**Comment by FlexMcMurphy** [comment]
I was using File > Open Remote File to open the python script but it still wasn't running it remotely.

My problem: I wasn't connecting to the remote machine...

`Run > Python Engine > SSH menu option`

I think the naming of the "Python engine types" is a bit confusing. To run a script that is located on a "remote host" you have to select the "SSH" Python engine.. not the "Remote" engine.

Working with remote files in PyScripter explained [here ](https://pyscripter.blogspot.com/2019/01/ssh-engines-using-putty.html)and [here](http://pyscripter.blogspot.com/2018/10/working-with-remote-files-preview-of.html).

Cheers.

**Comment by pyscripter** [comment]
May I close this one?

**Comment by FlexMcMurphy** [comment]
Yes please.

But for what it's worth I think the names you have for the different Python Engine types... newbies would find them misleading and confusing, and maybe not only newbies. The "Remote" Python engine is not an interpreter located on a "remote" machine but it's located on the same machine running PyScripter. Maybe the word "remote" makes sense in a programmatic context because the engine can run in a separate process to PyScripter but for practical purposes it makes more sense for people to think in terms of where the interpreter is based relative to the machine running PyScripter. I would called the ssh engine the remote engine and what you call the remote engine I would call the local engine or local (x) where x = some way to distinguish the type of engines that run on the local machine that PyScripter is installed on.

Cheers,

Flex

**Comment by pyscripter** [comment]
Fully agree, but the naming "Remote Engine" has been around long before ssh engines were implemented.  Renaming it now and calling ssh engines remote engines is also going to cause confusion to existing users.  Most users are not using or even aware of ssh engines.
