### ISSUE TITLE
scp error: protocol error: filename does not match request

### ISSUE THREAD

**Issue by FlexMcMurphy** [pyscripter/pyscripter#1019]
Hello,

PyScripter-3.6.3-x64-Setup.exe on Windows 7
OpenSSH-Win32.zip Version: v8.1.0.0p1-Beta installed on Win 7 and added to the PATH.
Trying to remote edit/debug script on OSMC running on a Raspberry Pi on the same LAN.

My keys are set up and I can connect to OSMC Pi from Windows 7 command line with: `ssh root@osmc`

However when I set up the SSH server details in PyScripter like this:
![image](https://user-images.githubusercontent.com/32464325/93078863-1fa0c500-f683-11ea-9e9e-f0a22e76ae31.png)

And try to open a file on the OSMC Pi filesystem like this:
![image](https://user-images.githubusercontent.com/32464325/93078965-4959ec00-f683-11ea-9752-70094e03865c.png)

Instead I get this error:
![image](https://user-images.githubusercontent.com/32464325/93079002-55de4480-f683-11ea-9c06-d445686cd607.png)

If I add the scp option -T into the ssh server settings like this:
![image](https://user-images.githubusercontent.com/32464325/93079101-7dcda800-f683-11ea-9048-3f1dee3b66c5.png)

Then it _does_ connect.

I can also simply drag and drop the file from a Windows Samba share into the PyScripter IDE and it opens it remotely without any error...
![image](https://user-images.githubusercontent.com/32464325/93080137-203a5b00-f685-11ea-9c42-f52ca4f467d2.png)

Why do I need to add the -T? According to the [scp man page](https://man7.org/linux/man-pages/man1/scp.1.html) this option disables strict filename checking when copying files from a remote host to a local directory. But why would scp think there has been any change to the remote and local filename in this case? All characters in the remote filename and path are ascii and there are no spaces.

Are there any other scp or ssh options that I should be adding into the PyScripter ssh server settings dialog?

Cheers,

Flex

**Comment by pyscripter** [comment]
I will check.

Please note that when you open a file from a Samba share it will load fine and if you change it it will also save fine.  However when you run such a script it will be run locally not remotely.

You would need to open the file through open remote file to run it remotely at the ssh server.

**Comment by FlexMcMurphy** [comment]
Thanks for explaining the difference between File > Open Remote File and dragging a file from Samba share in to the PyScripter IDE.

About the scp error. Yes I already read that link and understand that -T (or using sftp instead of scp) is a workaround.

But I'm curious why, in my case above, is PyScripter causing scp to give that error? There is nothing unusual about the remote filename:
`/home/osmc/python/h7spatterns`

Perhaps, [as with ansible mentioned here](https://github.com/ansible/ansible/issues/52640), when scp is used to fetch a file PyScripter will use single quotes around the path causing a validation failure? Is that so do you know?

Flex

**Comment by pyscripter** [comment]
> Perhaps, [as with ansible mentioned here](https://github.com/ansible/ansible/issues/52640), when scp is used to fetch a file PyScripter will use single quotes around the path causing a validation failure? Is that so do you know?

Yes this is the case.

**Comment by FlexMcMurphy** [comment]
Brilliant. Thank you.
