### ISSUE TITLE
TSynInfoLossEvent

### ISSUE THREAD

**Issue by limelect** [pyscripter/pyscripter#1021]
D10.2.3
Could not find TSynInfoLossEvent on synedit or else or google

**Comment by pyscripter** [comment]
I suppose you are trying to compile PyScripter.

You need the latest version of [Turbo Synedit](https://github.com/TurboPack/SynEdit).  The Multiinstaller undrer Components\ThirdParty  will help you install dependencies.

However you will need at least Delphi Rio (10.3) to compile the sources.  Use the Community edition.
