### ISSUE TITLE
why  High CPU consumption

### ISSUE THREAD

**Issue by liuzg2** [pyscripter/pyscripter#1022]
why  High CPU consumption  when open   pyscripter
![20201003100113](https://user-images.githubusercontent.com/48178108/94980849-0e4f2800-0560-11eb-8c25-1a21eb3902c0.jpg)

**Comment by pyscripter** [comment]
I don't see that here with 64 bits.  I will check with 32 bits.
![image](https://user-images.githubusercontent.com/1311616/94988311-eddd9880-0574-11eb-9daa-fbb9ed52fbb6.png)

Which version of Python are you using?

**Comment by liuzg2** [comment]
found why !
run  ---  python engine----remoter(tk)        High CPU consumption
run  ---  python engine----remoter             normal

**Comment by pyscripter** [comment]
Oh!  Please read.  https://github.com/pyscripter/pyscripter/wiki/RemoteEngines.

The remote python engine is recommended for most tasks including running GUI scripts.  You should only be using the Tk engine when you want to develop Tk Windows interactively.
