### ISSUE TITLE
Turn off Windows bell sound when I run a script

### ISSUE THREAD

**Issue by FlexMcMurphy** [pyscripter/pyscripter#1023]
PyScripter 3.6.3.0 64-bit
Python 2.7 64-bit
Windows 7

Sometimes when I run a python script in PyScripter I get the Windows bell sound... although not every time.... why do I get that sound sometimes and how do I turn it off?

Cheers,
Flex

**Comment by pyscripter** [comment]
It would help if you have a reproducible case.  I don't hear bell sounds here when I run/debug scripts.

**Comment by FlexMcMurphy** [comment]
Here is a test script:

```
#!/usr/bin/python

# importing modules
import os
import time
import datetime
from datetime import datetime

def f_log(strtext):
# In this method try and write to the log file
	logFilePath = '/home/osmc/python/pyscripter_file.txt'
	ts_local = datetime.now()
	ts = ts_local.strftime("%d/%b/%Y %H:%M:%S")

	try:
		# Check if the logfile exists
		if(os.path.isfile(logFilePath)):
			# Append the error message to the log file. 'a+' creates the file if it does not exist.
			with open(logFilePath, 'a+') as f:
				f.write(ts + '\t' + strtext + '\n')
		else:
			print("Log File does not exist - Creating File now")
			with open(logFilePath, 'a+') as f:
				f.write(ts + '\t' + 'Log File does not exist - Creating File now' + '\n')
				f.write(ts + '\t' + strtext + '\n')
	except IOError as e:
		# Handle the exception
		print("Error Msg")

f_log("Test Script")
print("Hello World")
```
This script is in a directory on a Raspberry Pi running OSMC... in a folder called /home/osmc/python
I have opened it as a remote file in Pyscripter and can see ssh://osmc//home/osmc/python/test.py
When I run it from PyScripter on Windows I get a beep when it finishes executing.

If I create a crontab to run it in osmc...
```
PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/bin/python
#
53 22 * * * /usr/bin/python /home/osmc/python/test.py >> out.txt  2>&1 
```

This also gives a beep at the end.

If I run the script from a command line to osmc (from an ssh connection in Putty)
```
# cd /home/osmc/python
# python test.py
```
I DO NOT get a beep when it completes.

If I run this script in Pyscripter it does NOT make a beep
```
import sys
print('Python '+sys.version.replace('\n','')+' at '+sys.executable+' on '+sys.platform)
```
Why do I sometimes get the beep? Something in the Python code in the first script I guess?

Flex

**Comment by FlexMcMurphy** [comment]
I think I figured out what is causing the beep.

When I run the above script it writes to the log file: `/home/osmc/python/pyscripter_file.txt`.

I have that file open in PyScripter. When the script runs I just realize that PyScripter gives the message: "Changed files have been reloaded". So it must be PyScripter making the beep signalling that a file open in the IDE has been reloaded.. after the script writes to it.

Is it possible to stop PyScripter from beeping when a file open in the IDE has been changed by some external process?

Flex

**Comment by pyscripter** [comment]
> In IDE > "File Change Notification". What do these settings mean?
> fcnFull
> fcnNoMappedDrives
> fcnDisabled

Explained in the help file.  
a)  Receive FCN from all drives including Mapped drives  
b)  Receive FCN except from Mapped drives (slows down pyscripter)
c)  Do not receive FCN.

There is an option Auto reload changed files:
-  if true then changes files change automatically and there is message at the status bar and a beep (you were right about this.
- if false you are asked whether to load change files

There could be another option about the beep.

If you feel strongly about this please close this issue and open another one "Option to not beep with Auto Reload Files" or something.
