### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by luebbe** [pyscripter/pyscripter#1025]
Hi Kiriakos,

Following up on your request, I've seen that you already updated ggexclude.cfg. I added another property and will push this change.

Using ggexclude allows us to weed out ignore.po, which still contains a lot of stuff that is now obsolete, because it is caught by ggexclude.

I did this and created a minimal igonore.po See #1024. This now leaves some more text in default.pot, which you should review.
I'll gladly add more entries and update the PR

**Comment by luebbe** [comment]
BTW, maybe you should set the caption of the about dialog programatically so that the text: "(C) Kiriakos Vlahos 2005-2019" never makes it into the .pot file ;)

**Comment by pyscripter** [comment]
Thanks very much!
The issue was addressed by:
-  Changing a few things in the form files and source code (including the copyright)
- Updating ggexclude.cfg
- Refining ignore.po

**Comment by luebbe** [comment]
Very nice. Are you sure that "Inches" should not be translated? It is probably understood by everyone, but some translations are:
* German "Zoll"
* French "Pouce"

**Comment by pyscripter** [comment]
> Very nice. Are you sure that "Inches" should not be translated? It is probably understood by everyone, but some translations are:
> 
> * German "Zoll"
> * French "Pouce"

In Greek "ίντσες"

Ok you won.  I have removed Inches from ignore.po and recreated default.pot
