### ISSUE TITLE
Script created in Pyscripter and encoded in UTF-8 do not run from crontab

### ISSUE THREAD

**Issue by FlexMcMurphy** [pyscripter/pyscripter#1027]
Hello,

I also created a [stackoverflow ](https://stackoverflow.com/questions/64299852/executable-python-script-does-not-run-from-crontab)question about this.

I create a script: **test3.py** in NotePad++ and encode as UTF-8 with UNIX line endings. I make it executable.
```
#!/usr/bin/python

# importing modules
import os
import time
import datetime
from datetime import datetime

def f_log(strtext):
# If this method cannot write to the log file, send an email but continue script execution anyway,, fnny!
	logFilePath = '/home/osmc/python/pyscripter_file.txt'
	ts_local = datetime.now()
	ts = ts_local.strftime("%d/%b/%Y %H:%M:%S")

	try:
		# Check if the logfile exists
		if(os.path.isfile(logFilePath)):
			# Append the error message to the log file. 'a+' creates the file if it does not exist.
			with open(logFilePath, 'a+') as f:
				f.write(ts + '\t' + strtext + '\n')
		else:
			print("Log File does not exist - Creating File now")
			with open(logFilePath, 'a+') as f:
				f.write(ts + '\t' + 'Log File does not exist - Creating File now' + '\n')
				f.write(ts + '\t' + strtext + '\n')
	except IOError as e:
		# Handle the exception
		print("you made a booboo")

f_log("Test Script")
print("Hello World")
```
This script **test3.py** can run from crontab set up like this:
![image](https://user-images.githubusercontent.com/32464325/95691052-1704c580-0c14-11eb-8ab4-75025cfe9d0f.png)

However when I create a script: **test4.py** with identical content in PyScripter and encode as UTF-8 and UNIX line endings it does not run from crontab as above unless I include /usr/bin/python before the path to the script.

A hexdump of test3.py and test4.py show that PyScripter is adding in extra characters that are probably stopping the shebang on line 1 of the script from being recognized properly.
![image](https://user-images.githubusercontent.com/32464325/95691208-51bb2d80-0c15-11eb-9c11-f190d53ea190.png)

Instead of out.txt containing the text: "Hello World" instead it contains the error message:
```
/home/osmc/python/test4.py: 1: /home/osmc/python/test4.py: ﻿#!/usr/bin/python: not found
/home/osmc/python/test4.py: 4: /home/osmc/python/test4.py: import: not found
/home/osmc/python/test4.py: 5: /home/osmc/python/test4.py: import: not found
/home/osmc/python/test4.py: 6: /home/osmc/python/test4.py: import: not found
/home/osmc/python/test4.py: 7: /home/osmc/python/test4.py: from: not found
/home/osmc/python/test4.py: 9: /home/osmc/python/test4.py: Syntax error: "(" unexpected
```
After some more reading I realize that the inserted hex characters: ef bb bf are the [UTF-8 representation of the Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark) (BOM). If I select UTF-8 (No BOM) as the File Format in PyScripter then the script will run from crontab without having to specify the /usr/bin/python before the path to the script.

Why does the UTF-8 encoding in PyScripter add the BOM since that can trip Python from running the script? It doesn't in NotePad++... instead they have the option: Encode in UTF-8-BOM.

Also, do you understand why the UTF-8 (with BOM) encoded script requires /usr/bin/python to be specified before the path to the script in the crontab or else it won't run from crontab? Likewise how come the UTF-8 (without BOM) encoded script does NOT require /usr/bin/python to be specified before the path to the script in the crontab?

Cheers,

Flex

**Comment by pyscripter** [comment]
Why not save as UTF8 No Bom?  This is the default.

**Comment by FlexMcMurphy** [comment]
When I create a new python script in PyScripter it selects ANSI as the encoding and Windows line endings by default.

If I select UTF-8 it includes the BOM which can cause problems for other systems trying to run the python script if they are not expecting that magic signature.

For example, to get test3.py to run from crontab I had to change my crontab from:
`21 11 * * * /home/osmc/python/test3.py >> out.txt 2>&1`
To
`21 11 * * * /usr/bin/python /home/osmc/python/test3.py >> out.txt 2>&1`

In both cases test3.py is executable and has the shebang #!/usr/bin/python at the start of the script.

**My suggestion:**
I think in PyScripter the UTF-8 encoding should by default NOT include the BOM because it might cause problems for those python scripts in other places. Also many hobbyist programmers won't know what the BOM is and don't need to.

**My question:**
My script /home/osmc/python/test3.py is executable and has the shebang #!/usr/bin/python at the start of the script.
How come if it is encoded with UTF-8 (WITHOUT BOM) I can it run it from the command line like this: 
`# /home/osmc/python/test3.py`
But if it is encoded in UTF-8 (WITH BOM) it won't run unless I run it like this:
`# /usr/bin/python /home/osmc/python/test3.py`

Cheers,

Flex

**Comment by pyscripter** [comment]
If your file contains no character > 127 than Ansi is the same as UTF8.  PyScripter automatically saves python modules when using python 3 in utf8 and detects UTF8 when it opens files without BOM

Try the following:

- Create a new module.
-  type something like print("你好")
- Save and close the file
- Reopen the file

You will see the file opens correctly and that the file format is UTF8-No Bom,

**Comment by FlexMcMurphy** [comment]
I followed those steps and I see that behavior when using Python 3. Thank you for your patience and continued support.

As to your last point, that's why I left my suggestion above, you didn't respond to it but I think PyScripter should reverse the default behavior of UTF-8. It would be less confusing if PyScripter UTF-8 encoding did NOT include the BOM... just like NotePad++. Especially less confusing for less knowledgeable and sophisticated hobbyist Python coders (like me) who are I suspect the majority users of PyScripter.

**Can I ask another related question please?**
The script in my first comment above... my linux shell was not able to run that PyScripter UTF-8 encoded script like this:
#`/home/osmc/python/test3.py`
I had to change the command to this:
#`/usr/bin/python /home/osmc/python/test3.py`
I understand that first command doesn't work because the linux shell couldn't work out what interpreter to use (python) to run the script because the BOM magic codes were interfering with the shebang.
**BUT**
Why does the second command work?
OK, it's because in the second command I specify the python interpreter explicitly... but why is the python interpreter not tripped up by the BOM? I used a hexeditor and the BOM is inserted at the start of the script file before the shebang so shouldn't the python interpreter see it? How does the interpreter know how the script is encoded and how to handle that encoding correctly? Does the PyScripter IDE somehow pass on the encoding information to the python interpreter?

Cheers,

Flex

**Comment by pyscripter** [comment]
In general I agree and I will consider your suggestion regarding UTF8.

If I understand your question regarding the shebang, you are creating the  file with PyScripter, but you are running it not from inside pyscripter but from the Linux shell.  I am not sure why the one runs and the other doen't.  In any case the solution is to save the file as UTF8 No BOM.
