### ISSUE TITLE
Move to Weblate translation platform?

### ISSUE THREAD

**Issue by comradekingu** [pyscripter/pyscripter#1029]
Transifex is an exercise in egregious terms and conditions, would be more suitable to go with something that is libre software written in Python.

**Comment by pyscripter** [comment]
Interesting suggestion.  However, Transifex has provided us with a free license and there is dozens of PyScripter translators registered and using Transifex. A move would take considerable effort and risk losing loyal translators.

**Comment by comradekingu** [comment]
@pyscripter It isn't a free license, it is commissioning the work of others, and extracting data from them in the process. Moreover it it isn't even gratis by itself, since it is only valid for _non-commercial_ libre software (which this is not).
What you do risk is Transifex deciding you are at some point too big, and then decide to argue licensing terms. That does happen.

Losing translators isn't something that has happened for projects that move, but I agree it could. Even for the ones moving to their own instance it doesn't, and instead quality goes up. It would take a lot to not get a surge in activity with such good news, and you can log in with OAuth 2.0, so I don't see how any loyal translators would drop out. Try the importer on Hosted Weblate by setting up a libre project there. Should work nicely if it isn't all custom configuration :)
