### ISSUE TITLE
Help using the debugger

### ISSUE THREAD

**Issue by FlexMcMurphy** [pyscripter/pyscripter#1030]
Hello,

In Pyscripter when I debug a script I can set a break point and step through and over lines of code. I can place the mouse cursor over variables to see their values... but the debug window for Variables never contains anything when I am using the SSH engine. Variables and their values DO appear when using the Remote engine.

Is it possible to make information appear in the Variables debugger window when using the SSH engine?

Cheers,

Flex

**Comment by pyscripter** [comment]
Tools, Options, IDE Options, SSH, Disable Variables Window with SSH

**Comment by pyscripter** [comment]
Please use the support forum for questions.

**Comment by FlexMcMurphy** [comment]
I didn't realize there was a support forum distinct from here.
A google search reveals [this google group](https://groups.google.com/g/pyscripter).
I'll use that for general questions so.

Many thanks.
