### ISSUE TITLE
Compiling PyScripter: a fix and a remaining problem

### ISSUE THREAD

**Issue by ReinierNL** [pyscripter/pyscripter#1032]
I've downloaded the sources of PyScripter and tried to compile it (I wanted to have the fix for the problem of the 'jumping' editor insertion point). I followed the instructions from **Compilation Instructions.txt** but did not succeed completely.
First problem was that some paths in the **setup.ini** for the MultiInstaller were wrong. I am attaching an improved version here (with extension .txt because GitHub did not accept .ini.):
[Setup.ini.txt](https://github.com/pyscripter/pyscripter/files/5469521/Setup.ini.txt)

The next problems were possibly related with already installed components (SynEdit and Py4D). I've uninstalled these and removed paths from library options and then ran the MultiInstaller again. So far so good.

Then I tried the last step:  opening PyScripter.dproj and compiling it.
That fails with these errors:
[dcc64 Error] uCommonFunctions.pas(1253): E2003 Undeclared identifier: 'PyString_AsAnsiString'
[dcc64 Error] uCommonFunctions.pas(1393): E2003 Undeclared identifier: 'PyUnicode_AsWideString'

and this is where I am stuck at.
I suspect this is an easy to fix problem..

**Comment by pyscripter** [comment]
PyScripter code has not been updated to use the latest version of P4D yet.  You need to switch to the Python 2 branch to compile.

What is the jumping editor insertion point problem?

**Comment by ReinierNL** [comment]
Ok, thanks for the answer.
The problem I'm talking about is this:
[Odd movement of insertion point in editor](https://groups.google.com/g/pyscripter/c/r5Jlis0tLV8)
(a recent item on the PyScripter Groups forum)

**Comment by pyscripter** [comment]
This issue is fixed in version control.

**Comment by pyscripter** [comment]
PyScripter is now compatible with the latest version of P4D.
