### ISSUE TITLE
Does Pyscripter support two factor authentication?

### ISSUE THREAD

**Issue by FlexMcMurphy** [pyscripter/pyscripter#1033]
Hello,

I set up a remote server I want to run python scripts on that I would like to edit via SSH from Pyscripter.

To authenticate I have an RSA key pair with passphrase and also use google-authenticator on the server with an app on my phone for an additional two factor authentication... So to log in I need to type in the RSA passphrase and also another password that I get from an app on my phone.

Can Pyscripter support this? I tried and it prompts for the passphrase but I don't get another prompt for the phone app password instead an SCP Error: Network Error: Connection refused.

Cheers.

Flex

**Comment by pyscripter** [comment]
No it doesn't.
