### ISSUE TITLE
Using help crashes PyScripter

### ISSUE THREAD

**Issue by kingstairs** [pyscripter/pyscripter#1036]
Summary: Searching the help index in the Python manual can cause PyScripter to crash without error or warning.

PyScripter 3.6.4.0 x64, Win10 20H2 x64, Python 3.8.6 x64 (no venv active)

The following recipe seems to replicate the problem quite well, though it may not be 100%.

1. Launch PyScripter - if a script is auto-opened, fine. Not sure if a script loaded is required.
2. Use **Help | Python Manuals** to open the Python Documentation (not the PyScripter help).
3. On the Help index tab, type for search term, say "template". Select a help topic.
4. Click in the PyScripter window to return focus to PyScripter. You do not need to do *anything* in PyScripter.
5. Go back to the help application - just click on its window to return to the foreground.
6. Start typing "sets" in the index tab search box. After the "s" is displayed, PyScripter (and the help application) will disappear without any error or exception raised.

Since a bug in the help application shouldn't impact PyScripter, I'm thinking some kind of focus issue created at Step 4: PyScripter is not properly releasing focus when the help app is selected at Step 5.

The first step to a solution is of course replication - are the steps above enough for people to reproduce what I am seeing?

**Comment by pyscripter** [comment]
I cannot replicate this here.

**Comment by kingstairs** [comment]
Some more investigation indicates a direct link to this Python issue: https://bugs.python.org/issue35228
So it may be a bug in the Python CHM that's triggering this, but why is it taking out the parent PyScripter process? A crash in the help viewer should *not* impact the *parent* process, agreed?

**Comment by pyscripter** [comment]
Agreed.  However, it appears that the CHM crash brings down the parent process as well.  Not much I can do.  Let's hope this get fixed soon
