### ISSUE TITLE
PyScripter crashed and now doesn't work

### ISSUE THREAD

**Issue by 4ndr35py** [pyscripter/pyscripter#1037]
I'm new to python and was using PyScripter to learn it, suddenly the programm stop working, I closed it and when I tried to open it again it starts minimized and doesn't work. I have already reinstalled it and checked that python and pyscripter are the 64-bit version.

**Comment by pyscripter** [comment]
Which versions of Python/PyScripter are you using?
Did PyScripter work initially?

**Comment by 4ndr35py** [comment]
I'm using Python 3.9.0 for Windows x86-64 and PyScripter-3.6.4-x64. It used to work with out problem.

**Comment by pyscripter** [comment]
Please try the following:
Find pyscripter.ini and pyscripter.local.ini in your %APPDATA%\pyscripter directory (%APPDATA % is the value of the environment variable) and delete it.  Then restart Pyscripter.

In other words, open a command prompt and do:

```
>cd %APPDATA%\PyScripter
>del PyScripter.local.ini
>del PyScripter.ini
```

**Comment by 4ndr35py** [comment]
That worked! thank you!
