### ISSUE TITLE
Problem positioning console panel at first run

### ISSUE THREAD

**Issue by ocarillo** [pyscripter/pyscripter#1040]
I think there is a bug when you run the app for the first time. If you try to leave the Python Interpreter panel to the right side of the window, the panel takes all the screen. This happens only on the right side; on the left, up and down there is no problem as you can leave the panel well located. Once you leave the panel in one of those positions, if you try to leave the panel again on the right, then the problem dissapear.

I am showing to you an animation with the problem:
![video](https://user-images.githubusercontent.com/50459080/104436490-f55a0800-558d-11eb-8439-d68d0c8dc5b2.gif)

**Comment by pyscripter** [comment]
Fixed in version control.
