### ISSUE TITLE
Runing Code window (python interpreter) is dosen't appear

### ISSUE THREAD

**Issue by pythookie** [pyscripter/pyscripter#1104]
Runing Code window (python interpreter) is dosen't appear. (That window ise appear when I push F9) I miss it. How can I see it again? I Push again and again F9 then it dosen't appear. I click view menu then IDE windows and int.interpreter but never appear.

![hata](https://user-images.githubusercontent.com/79474527/108752436-7ffe3180-7554-11eb-9286-2a12e7b6b2ae.png)

**Comment by pyscripter** [comment]
Something must have gone wrong with the layouts.
You can use the menu command View, Layout, Default to get back the default layout.

If this does not help please do the following:

Find pyscripter.local.ini in your %APPDATA%\pyscripter directory (%APPDATA % is the value of the environment variable) and delete it.  Then restart Pyscripter.

In other words, open a command prompt and do:

```
>cd %APPDATA%\PyScripter
>del PyScripter.local.ini
```
