### ISSUE TITLE
Feature request: update recent file list when closing the program

### ISSUE THREAD

**Issue by pjinturin** [pyscripter/pyscripter#1109]
Can the new version be changed so that the recent file list be updated not only when a file is closed, but also when PyScripter is closed with the file still open? Often I work on just one file and rather than closing the tab I'll close the program, and that file is therefore not added to the list. Thanks.

**Comment by pyscripter** [comment]
Just a question:

With the "Restore Open Files" IDE option, when you restart PyScripter, you get the files you had opened, reopened.   Why do you need this?

**Comment by pjinturin** [comment]
I did think of this. This would be OK if you work on one file at a time. But if you have say 5 scripts that you are working on on-and-off you'd need to leave them all open to have a quick way of getting back to them. I agree it's not a big deal though.

**Comment by pjinturin** [comment]
I see that the latest version adds the file to the list if "Restore open files" is deselected. Perfect, thank you!
