### ISSUE TITLE
Theme integration

### ISSUE THREAD

**Issue by BBands** [pyscripter/pyscripter#1110]
It would be nice if the themes for the IDE and the editor themes were integrated, or, if that is a reach, that a few of the same themes were available in each.

Best,

     John

**Comment by pyscripter** [comment]
Currently there are a number of styles (IDE) and a number of themes (editor highlighting schemes) and the two are totally independent, i.e. you select an IDE style and separately an editor theme.

If I understand your suggestion, you would like to link them, so if say you change the style the editor theme would change as well to a matching one.    Do I understand well what you suggest?

**Comment by BBands** [comment]
Yes you do. It was just a thought I had as I set up 4.0.0. l prefer light
backgrounds, but was trying a number of themes to grok the new look. Now
that I think of it, it is probably best to leave them separate for maximum
flexibility. I'll close the issue.

Nothing else to report, all working well for me.

Very best,

    John

**Comment by pyscripter** [comment]
There is a new light highlighter theme called Ski.
