### ISSUE TITLE
When starting debugging, the caret is put in the next line after the ">>>" prompt

### ISSUE THREAD

**Issue by asmwarrior** [pyscripter/pyscripter#1111]
Hi, when start debugging, the I see the caret is moved to the next line of the ">>>" prompt, see the gif below, this cause some command(in my gif example, the `T3` command has not response.

![wrong_carret](https://user-images.githubusercontent.com/561818/115110575-b6818700-9fae-11eb-888e-e79edffc8e1d.gif)

To workaround this, I have to first press the "Backspace" key to move the caret back to the same line of the ">>>", and everything works OK. See the gif of this workaround.

![correct_carret](https://user-images.githubusercontent.com/561818/115110584-be412b80-9fae-11eb-860b-bfe36a0114f2.gif)

I think this is a bug. I'm using the 4.0.1 version.

**Comment by pyscripter** [comment]
- It has always worked like this and it is by design.  
- The reason is that when you run/debug a script, the cursor needs to be where the output should appear, starting with a new blank line.
- If you want to issue a command while debugging, the easiest way to get a prompt is to press ENTER in the interpreter window (instead of backspace).

**Comment by asmwarrior** [comment]
When I try to hit the `T3` variable(when I try to see the value of the `T3`), the debugee is already hit on a breakpoint. So, at this time, the debugee is already halted.

You mean I need to type the `Enter` key before I type the `T3`?

See the screen cast when I debugged under Spyder, I don't need to type that `Enter` or `Backspace` when I want to inspect some variables after I hit some breakpoint.

![spyder_carret_ok](https://user-images.githubusercontent.com/561818/115112657-167d2b00-9fb9-11eb-8bb6-99a30fe4d823.gif)

**Comment by pyscripter** [comment]
Yes, but that means every time you stop at a breakpoint or you step through the code your output gets littered with prompts.  I don't like that.

**Comment by asmwarrior** [comment]
> 
> 
> Yes, but that means every time you stop at a breakpoint or you step through the code your output gets littered with prompts even if you issue no commands. I don't like that.

I think this is a kind of interactive debugging. If you ever work with GDB to debug some C/C++ program, it also works like that(the way Spyder works). 

> Is pressing Enter before typing a command such a big deal?
Aha, this is really **not** a big deal.

**Comment by pyscripter** [comment]
> If you ever work with GDB to debug some C/C++ program

A GUI debugger should not imitate command line debugging.  Can do better.

In any case let me think how I can improve on the current situation.  Maybe showing a prompt and then deleting it when resuming if no command is issued.   How does this sound?

**Comment by asmwarrior** [comment]
> 
> 
> > If you ever work with GDB to debug some C/C++ program
> 
> A GUI debugger should not imitate command line debugging. Can do better.
> 
> In any case let me think how I can improve on the current situation. Maybe showing a prompt when breaking and then deleting it when resuming if no command is issued. How does this sound?

I agree, normally the "Python interpreter's caret" is hidden when the debugee is resuming. Unless the debugee is asking user to enter some text, in this case, the prompt from the debugee, not from the Python interpreter.

**Comment by pyscripter** [comment]
I ended up implementing this idea.  Hope you will like it.

> Maybe showing a prompt when breaking and then deleting it when resuming if no command is issued. How does this sound?

**Comment by asmwarrior** [comment]
Hi, thanks for your work!

If there will be a pre-build version including this new feature, I will test/use it.

**Comment by pyscripter** [comment]
Since you asked https://drive.google.com/file/d/1uCqGG2m0ruMz6zo2ElGoMIeOsf2niqpH/view?usp=sharing

**Comment by asmwarrior** [comment]
> 
> 
> Since you asked https://drive.google.com/file/d/1uCqGG2m0ruMz6zo2ElGoMIeOsf2niqpH/view?usp=sharing

Thanks. I just tested it, and it works OK!
