### ISSUE TITLE
code hint/find definition does not work correctly for some functions

### ISSUE THREAD

**Issue by asmwarrior** [pyscripter/pyscripter#1112]
I found that some code hint does not shown correctly.

For example, when using the `robotics-toolbox-python` package:  https://github.com/petercorke/robotics-toolbox-python, when open a source file, I see that when the mouse hover the `jd = puma.jointdynamics(puma.qn)`, the function definition `jointdynamics` can't be find, while under Spyder, it can be found and go to that definition.

Both the PyScripter 4.0.1 and Spyder 3.2.5 are using the same Python distribution 3.8.8.0.

Here is the screen cast of PyScripter:
![definition_not_found](https://user-images.githubusercontent.com/561818/115112235-272ca180-9fb7-11eb-9e7f-b8bccd549e01.gif)

Here is the screen cast of Spyder:
![definition_OK](https://user-images.githubusercontent.com/561818/115112247-37448100-9fb7-11eb-937c-36b832e13144.gif)

Note that PyScripter can find other definitions. For my testing, only the `jointdynamics` is not showing the code hint window.

**Comment by pyscripter** [comment]
You can get better code-completion hints etc, if you add some packages to Tools, Options, IDE Options, Code completion, Special packages eg. change it to 

> os,roboticstoolbox

The next development in PyScripter is to use JEDI for code support (language server), so you would get the same quality of hints, definitions, references etc. as in Spyder.

**Comment by asmwarrior** [comment]
> 
> 
> You can get better code-completion hints etc, if you add some packages to Tools, Options, IDE Options, Code completion, Special packages eg. change it to
> 
> > os,roboticstoolbox
> 


I just tried it, but this does not solve this issue. I don't know how the internal this IDE works, maybe the parser is failed to parse some code.

> The next development in PyScripter is to use JEDI for code support (language server), so you would get the same quality of hints, definitions, references etc. as in Spyder.

That's a good direction! Hope I won't wait for a long time to see the JEDI based release.

**Comment by pyscripter** [comment]
By the way and since you are using Spyder, may I ask why you are using PyScripter?

**Comment by asmwarrior** [comment]
> 
> 
> By the way and since you are using Spyder, may I ask why you are using PyScripter? i.e. what are the things you prefer in relation to Spyder?

Spyder has some issue to catch the error when I debug the robotictoolbox, see this issue report here:

[Debugger not working with the roboticstoolbox package](https://github.com/spyder-ide/spyder/issues/15243)

In-fact, I'm using Spyder for a long time. After that issue report in Spyder, I notice that Spyder developer's response is not quite active, because my usage is quite special, and they can't solve that issue soon, so, I try to seek another IDE, and finally I found PyScripter. When debugging, both Spyder and PyScripter can inspect variables or type command when I hit some breakpoints, while other IDEs can't. 

And that's the whole story I post issues in PyScripter's github site later.

**Comment by pyscripter** [comment]
I am closing this one.  You can monitor progress on #1113.
