### ISSUE TITLE
Implement the Language Server Protocol

### ISSUE THREAD

**Issue by pyscripter** [pyscripter/pyscripter#1113]
It would allow PyScripter to use [LSP](https://microsoft.github.io/language-server-protocol/) servers such as [this one](https://github.com/pappasam/jedi-language-server)

**Comment by asmwarrior** [comment]
good work！

**Comment by asmwarrior** [comment]
any nightly build version I can try it?

**Comment by pyscripter** [comment]
I will publish a pre-release in the next few days.
