### ISSUE TITLE
Docking

### ISSUE THREAD

**Issue by achambily** [pyscripter/pyscripter#1114]
How do you dock the interpreter on the right side ? (pyscripter 4.0)
If I try to do this, it becomes full screen.

**Comment by pyscripter** [comment]
Please download again and install v.4.0.0.  It should now show v4.0.0.6.  Do you still have the same issue?

If yes please find pyscripter.local.ini in your %APPDATA%\pyscripter directory (%APPDATA % is the value of the environment variable) and delete it.  Then restart Pyscripter.

In other words, open a command prompt and do:

```
>cd %APPDATA%\PyScripter
>del PyScripter.local.ini 
```

Does this help?

**Comment by ocarillo** [comment]
This error was reported at #1040 by me. I have checked now, and solved by installing the last version as suggested. Tested on Win10 64bit.

Anyway, you can place the interpreter in the right side following these steps:

On first run, put the panel on the left side. Yo should be able to do this.
Once you do, you will be able to put the panel in the right side.

Hope it helps.
