### ISSUE TITLE
Duplicate Keyboard Accelerators in File menu

### ISSUE THREAD

**Issue by primenumber59** [pyscripter/pyscripter#1119]
In the File menu A is the keyboard accelerator for the Save As and Save All commands.

This means extra keystrokes are necessary for the common action of File, Save As.

As a suggestion, the A accelerator for Save All, could be removed, and instead a commonly(?) used keyboard shortcut of Ctrl+Shift+S could be assigned by default to Save All.

**Comment by pyscripter** [comment]
The other menus also have duplicated accelerator keys, but since they are not used as "standard" I don't think they matter as much, although F and R in the Search menu might bother someone?

**Comment by pyscripter** [comment]
Fixed quite a few more conflicts as well.
