### ISSUE TITLE
PyScripter could not load a Python engine (Python 3.9)

### ISSUE THREAD

**Issue by ShadyMBA** [pyscripter/pyscripter#1120]
Hi,

Thanks for your great work. I love PyScripter! I've installed the latest version of Python (3.9) and have verified that it is working properly from the cmd prompt.
I have also verified that my Python is 64 (as confirmed by the screenshot)
However, when I opened PyScripter I have received the error in the screenshot even though it seems that PyScripter sees a valid Python engine. Any ideas how to fix this problem? Thanks

![image](https://user-images.githubusercontent.com/58062696/119866407-c7e17b80-beea-11eb-99a5-1fb64c23e35d.png)

![image](https://user-images.githubusercontent.com/58062696/119866592-f5c6c000-beea-11eb-9a7e-622af1b2e933.png)

![image](https://user-images.githubusercontent.com/58062696/119866650-05460900-beeb-11eb-9a25-655616ea1229.png)

**Comment by pyscripter** [comment]
Here Python 3.9.5 64 bits loads fine, so there must be a conflict somewhere.

Things to check and try.

- Add the installed version as an unregistered version and see if it loads that way.  (Press the second button and specify the path to the python version).
- Check whether the environment variables PYTHONHOME or PYTHONPATH have been set.
- Check the Registry entry for this Python version (keys Computer\HKEY_CURRENT_USER\SOFTWARE\Python\PythonCore\3.9 or
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\3.9.  Do they look OK?  Do the InstallPath and PythonPath subkeys point to the correct paths?
- Check the content of the python install directory.  Does it contain python39.dll?

**Comment by llarsen71** [comment]
I have a copy of 32 bit Python 2.7 installed from python.org on my windows 10 computer. I had this working with a previous version of Pyscripter. However, when I uninstalled Pyscripter and then installed Pyscripter 4.0 x86 version, Pyscripter is unable to detect my Python instance. I have tried using the + symbol to select the Python27 folder using both the registered and unregistered version items without success.

There is no PYTHONHOME or PYTHONPATH defined when I look at environment variables.

Interestingly I do not see registry keys for Python. Is it standard for the Python2.7 installer to add registry keys? Are these necessary for it to find python?

I also looked for the python27.dll. This was not included in the Python27 folder, but could be found in c:\windows\SysWOW64.

What do I need to do to get Pyscripter configured to use python. Do I need to reinstall python?

**Comment by pyscripter** [comment]
@llarsen71  PyScripter version 4.x does not support python 2.x.  If you want to use python 2.x with PyScripter, please download and install an earlier version of PyScripter.

**Comment by ShadyMBA** [comment]
@pyscripter Thank you so much for your punctual response. The problem kind of solved itself...I installed Anaconda for other purposes but seems that your program was able to detect Python out of Anaconda installation so it's working now. Many thanks!

**Comment by pharhp** [comment]
Just went through several rounds of install/uninstall python311 x64 and pyscripter. multiple attempts to make sure there was nothing being left from previous installation etc. all to no avail. I installed anaconda as suggested above and everything works as expected now with the python distro installed by Anaconda. It would seem to me that the issue here may be with the python installer not setting up something that pyscripter is depending on to function properly.
