### ISSUE TITLE
Pyscripter 4 doesn't find Python 2.7.18 32bit

### ISSUE THREAD

**Issue by hitech-hifi** [pyscripter/pyscripter#1121]
Hi I am trying to install Pyscripter V4 but it doesn't recognize Python 2.7.18 32bit installation and shows error that the usable installation is not found. 

Pyscripter V3.6.4 automatically finds the same python installation without any issues. 

Please advice how to setup V4 with Python 2.7.18 32bit.

Thanks

**Comment by pyscripter** [comment]
I am afraid, support for python 2.x has been dropped in PyScripter 4.  If you want to keep on using python 2.x with PyScripter, please use an earlier version of PyScripter installed side-by-side with PyScripter 4.
