### ISSUE TITLE
Remote server is not connected error

### ISSUE THREAD

**Issue by oelozada** [pyscripter/pyscripter#1126]
![image](https://user-images.githubusercontent.com/90930751/133840956-a9af336f-b41b-4ada-99b8-ce166aeb9923.png)

Could you helpme with this error?

**Comment by pyscripter** [comment]
Your python program has crashed.   You need to reinitialize the remote engine, by the menu command Run, Python Engine, Reinialize.  The command is also available from the Status bar and the Interpreter Window context menu.

**Comment by oelozada** [comment]
I did it and then run it again and the same box error.
You can see at the Python Interpreter console it was reinitialized and the subprocess es executed, so i dont understand why the engine crashed.

**Comment by pyscripter** [comment]
You have to investigate why your script crashes python.   I can't help you with that.

**Comment by pyscripter** [comment]
Your script does not make much sense.  You are returning a boolean and the print(response) will never be executed.

import subprocess

```python
def ping():
    hostname = "150.1.3.201"
    return subprocess.check_call("ping 127.0.0.1", shell=False) == 0

print(ping())
```
runs fine.
