### ISSUE TITLE
translate line 4178 is not work

### ISSUE THREAD

**Issue by ystartgo** [pyscripter/pyscripter#1133]
line 4178 : Manage Python &Path...
When translate 4178 is not work.

#. FileExplorerWindow..BGPanel..FGPanel..ExplorerDock..ExplorerToolbar..TBXSubmenuItem1..tbiPythonPath..Caption
#. FileExplorerWindow..ExplorerPopUp..mnManagePythonPath..Caption
#: frmFileExplorer.dfm
msgid "Manage Python &Path..."
msgstr "管理Python路徑(&P)..."

**Comment by pyscripter** [comment]
What exactly is the problem?

**Comment by ystartgo** [comment]
I found  https://imgur.com/DHUxSA6 it translate is not work, show default english

#. FileExplorerWindow..BGPanel..FGPanel..ExplorerDock..ExplorerToolbar..TBXSubmenuItem1..tbiPythonPath..Caption
#. FileExplorerWindow..ExplorerPopUp..mnManagePythonPath..Caption
#: frmFileExplorer.dfm
msgid "Manage Python &Path..."
msgstr "管理Python路徑(&P)..."

**Comment by pyscripter** [comment]
I see...   Will look into it.

**Comment by pyscripter** [comment]
By the way you are now a member of the PyScripter translation team.
Please translate language.po
Optionally, you may want to translate the installation program.  Have  a look at https://github.com/pyscripter/pyscripter/tree/master/Install/locale

**Comment by pyscripter** [comment]
The fix will be available in the next release
