### ISSUE TITLE
pyinstaller show SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ystartgo** [pyscripter/pyscripter#1135]
When pyscripter pip pyinstaller is done and try to execute pyinstaller -F ./test.py
show SyntaxError: invalid syntax
file path cannot recognize

**Comment by pyscripter** [comment]
> try to execute pyinstaller -F ./test.py

Where are you running this command from.

You can create an External Tool for using pyinstaller. Tools, Configure Tools, Add:

![image](https://user-images.githubusercontent.com/1311616/136689270-122cb5fa-ae2f-42ae-8226-56f9503091b4.png)
