### ISSUE TITLE
Issue with unclosed script with RDS

### ISSUE THREAD

**Issue by electropica** [pyscripter/pyscripter#1137]
Hello,

we run PysSripter 3.6.3.0 x64 from EduPython under RDS session on thin clients.

Last open script stay open from session to an other and each user can see all recents openned scripts.
This brings error when trying to save it because user think its his own script.
Is there something to configure to close script when we quit PyScripter ?

Thank you.

![pyscripter_recents](https://user-images.githubusercontent.com/552299/137683610-d69bad3d-8053-402f-b8a8-4661f36204ec.JPG)

**Comment by pyscripter** [comment]
The open files information is saved in PyScripter.ini.  This file can be either in the same directory as PyScripter.exe in portable installations or else in %APPDATA%\PyScripter where %APPDATA% is the value of the environment data.

To prevent the next user from seeing the files opened by the previous user you can either process the PyScripter file and set:

```ini
[Open Files]
Count=0
ActiveEditor=
```

Alternatively, delete PyScripter.ini altogether or replace it with a default one  before or after running PyScripter (say using a batch file) and the next user can have  a fresh start.

**Comment by pyscripter** [comment]
- Yes you could set RestoreOpen Lines to False.
- Or you could replace pyScripter.ini with an new copy everytime you run PyScripter.
- Or you could remove/modify the sections with [Open Files] from the ini file.

I know you use EduPython, which is portable (PyScripter.ini is in the same directory as PyScripter.exe).   But if is used by many users it would make sense to have the PyScripter installed version.  That would allow every user to have their own PyScripter.ini file in %APPDATA%\PyScripter.

**Comment by electropica** [comment]
Ok.
Thank you.
