### ISSUE TITLE
Problems Upgrading to 4.1

### ISSUE THREAD

**Issue by Hiltronix** [pyscripter/pyscripter#1139]
Hello,

I'm having 2 noticeable problems upgrading to 4.1 from 4.0.  I'm using Windows 10 64bit.  Upgrading into same location as 4.0, witch was working fine on a daily basis.  

The first problem is that code completion doesn't work in 4.1 for me, and it did in 4.0.  Do I have to install something separately for this new Jedi Intellisense feature that I read about?  I thought I read that it's being installed as part of 4.1.

The second problem is that I get a rapid series of error messages when closing PyScripter.  I'm unable to click the button to "Send" the error report, as they close on their own almost immediately, and there are roughly 9 of them in a row that look the same.

I notice the new INI file is now 3 times the size as for 4.0.  Or at least what is now called "PyScripter.local.ini".  If I start 4.1 with "PyScripter.local.ini" renamed to "PyScripter.ini", I don't get the error messages when closing, but code completion still doesn't work.  And all my IDE settings are changed, or at least the defaults.

If I downgrade to 4.0 everything works fine again, and no errors messages when closing.  I'd love to upgrade to 4.1, without a clean install, so I don't have to set up everything from scratch again

I'm attaching this INI files in case that's of some help.

Thank you.

[Temp.zip](https://github.com/pyscripter/pyscripter/files/7385031/Temp.zip)
.

**Comment by pyscripter** [comment]
PyScripter v4.1.1 has been released.  Please try that.

Are you using the installed version or the portable version? (zip file)?   

The difference is that the portable version keeps everything into the PyScripter directory.  PyScripter detects it is portable mode by the presence of PyScripter.ini in the same directory as PyScripter.exe file.

The installed version places ini files and a few more in the %APPDATA%\PyScripter directory.   (Typically %APPDATA% is the c:\users\username\AppData\Roaming folder.)  In recent versions the installer places a number of folders under c:\Program Data\Pyscripter (highlighters, themes, and the Jedi Language Server).

If you are afraid of losing your customizations please don't.   PyScripter stores  all settings in two files:
PyScripter.ini and PyScripter.local.ini.  The second contains stuff which is specific to the computer you are working (Layouts, Open Files).   PyScripter.ini stores everything else.   The installer does not overwrite these files in %APPDATA%\PyScripter, so you will keep all your settings when using the installer.

Please also bear in mind that the portable version needs full access to the directory it is installed.  So it cannot be placed in the Program Files folder for instance.

**Comment by pyscripter** [comment]
There is a Language Server indicator at the right of the PyScripter Status bar.  If it is gray it means the the Language Server has not started.  (It will say so if you hover the mouse).  What color is yours? The 5 seconds delay in showing the Code Explorer is normal.  It will get shorter the second time you run PyScripter, because the Python code will have been compiled.  If the Code Explorer displays the script structure, it means that the Language Server is working and you should get code completion.

**Comment by Hiltronix** [comment]
Update to my previous comment.  Code completion is working!  But not the first several times I try.  After several attempts, I finally do get the drop down context menu with suggestions, but it takes a while to start working, just like the Code Explorer pane takes a while to display.  These things seems instant with 4.0.  Is this just the nature of the changes to the Jedi Language Server?

**Comment by Hiltronix** [comment]
The status bar indicators show: 
    Debugger state: Ready (Green)
    Lanuage server: Ready (Orange). 
So it must be working.
Yes I currently have 11 files open all with several thousand lines of code each.
Disabling syntax check doesn't seem to make much difference at a glance.  But maybe I need to work with it for a while.

**Comment by pyscripter** [comment]
Could you post your file here please?
_pydecimal.py (6k lines) and turtle.py (4K lines) from the standard library here show up fine in Code Explorer and in no time.
You can turn on Lsp Debug output through IDE options.  In that case LSP diagnostic output is produce in a file at %APPDATA%\PyScripter.

**Comment by pyscripter** [comment]
Please see a fix in #1140
