### ISSUE TITLE
TB2K-Patch

### ISSUE THREAD

**Issue by groehner** [pyscripter/pyscripter#1141]
The patch in
pyscripter/Components/ThirdParty/TB2KPatch-2.2.2.zip 
doesn't include the creation of the attribute ImageName for class TTBCustomItem

The correct patch is in 
https://github.com/pyscripter/SpTBXLib/blob/master/TB2K%20Patch/tb2kdiff.txt

**Comment by pyscripter** [comment]
https://github.com/pyscripter/SpTBXLib/blob/master/TB2K%20Patch/tb2kdiff.txt and the tb2kdiff.txt inside pyscripter/Components/ThirdParty/TB2KPatch-2.2.2.zip are identical.  

One of your two repos must be out of sync.
