### ISSUE TITLE
Does the latest version of PyScripter (4.1.1) support Python 2.7 32-Bit?

### ISSUE THREAD

**Issue by ianbroad** [pyscripter/pyscripter#1143]
I use ESRI's ArcMap application at work and they are still using Python 2.7 32-Bit. It's what comes with a standard install even though I know it's not supported anymore.

I downloaded the latest version of PyScripter (4.1.1) and when I browse to the 2.7 install path it states that it can't find a usable Python installation at the specified path.

Is there a way to get it to work with 2.7 32-Bit? I need to use ESRI's Python library that comes with their install.

**Comment by pyscripter** [comment]
PyScripter version 4.x dropped support for python 2.   The last version of PyScripter supporting python 2 is 3.6.  You can use the portable version of PyScripter 3.6 alongside PyScripter 4.x if you want to work with python 2 projects.

See https://github.com/pyscripter/pyscripter/wiki/History for details.

**Comment by ianbroad** [comment]
Thanks
