### ISSUE TITLE
PyScripter - Import Arcpy ModuleNotFoundError: No Module named 'arcpy'

### ISSUE THREAD

**Issue by jonah84** [pyscripter/pyscripter#1145]
Please help I use to be able to run PyScripter no problem ran an esri update and now I'm unable to launch the application. Very frustrating. Can anyone shed light on why this is not importing the arcpy library and provide a viable solution. I have tried all the other Q and A forums without success. Thanks in advance

![1](https://user-images.githubusercontent.com/13709088/142649595-563317e0-5d5f-4dc9-aa5c-11891a4efc46.png)

![4](https://user-images.githubusercontent.com/13709088/142650231-417f9cb6-320e-47d1-899c-6c80d186d347.png)
![2](https://user-images.githubusercontent.com/13709088/142650240-27788d69-da86-44e0-9dc5-bc985f20475c.png)
![3](https://user-images.githubusercontent.com/13709088/142650256-eb641bba-2224-454d-8fe3-4b93067b7920.png)

**Comment by pyscripter** [comment]
- Can you import arcpy from the ArcGIS python prompt (outside PyScripter)?
- If yes, please do
> import sys
> sys.path

What do you get?

If not then there is something wrong with the installation.

I have provided some instructions for using PyScripter with ArcGIS Pro at https://pyscripter.blogspot.com/2018/10/using-pyscripter-with-arcgis-pro.html.  But ArcGIS Pro uses python 3.x and ArcGIS python 2.x.

Please also note that PyScripter no longer supports python 2.x.  You need to use the last version of PyScripter that supports python 2.x which 3.6

**Comment by jonah84** [comment]
>>> import sys
>>> sys.version
'2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:19:08) [MSC v.1500 32 bit (Intel)]'
>>> sys.path
['', u'c:\\program files (x86)\\arcgis\\desktop10.8\\arcpy', 'C:\\Python27\\ArcGIS10.8', 'C:\\WINDOWS\\SYSTEM32\\python27.zip', 'C:\\Python27\\ArcGIS10.8\\Lib', 'C:\\Python27\\ArcGIS10.8\\DLLs', 'C:\\Python27\\ArcGIS10.8\\Lib\\lib-tk', 'C:\\WINDOWS\\system32', 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.8\\bin', 'C:\\Python27\\ArcGIS10.8\\lib\\site-packages', 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.8\\ArcPy', 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.8\\ArcToolBox\\Scripts']
>>> 


Also I'm running PyScripter 4.1.1
Also I'm only using ArcMap 10.8 and Not using Pro

Thanks in advance pyscripter!!!

![image](https://user-images.githubusercontent.com/13709088/142664080-4610e386-8f0a-4604-a39b-46d16420aeb3.png)

**Comment by pyscripter** [comment]
PyScripter 4.x does not support python 2.x.
Also ArcGIS python is 32 bits.

You will need a 32-bit version of PyScripter that supports python 2.x.  PyScripter 3.6 32-bits is the latest version.

You can either uninstall your current version of PyScripter and install PyScripter 3.6 32-bits from [here](https://sourceforge.net/projects/pyscripter/files/PyScripter-v3.6/) or download the registry-free installation file (PyScripter-3.6.4-x86.zip) unzip it and run PyScripter from there.  The latter allows you to have both versions of PyScripter installed.

**Comment by pyscripter** [comment]
By the way where did you download ArcGIS Desktop from?   The only thing I could find without paying is ArgGIS Pro trial version.

**Comment by pyscripter** [comment]
See also https://support.esri.com/en/technical-article/000017479.

**Comment by jonah84** [comment]
Still no luck here with that advice.

Huge thanks in advance. I'll mail you a gift card if someone can provide a solution. I've be manipulating paths for 2 days now.

This is a major pain in my #$% . Does anyone know how to fix this no module named arcpy
![image](https://user-images.githubusercontent.com/13709088/142954654-2d97faf3-e270-49ee-8aa7-f60d85c13246.png)


Just some background I'm using ArcGIS Desktop 10.8

System Environment Variables for the PATH
![image](https://user-images.githubusercontent.com/13709088/142954072-8a3b4da6-a7c7-40f3-b6a3-784bd0bb1c5c.png)


Pyscripter Path
![image](https://user-images.githubusercontent.com/13709088/142954378-fde48c13-bf5b-4c00-81b9-fba508e5453d.png)


ArcMap Internal Python
![image](https://user-images.githubusercontent.com/13709088/142954438-1eb2da88-ecaf-4d66-95b7-8c6d99ef871b.png)

C:Python 27 Directory
![image](https://user-images.githubusercontent.com/13709088/142954486-f0f35017-36dc-4170-aed9-51d96ab3b18c.png)

Python .pth file
![image](https://user-images.githubusercontent.com/13709088/142954559-476981e2-3ccb-4b38-968a-40e7c6c68dd9.png)

**Comment by pyscripter** [comment]
I don't think you understood what I said.
It looks like you are using the latest version of PyScripter (4.1) with python 3.9.   This will not work since PyScripter 4.x does not support python 2 and ArcMap is still using the now unsupported python 2

You need to:
-  Unistall PyScripter
-  Download and install PyScripter 3.6 32-bits from [here](https://sourceforge.net/projects/pyscripter/files/PyScripter-v3.6/).  This is the last version of PyScripter with python 2 support.

Then try again.

To be able to help you I will need to install here ArcGIS Desktop.  Is there a free version? where do I find it?

**Comment by jonah84** [comment]
Okay sorry let me try that and I'll get back to you. Gift card still stands if this works. Thanks in advance

**Comment by pyscripter** [comment]
If you insist, you can make a donation using the donate button in the homepage https://github.com/pyscripter/pyscripter.
