### ISSUE TITLE
Activating a Python-Version when using portable version

### ISSUE THREAD

**Issue by groehner** [pyscripter/pyscripter#1146]
I have installed a portable version of PyScripter on an usb-stick.
When i change from my PC to a laptop, i'm noticed that PyScripter could not load a Python engine.
Then the window "Setup Python Versions" is automatically opend, but is it's not possible to activate the installed version, because the 
activation button isn't enabled.

I think in TPython.Control.InitPythonVersions you have to intialize fPythonVersionIndex with -1
![portable](https://user-images.githubusercontent.com/53400267/142740142-7b55278f-3ebb-4dc1-b11d-b1d4c929923e.png)
.

**Comment by pyscripter** [comment]
Fixed in version control.

As a workaround edit PyScripter.local.ini (in same folder as PyScripter.exe)  find and correct the  following lines:

[PythonVersions-x64]
SysVerion=3.10
