### ISSUE TITLE
PyScripter and python 3.10 match

### ISSUE THREAD

**Issue by shineworld** [pyscripter/pyscripter#1147]
Hi,
I'm trying PyScripter with python 3.10 and seem that AST do not recognize new keyword 'match':
![image](https://user-images.githubusercontent.com/1633598/142762525-547409ce-07b7-4c52-9509-b5e0eddc97a7.png)

**Comment by pyscripter** [comment]
From https://www.python.org/dev/peps/pep-0622/

`The match and case keywords are proposed to be soft keywords, so that they are recognized as keywords at the beginning of a match statement or case block respectively, but are allowed to be used in other places as variable or argument names.`

**Comment by pyscripter** [comment]
As for the reported syntax errors this is a Jedi issue.  See:
https://github.com/davidhalter/jedi/issues/1756
https://github.com/davidhalter/parso/issues/138

Hopefully we get a fix at some point.
