### ISSUE TITLE
PyScripter V4.1.1.0 x64 crashed by using Python Manuals

### ISSUE THREAD

**Issue by gmu-code** [pyscripter/pyscripter#1148]
If i use the Manual over PyScripter **Help > Python Manuals**
and using it with any searches and any scrolling and klicks, the manual and the PyScripter crashed without any message box.
The both windows where closed.

I'am using Windows 11 x64 and Python 3.9.1 x64

**The application log says (german):**

```
Protokollname: Application
Quelle:        Application Error
Datum:         27.11.2021 12:34:14
Ereignis-ID:   1000
Aufgabenkategorie:(100)
Ebene:         Fehler
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      XXX
Beschreibung:
Name der fehlerhaften Anwendung: PyScripter.exe, Version: 4.1.1.0, Zeitstempel: 0x6170beee
Name des fehlerhaften Moduls: hhctrl.ocx, Version: 10.0.22000.1, Zeitstempel: 0xfdac397f
Ausnahmecode: 0xc0000005
Fehleroffset: 0x0000000000040b81
ID des fehlerhaften Prozesses: 0x488c
Startzeit der fehlerhaften Anwendung: 0x01d7e382a8085594
Pfad der fehlerhaften Anwendung: C:\Program Files\PyScripter\PyScripter.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\SYSTEM32\hhctrl.ocx
Berichtskennung: 42a7d6f8-b1b9-4a0b-8998-6f95dcf405cf
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-11-27T11:34:14.7679827Z" />
    <EventRecordID>15265</EventRecordID>
    <Correlation />
    <Execution ProcessID="22120" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>XXXX</Computer>
    <Security />
  </System>
  <EventData>
    <Data>PyScripter.exe</Data>
    <Data>4.1.1.0</Data>
    <Data>6170beee</Data>
    <Data>hhctrl.ocx</Data>
    <Data>10.0.22000.1</Data>
    <Data>fdac397f</Data>
    <Data>c0000005</Data>
    <Data>0000000000040b81</Data>
    <Data>488c</Data>
    <Data>01d7e382a8085594</Data>
    <Data>C:\Program Files\PyScripter\PyScripter.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\hhctrl.ocx</Data>
    <Data>42a7d6f8-b1b9-4a0b-8998-6f95dcf405cf</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

```

Thanks for support and the nice PyScripter.

**Comment by pyscripter** [comment]
This is because you have not installed the python manuals.  
Python distributions from www.python.org  come with the manuals included (CHM file in the Doc subdirectory) but other distributions, including Conda, do not.  You can copy the chm file from a distribution that includes it to the Doc subdirectory of you python installation path.

By the way when you say crashed, does this mean you were not able to carry on work?

**Comment by pyscripter** [comment]
Here I have tested with PyScripter 4.1 x64 Python 3.9 Windows 11 and it works fine.

-  Could it be that there are problems with the chm file viewer (hhctrl.ocx)?  See  https://www.exefiles.com/en/ocx/hhctrl-ocx/ for possible issues and fixes.
- Can you open the python help file (in the Doc subdirectory of you python installation) by double-clicking?

**Comment by gmu-code** [comment]
Yes, I can open the chm file.

It's strange because PyScripter crash also and not only the help window.

**Comment by pyscripter** [comment]
Indeed strange.  Some of the things that would help to know:

- Is the chm file by any chance on a network drive?
- Is this issue related to Windows 11?
- Do you get the same issue with earlier versions of PyScripter?
- Do you get the same issue with other versions of python?
- Can you reproduce the issue in a different computer?

**Comment by pyscripter** [comment]
No feedback for a long time.   Have not had any similar reports.
