### ISSUE TITLE
update the release section of the github page

### ISSUE THREAD

**Issue by asmwarrior** [pyscripter/pyscripter#1150]
Hi, from your blog(https://pyscripter.blogspot.com/), I see that the latest release is 4.1.1.

But when I looked at the github page, it release section still shows 4.0.0.

So, I suggest update the github release page. Thanks.

**Comment by pyscripter** [comment]
The github releases are source code only.  Binary releases (downloads) are at SourceForge.  Few developers are interested in source code releases and the advice is to use the master branch.  In any case, I will try to make a new one to coincide with the next binary release.

**Comment by asmwarrior** [comment]
I see you have new release tag, that's great! I got the email notification.

I would suggest that you could put a link like https://sourceforge.net/projects/pyscripter/files/PyScripter-v4.3/

In the download section(currently you don't have such section) of the github home page markdown file, so people can easily find the binary file to download it.

Thanks.

**Comment by pyscripter** [comment]
Thanks.  I have added a link in the release info.

> currently you don't have such section) of the github home page

![image](https://github.com/pyscripter/pyscripter/assets/1311616/90ab2c76-68f9-4dc6-ba7a-27a36c840b32)

**Comment by asmwarrior** [comment]
OK, and another suggestion: I think the binary download link such as:

[PyScripter - Binary and source Files at SourceForge.net](https://sourceforge.net/projects/pyscripter/files/)

should be appeared in your github home page.

**Comment by asmwarrior** [comment]
> ![image](https://user-images.githubusercontent.com/1311616/275125779-90ab2c76-68f9-4dc6-ba7a-27a36c840b32.png)

Oh, I see the image(icon), but please note that I don't notice this image can be clicked(and it is a link), and I strongly suggest add a text link about "Download".

**Comment by pyscripter** [comment]
Ok.  I can see that other people can be confused.
