### ISSUE TITLE
Code Explorer based on LSP doesn't show attributes

### ISSUE THREAD

**Issue by groehner** [pyscripter/pyscripter#1152]
The code explorer window based on LSP doesn't show attributes anymore.

![grafik](https://user-images.githubusercontent.com/53400267/145682126-f7e9f42b-1aa3-4379-b0f4-bc4ffb34b1d8.png)

Parameters are also no longer displayed .

**Comment by pyscripter** [comment]
Fixed in version control.  The fix will be available in v4.2.2
