### ISSUE TITLE
Code Explorer shows no content.

### ISSUE THREAD

**Issue by pqwer99** [pyscripter/pyscripter#1155]
when pyscripter(4.1.1 x86) is installed in a path with space, the code explorer shows no content.

**Comment by pyscripter** [comment]
Strange since by default PyScripter 32 bits installs in "C:\Program Files (x86)\PyScripter" which contains a space and no one has complained.

**Comment by pyscripter** [comment]
Fixed in version control.   The fix will be available in the next release.
