### ISSUE TITLE
PyScripter could not load a Python engine (Python 3.10.2)

### ISSUE THREAD

**Issue by JeanPhi007** [pyscripter/pyscripter#1156]
Hello,

I know this question has been asked before, but solutions discussed seem so complicated that I wonder if there something more simple.
I've installed Python 3.10.2 (64bits) without changing the proposed folder (c:\users\MyName\AppData\Local\Programs\Python\Python310) and I can start Python via command line
![image](https://user-images.githubusercontent.com/62078799/151026181-d4505aff-5c99-473f-865b-efab5a029587.png)

My question is: how to tell to PyScripter to look at this folder(..\AppData\..) as it's impossible to open it with the Browse folder dialog?

Thanks in advance
Jean-Philippe

**Comment by pyscripter** [comment]
First allow the display of hidden files.  See https://www.technipages.com/show-hidden-files-windows 

Then use the Run, Python Versios, Setup Python Versions dialog to your version.

**Comment by JeanPhi007** [comment]
Hello,

Thank you for the answer (I didn't know this trick) but unfortunately it doesn't work. I've always this message 
![image](https://user-images.githubusercontent.com/62078799/151121170-3bb5e021-b683-473b-9926-481bd69cddd5.png)

despite the fact that python.exe is in this folder

![image](https://user-images.githubusercontent.com/62078799/151121553-7c3163cf-195f-45f9-bd2f-18b41df4e0c1.png)

and versions of both PyScripter and Python are both 64bits
![image](https://user-images.githubusercontent.com/62078799/151122666-779d0ec1-4814-4904-9bd2-9a17957d1709.png)
![image](https://user-images.githubusercontent.com/62078799/151122749-c1d53081-da3e-4c61-9f01-78c58a2c3381.png)

it's stange because I don't remember having any problem with previous version of Python, which was installed in a similar directory

**Comment by pyscripter** [comment]
Are you using PyScripter 3.6?  Support for Python 10 was provided in version 4.  Please download the latest version of PyScritper and try again.

**Comment by JeanPhi007** [comment]
Yessss, it works. And the new look seems great!
Thank's a lot
