### ISSUE TITLE
Update PO files from Transifex

### ISSUE THREAD

**Issue by excript** [pyscripter/pyscripter#1159]
I finished the Portuguese translation but in the latest version (4.0.0.6 x64), the PO pt_BR files are not available.

**Comment by pyscripter** [comment]
Thanks very much.  Will do.

**Comment by pyscripter** [comment]
The files have been updated automatically.  See https://github.com/pyscripter/pyscripter/tree/master/locale/pt_BR/LC_MESSAGES.  

The new complete Portuguese (Brazil) translation will be available with the next release.  In the meantime please consider submitting a translation of the installation program.  See https://github.com/pyscripter/pyscripter/tree/master/Install/locale.
