### ISSUE TITLE
Impossible to choose the idiom

### ISSUE THREAD

**Issue by excript** [pyscripter/pyscripter#1160]
The language changes when selecting a new language, but visually it is not displaying correctly in the main menu.

![image](https://user-images.githubusercontent.com/10388739/153041616-ed8fae60-4246-4a8f-932d-555ab5da2601.png)

** In the image above, I changed the PO pt_BR files manually.

**Comment by pyscripter** [comment]
The new complete Portuguese (Brazil) translation will be available with the next release.
