### ISSUE TITLE
Virtual Environments

### ISSUE THREAD

**Issue by excript** [pyscripter/pyscripter#1161]
I've been studying the PyScripter code and, according to my tests, the problem in using virtual environments is basically in the settings of the file "venv\Lib\site-packages\delphivcl\moduledefs.json".

For example, if "delphivcl" is installed in the Python installation, we will have the following paths configured in the "moduledefs.json" file:
{
  "python_home": "C:\\Users\\claud\\AppData\\Local\\Programs\\Python\\Python310",
  "python_bin": "C:\\Users\\claud\\AppData\\Local\\Programs\\Python\\Python310",
  "python_lib": "C:\\Users\\claud\\AppData\\Local\\Programs\\Python\\Python310",
  "python_ver": "3.10",
  "python_shared_lib": ""
}

Now, when we install "delphivcl" in the virtual environment, we will have the following paths:

{
  "python_home": "C:\\dev\\study\\delphi\\venv",
  "python_bin": "C:\\dev\\study\\delphi\\venv",
  "python_lib": "C:\\dev\\study\\delphi\\venv",
  "python_ver": "3.10",
  "python_shared_lib": ""
}

If the "moduledefs.json" file from the virtual environment is overwritten by the Python installation file, everything works normally.

My suggestion is that at the time of execution, you try to find out if the file "pyvenv.cfg" exists in the root of the directory, if it exists, you will be sure that you are working with a virtual environment and within this file you will find the PATH to the location where are the files that "delphivcl" needs to work!

File "pyvenv.cfg":

![image](https://user-images.githubusercontent.com/10388739/153045316-18972179-8c66-4412-9a24-9d0c48bcdfd0.png)

**Comment by pyscripter** [comment]
You have submitted this to the wrong place.  Please submit to https://github.com/Embarcadero/DelphiVCL4Python
