### ISSUE TITLE
PyScripter entering loop

### ISSUE THREAD

**Issue by excript** [pyscripter/pyscripter#1163]
Here's the list of steps needed to make the IDE crash, apparently going into a loop.

1) Open the IDE
2) Click (add focus) on bottom section (Python Interpreter)
![image](https://user-images.githubusercontent.com/10388739/153726889-e1ddec44-1098-4728-beb2-4d802df1e507.png)
3) Import the ``delphivcl import`` module
4) Write ``delphivcl`` and then add a dot (``.``).

The IDE should open Code Complete and display the list of functions/properties, however the IDE loops and needs to be dropped.

Looping IDE image.
![image](https://user-images.githubusercontent.com/10388739/153726962-814bda7a-f6d8-4528-913d-f0fa6ed5db59.png)

**Comment by pyscripter** [comment]
Confirmed.

By the way to get good completion with delphivcl in the editor you can add it to 
Tools, Options, IDE Options, Code Completion, Special packages

**Comment by pyscripter** [comment]
Thanks for your report.  Actually this is due to a bug in delphivcl.  See https://github.com/Embarcadero/DelphiVCL4Python/issues/15.   I hope they fix it soon.

**Comment by pyscripter** [comment]
The PyScripter side of this issue has been fixed in the repo.  The fix will be available with the next release.  
I have also fixed the P4D issue that caused the problem with delphivcl.   But Embarcadero need to apply the fix and recreate/release the python modules.
