### ISSUE TITLE
Documentation Translation

### ISSUE THREAD

**Issue by excript** [pyscripter/pyscripter#1164]
I'm developing a series of delphivcl video lessons with PyScripter and would like to translate the official documentation for the IDE.

It turns out that the documents are written in HTML format, which makes the translation work more laborious.

Would you be interested in converting the HTML files to Restructured Text (*.rst) ?

I would do the documentation conversion and send a Pull Request of the converted files, later, I would also submit the translated documentation.

There is interest in converting the documentation files to Restructured Text, which would also facilitate collaboration in improving the official documentation.

In the end, we would have the official documentation in Sphinx format, making it easy to share the documentation in places like Read the Docs.

**Comment by excript** [comment]
I didn't see your note and nothing appears in Transifex.

On [Transifex](https://www.transifex.com/pyscripter/pyscripter/translate/#pt_BR), it says that 100% of the translation into Portuguese (Brazil) is complete.

What would you need to convert to Portuguese (Brazil)?
![image](https://user-images.githubusercontent.com/10388739/154075655-2dd516e0-aa0e-460b-ae33-b0921f961c90.png)



I'll be converting the files and submitting a Pull Request from the official PyScripter documentation!

**Comment by pyscripter** [comment]
The translation of the installation program is not in Transifex.  It is  in https://github.com/pyscripter/pyscripter/tree/master/Install/locale.
You need to translate three small files and submit a PR.

**Comment by excript** [comment]
I'm finishing converting the documentation from HTML to RestructuredText and I'll send the Pull Request!

**Comment by Priyatham10** [comment]
@excript I have updated the help files using HTML itself. I didn't check this issue and converted all the old screenshots to new IDE ones. There's still half work needed. What are you up to?

**Comment by pyscripter** [comment]
@excript Any progress on this?

**Comment by pyscripter** [comment]
Help files converted to Markdown.  So they are now easy to translate.
Sphinx is used to generate documentation.

**Comment by groehner** [comment]
In editorshortcuts.md section Multi-carte commands the entry

Select Column Page Down | Shft+Alt+PgDown | Expand column selection a page down

appears twice:

Select Column Page Down | Shft+Alt+PgDown | Expand column selection a page down
Select Matching Text | Shft+Ctrl+W | Select all occurences of the currently selected text
Select Column Page Down | Shft+Alt+PgDown | Expand column selection a page down

**Comment by pyscripter** [comment]
@groehner  Fixed thanks!
