### ISSUE TITLE
Add comand line to python versions or manage the comands line

### ISSUE THREAD

**Issue by ManPython** [pyscripter/pyscripter#1166]
It's possible to more comfy add some parameters eg. `runserver --noreload` to python versions eg. venvs to manage this?
https://github.com/pyscripter/pyscripter/issues/700#issuecomment-1046068625
It's specially for Django. I missing something like VSC for this all.

**Comment by pyscripter** [comment]
What is wrong with Run, Command Line Parameters.. ?
You could use the same python version with different command line parameters.

**Comment by ManPython** [comment]
It's hard to manage and store after restart Pyscripter.
Eg. have project for 3 venvs with different versions and running multiple Pyscripters version on other ports to tests app or for unit test, etc. Always must type by hand these parameters and when "crash" what is not rarely.

**Comment by ManPython** [comment]
Also looking add some quick favorites shorcuts to run:
- python manage.py startapp music
- python manage.py migrate
- python manage.py makemigrations music
- python manage.py sqlmigrate music 0001
 
Or other

**Comment by pyscripter** [comment]
Have you looked at projects and run configurations?  You can create as many run configurations as you like.

**Comment by ManPython** [comment]
No. But looks I can mange this in this way, and Django can be run here, but:
- not working colapse tree
- problem to hook some shortcuts for debug or use "Debug play" from main toolbar (now contex menu by RMB)

Outside this. Can be the Traceback (most recent call last): as some.file as hyperlinks to see mouse cursor to click? Can be more comfy to manage files where are bugs.

**Comment by pyscripter** [comment]
> Can be the Traceback (most recent call last): as some.file as hyperlinks to see mouse cursor to click? Can be more comfy to manage files where are bugs.

The traceback in the interpreter window is clickable.  If you double click on a line with File info, it takes you to the corresponding file position.

You can also use the Messages Window to navigate/
