### ISSUE TITLE
PyScripter recolours the console when printing 3 consecutive characters.

### ISSUE THREAD

**Issue by Axle-Ozz-i-sofT** [pyscripter/pyscripter#1168]
This more of a quirk rather than a critical fault.
PyScripter V 4.1.1.0 x64, External Python V 3.9.6 x64

print(".....:::H")
print(">>>:::H...")
print("***:::H...")

It is just a visual quirk in the PyScripter interpreter window and does not effect the output otherwise. 
I encountered this while testing Ken Perlin's Mandelbrot ASCII art application.
Regards
Axle

**Comment by pyscripter** [comment]
Indeed, but not just any character.  Only '>>>', '...' and '***'.
For example:
print("---:::H...") will print with the correct output color.

'>>>', '...' and '***' are used by the syntax coloring of the interpreter to detect the python prompt and banner.
Hard to differentiate between the prompt and the output.

**Comment by Axle-Ozz-i-sofT** [comment]
OK, thanks. I'll make a note that that's how it is and suggest the native OS console for viewing :)
