### ISSUE TITLE
Error with PyScripter and QGIS 3.22, can't find DLL

### ISSUE THREAD

**Issue by amr66** [pyscripter/pyscripter#1169]
I installed the newest OSGeo4W/QGIS(3.22 LTR) that comes with Python 3.9. The whole software is X64 only now. When I try to import QSettings (as an example) in python.exe or in QGIS all runs fine, in Pyscripter it raises an ImportError:

````
from PyQt5.QtCore import QSettings
Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
ImportError: DLL load failed while importing QtCore: Das angegebene Modul wurde nicht gefunden.)
````

The way I call PyScripter is the same as of python.exe, (mainly setting the path and some environment variables) and that worked in former times. I tried so many things but the error persisted. Now my configuration is that one I began with, installing every thing new and use the batch files, that come with OSGeo4w:

````
@echo off
:: changed to the right pass, sets the OSGEO4W environment
call "%~dp0\bin\o4w_env.bat"
@echo off
:: this is the part for Python and PyQGIS
path %OSGEO4W_ROOT%\apps\qgis-ltr\bin;%PATH%
set QGIS_PREFIX_PATH=%OSGEO4W_ROOT:\=/%/apps/qgis-ltr
set GDAL_FILENAME_IS_UTF8=YES
rem Set VSI cache to be used as buffer, see #6448
set VSI_CACHE=TRUE
set VSI_CACHE_SIZE=1000000
set QT_PLUGIN_PATH=%OSGEO4W_ROOT%\apps\qgis-ltr\qtplugins;%OSGEO4W_ROOT%\apps\qt5\plugins
set PYTHONPATH=%OSGEO4W_ROOT%\apps\qgis-ltr\python;%PYTHONPATH%
:: Start Pyscripter, here I tried several variants
cd %~dp0\PyScripter
start "PyScripter" /B "PyScripter.exe" --PYTHON39 --PYTHONDLLPATH=%OSGEO4W_ROOT%\apps\Python39
````

I think, may be something changed in PyScripter OR something changed in the OSGeo4W-Python/Qt5 that makes it a non standard python install. (for examples in former versions you had to copy some files from the central bin\ to the "Pythonhome" dir.)

I also posted to the [Pyscripter google group](https://groups.google.com/g/pyscripter/c/bCauJqr8lpc) and asked a question in [gis.stackexchange](https://groups.google.com/g/pyscripter/c/bCauJqr8lpc) and opened a ticket on [osgeo4w-trac](https://trac.osgeo.org/osgeo4w/ticket/735)

**Comment by pyscripter** [comment]
Thanks for the info.  I need to investigate this and maybe incorporate this in PyScripter

**Comment by pyscripter** [comment]
I had a close look at the changes introduced in Python 3.8.  I did some tests and indeed it is as you described it:

```python
import ctypes
import os
import nt

def test1():
    """ Only in python >= 3.8 """
    os.add_dll_directory(os.getcwd())
    dll = ctypes.CDLL('libssh2.dll')
    print("test1", dll)

def test2():
    """ Succeeds in python 3.7 and in python >= 3.8 """
    dll = ctypes.CDLL(os.getcwd() + "\\TestDLL\\" + 'libssh2.dll')
    print("test2", dll)

def test3():
    """ Succeeds in python 3.7 but fails in python >= 3.8 """
    os.environ["PATH"] += os.pathsep + os.getcwd()  + "\\TestDLL"
    print(os.environ["PATH"])
    dll = ctypes.CDLL('libssh2.dll')
    print("test3", dll)

def test4():
    """ Winmode parameter only in python >= 3.8 """
    os.environ["PATH"] += os.pathsep + os.getcwd() + "\\TestDLL"
    print(os.environ["PATH"])
    dll = ctypes.CDLL('libssh2.dll', winmode = 0)
    print("test4", dll)
```

I think though that it is the responsibility of the libraries (in this case QGIS) to call add_dll_directory.  See https://github.com/conda/conda/issues/10897 for instance.   It appears that this change caused a lot of pain.

**Comment by pyscripter** [comment]
I will keep this issue open, unit I document your workaround in the Wiki.

**Comment by amr66** [comment]
Thank you for your work. The problem with QGIS is that for some reason python.exe must be in the QGIS bin directory. The main python package does the procedure I do with pyscripter, but others don't.

**Comment by amr66** [comment]
I found a new approach which I'm currently testing. I use sitecustomize.py  like discussed [here](https://trac.osgeo.org/osgeo4w/ticket/692) and use the code from my comment [above](#issuecomment-1310468377). I wasn't aware of this, but it executes the code each time python.exe is called. So it works, as far as I can tell, with PyScripter and other situations, like virtualenv and pip, for example.

**Comment by pyscripter** [comment]
Could you please do a write-up of your solution to this issue.   I will then add it to the Wiki.

**Comment by amr66** [comment]
Here is my solution for the current versions of QGIS:

**Comment by amr66** [comment]
Here is my solution for using the Python-Version (3.9) that is part of the QGIS installation since QGIS 3.22. For a complete integration of PyScripter you need two things: 
a) a batch file to start PyScripter with the QGIS "environment" and 
b) the automatic setting of the DLL search path, that changed in Python 3.8. 

a) Batch-File: I describe that for  the LTR-version of QGIS. It is a modified version of the existing python-qgis-ltr.bat in the folder "OSGeo4W\bin". I've made some changes to it, essentially using absolute paths to both the OSGeo4W and PyScripter installation folders. Please change the paths, if yours differ!

```text
@echo off
:: path for OSGeo4W/QGIS
set O4W=C:\OSGeo4W
:: path for PyScripter
set PYSC=C:\Program Files\PyScripter

:: changed start procedure
call "%O4W%\bin\o4w_env.bat"
@echo off
:: add python dir to path
path %OSGEO4W_ROOT%\apps\qgis-ltr\bin;%OSGEO4W_ROOT%\apps\Python39;%PATH%
set QGIS_PREFIX_PATH=%OSGEO4W_ROOT:\=/%/apps/qgis-ltr
set GDAL_FILENAME_IS_UTF8=YES
rem Set VSI cache to be used as buffer, see #6448
set VSI_CACHE=TRUE
set VSI_CACHE_SIZE=1000000
set QT_PLUGIN_PATH=%OSGEO4W_ROOT%\apps\qgis-ltr\qtplugins;%OSGEO4W_ROOT%\apps\qt5\plugins
set PYTHONPATH=%OSGEO4W_ROOT%\apps\qgis-ltr\python;%PYTHONPATH%

:: start PyScripter
start "PyScripter" /B "%PYSC%\PyScripter.exe" --PYTHON39 --pythondllpath=%OSGEO4W_ROOT%\apps\python39 %*
```
b) Start-Script for the Python-Interpreter: It uses the path variable and adds each path to the DLL-search path. Store this as "sitecustomize.py" into the folder OSGeo4W\apps\Python39

```python
#sitecustomize.py
import os
for p in os.getenv("PATH").split(";"):
    if os.path.exists(p):
        os.add_dll_directory(p)
```

Alternative: If you don't have write access to the OSGeo4W folder, you are still able to use the same code for the startup file of PyScripter, "python_init.py" in the program folder.

**Comment by pyscripter** [comment]
http://pyscripter.blogspot.com/2023/06/using-pyscripter-with-qgis.html
Also in the Wiki

**Comment by pyscripter** [comment]
In case anyone looks a this, I have updated the instructions for recent versions of QGIS.
https://pyscripter.blogspot.com/2025/02/using-qgis-update.html

It appears that the importing of DLLs is no longer an issue.

**Comment by amr66** [comment]
Yes, importing DLL's works now out of the box.
This is the bat-file python-qgis.bat or python-qgis-ltr.bat (in OSGEO4W\bin) for calling python. It has all that is needed to use QGIS libraries and so on:

````
@echo off
call "%~dp0\o4w_env.bat"
@echo off
path %OSGEO4W_ROOT%\apps\qgis-ltr\bin;%PATH%
set QGIS_PREFIX_PATH=%OSGEO4W_ROOT:\=/%/apps/qgis-ltr
set GDAL_FILENAME_IS_UTF8=YES
rem Set VSI cache to be used as buffer, see #6448
set VSI_CACHE=TRUE
set VSI_CACHE_SIZE=1000000
set QT_PLUGIN_PATH=%OSGEO4W_ROOT%\apps\qgis-ltr\qtplugins;%OSGEO4W_ROOT%\apps\qt5\plugins
set PYTHONPATH=%OSGEO4W_ROOT%\apps\qgis-ltr\python;%PYTHONPATH%
python %*
````

So, extending the PATH to include %OSGEO4W_ROOT%\apps\qgis-ltr\bin is missing in your example as well as setting QT_PLUGIN_PATH. The environment variable %OSGEO4W_ROOT% is set in o4w_env.bat and is just the same as your %QGIS_ROOT%.

**Comment by pyscripter** [comment]
@amr66 Thank you!  I have updated the blog post with the missing bits.
