### ISSUE TITLE
sys.path & debugging

### ISSUE THREAD

**Issue by da-dada** [pyscripter/pyscripter#1171]
it looks as though debugging does not use an updated `sys.path` for imports **if a break point is set** (no problem in all other cases)

**sorry** it's more complicated and something else

**Comment by pyscripter** [comment]
Could you please explain a bit more and provide an example.

**Comment by da-dada** [comment]
It hasn't got anything to with sys.path, but I can't extract the error:
in a try I do a raise and when I set a break point into the try then the raise exception is called right away although without that breakpoint it runs ok; and if I force the raise exception it comes up perfect without a breakpoint and if I take the raise out it works with a breakpoint as it should
so really, I have given up since there is no problem except with debugging

**Comment by pyscripter** [comment]
Still don't get it.  Could you please provide precise steps for reproducing the error.
