### ISSUE TITLE
os.chdir('C://pitoner')

### ISSUE THREAD

**Issue by tellts** [pyscripter/pyscripter#1173]
os.chdir('C://pitoner')
os.system('dir')

I run the python file by opening it in the program and clicking on the green triangle.
This lines in the code brings up an error window that says:
Remote Server is not connected.
Please reinitialize or disconnect the remote interpreter.

Python 3.9.5 in Windows 10

**Comment by pyscripter** [comment]
This works for me without issues:

```python
import os

def main():
    os.chdir("c:\\temp")
    os.system("dir")

if __name__ == '__main__':
    main()
```

This also works:
```python
def main():
    os.chdir("c:/temp")
    os.system("dir")
```

But, it appears that os.chdir('C://pitoner') crashes the remote interpreter.    Not sure what I can do about it.

**Comment by tellts** [comment]
Thanks
