### ISSUE TITLE
compile error: 'JvDockGlobals' not found

### ISSUE THREAD

**Issue by kameisan** [pyscripter/pyscripter#1175]
Original message:
[dcc64 致命的エラー] JvDockControlForm.pas(898): F2613 ユニット 'JvDockGlobals' が見つかりません。

in English:
[dcc64 Fatal error] JvDockControlForm.pas(898): F2613 unit 'JvDockGlobals' not found

**Comment by pyscripter** [comment]
JvDockGlobals is part of JVCL.

Please read https://github.com/pyscripter/pyscripter/blob/master/Compilation%20Instructions.txt

**Comment by kameisan** [comment]
Following 2 paths are needed in library path.
  pyscripter\Components\ThirdParty\delphi-detours-library\Source
  pyscripter\jvcl\jvcl\run

**Comment by pyscripter** [comment]
if you used the jvcl installer the second would be on your path (developer installation).
The multiinstaller adds the first.
