### ISSUE TITLE
PyScripter x64 (v4.1 and v4.2.x) doesn't install on Windows 11 / ARM64

### ISSUE THREAD

**Issue by MEissing** [pyscripter/pyscripter#1183]
* Start PyScripter-4.2.1-x64-Setup.exe
* Choose you installation language
* Results to
![image](https://user-images.githubusercontent.com/12135920/201042802-fd0ad656-ff32-43e6-a540-1a41eae6277e.png)

(32-Bit version of PyScripter works!)
(Portable version of PyScripter/x64 works!)

**Comment by pyscripter** [comment]
(32-Bit version of PyScripter works!)
(Portable version of PyScripter/x64 works!)

I never thought that they would.  So, Windows on ARM offers good compatibility with existing x86 apps?

There is constraint on the installer.   I will remove it and  send you a setup to try.

**Comment by MEissing** [comment]
> (32-Bit version of PyScripter works!) (Portable version of PyScripter/x64 works!)

> I never thought that they would. So, Windows on ARM offers good compatibility with existing x86 apps?

Absolutely! :-)

Low-level drivers don't work on Windows 11/ARM64... normal applications do work like a charm :-)

> There is constraint on the installer. I will remove it and send you a setup to try.

THX. Will test

**Comment by pyscripter** [comment]
Please try [this](https://drive.google.com/file/d/1BBjcRFbzF-TC5T6iOIGsWiEv1C8iNbh0/view?usp=sharing).

**Comment by pyscripter** [comment]
Thanks!

I will update the file on SF.

**Comment by pyscripter** [comment]
Question.  Is your python installation ARM64 or x64?
