### ISSUE TITLE
Restart automatically after a Windows shutdown

### ISSUE THREAD

**Issue by kkaskie** [pyscripter/pyscripter#1188]
Pyscripter will close itself if left open overnight. If a script isn't running the program remains idle, this appears to be when it happens. Files can be open and it still seems to be closed by the next day.

**Comment by pyscripter** [comment]
Are you sure Windows Update did not restart your system?

**Comment by kkaskie** [comment]
> 

Yes, it happens nightly for some time now. Other programs will remain open while pyscripter will be closed.

**Comment by pyscripter** [comment]
Notes to myself:
- [Article 1](https://stackoverflow.com/questions/10745151/detect-if-windows-closing-or-application-tries-to-close-from-system-menu-wm-clo)
- [Article 1](https://stackoverflow.com/questions/25536216/delphi-prevent-application-shutdown)
- [RegisterApplicationRestart](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-registerapplicationrestart?redirectedfrom=MSDN)
-

**Comment by pyscripter** [comment]
Recovery of unsaved files also implemented.
