### ISSUE TITLE
"Toggle comment" shorcut adds/removes leading "##" instead of "#"

### ISSUE THREAD

**Issue by bclarenc1** [pyscripter/pyscripter#1190]
## What steps will reproduce the problem?
1. set any shortcut for toggling comments
2. use this shortcut on any line

## What is the expected output?
The expected output is the addition of a leading "#" (single sharp) on the current line (or its removal if already present).

## What do you see instead?
The actual output is the addition (or removal) of a leading "##" (double sharp) instead.
Since "##" is not a valid start for a comment, the shortcut becomes useless. 

## Version
3.6.3.0 x64

**Comment by pyscripter** [comment]
This is a long-time python convention:

- # is used for comments
- ## is used for temporarily commenting out code.  This helps differentiate standard comments from commented out code.
