### ISSUE TITLE
Default settings

### ISSUE THREAD

**Issue by qwert76ya** [pyscripter/pyscripter#1191]
How can i reset the default settings?

**Comment by pyscripter** [comment]
Just delete PyScripter.ini.  It can be found at %APPDATA%\PyScripter, where %APPDATA% is the value of the environment variable APPDATA, typically, C:\Users\UserName\AppData\Roaming

By the way a better place to ask questions is the [support forum](https://groups.google.com/g/pyscripter)

**Comment by qwert76ya** [comment]
Thanks
