### ISSUE TITLE
Pyscripter error when I write (print) word 

### ISSUE THREAD

**Issue by Noman5523** [pyscripter/pyscripter#1192]
When I install pyscripter first time then phython language and open the pyscripter but when I write the word (print) then pyscripter has stopped working errors show 
![Uploading IMG_20230107_172409.jpg…]()
Please help me

**Comment by pyscripter** [comment]
You have not uploaded the image.  Please upload again.

- Have you got python  installed in your machine?
- Did PyScripter load the installed python?

If everything is fine you should see the following in the lower right corner of the PyScripter window.
![image](https://user-images.githubusercontent.com/1311616/211189699-9fd1f3c4-b158-43b4-a82f-b01b6866a553.png)

**Comment by pyscripter** [comment]
No feedback.
Most likely python installation issue.
