### ISSUE TITLE
Code and Debug hints stop working.

### ISSUE THREAD

**Issue by georgepruitt** [pyscripter/pyscripter#1196]
Sometimes, after many cycles of debugging / abort debugging I need to restart my computer to get the hints to show up again.  I frequently initiate debugging and then abort debugging once I have completed my code investigation.  I have tried to fix the issue by just restarting Pyscripter but this doesn't seem to work.

**Comment by pyscripter** [comment]
There may be running python subprocesses running that you want to kill as well.
![image](https://user-images.githubusercontent.com/1311616/217072650-c3a9adb0-cfd8-4674-afca-22d05775ba6e.png)

End Process Tree on the PyScripter process should do it.

**Comment by pyscripter** [comment]
I am not sure I can do much about this.
