### ISSUE TITLE
Translation and UI Issues

### ISSUE THREAD

**Issue by pyscripter** [pyscripter/pyscripter#1197]
- [x] Gutter in Editor options and Page Setup
- [x] Customize toolbars dialog not translated
- [x] IDE Shortcut dialog (Some categories not translated)
- [x] Word wrap not available when code folding enabled (fails quietly)
- [x] Word wrap wrong hint in the editor options
- [x] Editor options, Syntax colors:  Certain element names not translated.
- [x] Better hint for "Show font ligatures" in the editor options
- [x] Code Explorer contextual menu: "Find Definition/References"  not available for some types
- [x] Hints of the toolbar in the Documentation View
- [x] Parameter Replacement dialog box translation missing.
- [x] Message box Items replaced (unneeded quote character)
- [x] Scroll hint not translated

See 
- https://groups.google.com/u/1/g/pyscripter/c/bya57tBSfbQ
- https://groups.google.com/u/1/g/pyscripter/c/l__q1EuQeqw
- https://groups.google.com/u/1/g/pyscripter/c/_lEDTXKVuUY
- [To be reviewed.zip](https://github.com/pyscripter/pyscripter/files/10774355/To.be.reviewed.zip)

Thanks to Pedro Luis for finding the above.

**Comment by pyscripter** [comment]
I am sorry for the delay, but I am now addressing the above issues.

Notes:  I kept the editor the label "Gutter" for the editor left part.   This is more than the space for line numbers (includes debugging icons, bookmarks etc.).   Both VS Code and IntelliJ refer to this area as gutter.  (google "editor gutter" for instance.

**Comment by Plizze** [comment]
The word "Gutter" as with many words, can have many different meanings.
The "Gutter" between a text and the center of the book (the union of two sheets), in Spanish is "Medianil". This space-gutter remains blank.
But the "Gutter" which shows the line numbers and other signs, is not a "Medianil". I have tried to see in VS, Python, Java, how they solve this, I have not found anything clear, but an accurate translation can be "Canalón" (tube through which water falls from a roof) in English also is Gutter
