### ISSUE TITLE
crash everytime a function like min(), type(), etc... is typed in either the Python interpreter or in the code

### ISSUE THREAD

**Issue by Eridum** [pyscripter/pyscripter#1200]
Hi, I just installed the latest version: 4.2.5.0 and get systematic crashes of the application whenever I enter a function like min(), max() or type(). The crash occurs regardless of whether the typing occurs in the code or in the interpreter. it occurs precisely when typing the parenthesis.
Best regards,

Erik
![Crash2](https://user-images.githubusercontent.com/14116077/222975842-95ef9ea0-6883-4624-9236-8b845ba24e8a.PNG)
![Crash](https://user-images.githubusercontent.com/14116077/222975844-329d2c8d-db9b-46d4-8dbf-0930b6d38ddc.PNG)

**Comment by pyscripter** [comment]
Which version of Windows do you have? 
Is this related to https://groups.google.com/g/pyscripter/c/nLUWWAa1oYA

**Comment by Eridum** [comment]
Hi,
I had the problem yesterday at home on a Windows 8.1 Professional. I
reverted to Pyscripter 4.1.1 and everything ran fine.
Best regards,

Erik

**Comment by Eridum** [comment]
Hi,
the crash only occurs when typing functions max(), min(), type() (editor or
python shell) and only when I type the parenthesis, so I guess it is the
hint that causes the crash...
Best,

Erik

**Comment by pyscripter** [comment]
Could you please try the the x86 PyScripter.exe in   https://drive.google.com/file/d/1FEl0_fcpP-930phgRRPFHfgTcefJ5TmI/view?usp=share_link or the x64 PyScripter.exe in  the exe in https://drive.google.com/file/d/1vB1hQS7yojChXxNUr31mGe78C9gq25Ok/view?usp=share_link?

Install Pyscripter 4.2.5 and replace PyScripter.exe with the one in the appropriate zip file.

I think you will find that it fixes the error.

**Comment by Eridum** [comment]
Hi, I am traveling until Wednesday. I will try it then and let you know.
Best,

Erik

**Comment by Eridum** [comment]
Hi,
sorry I have not had the time to try the change you suggested before.
It does solve the problem indeed. Thanks very much for the correction.
Best,

Erik

**Comment by fansxs** [comment]
![aaaa](https://user-images.githubusercontent.com/17403815/225406483-1f8b2f4c-d0e8-43f6-a6ce-a1303f2edfb9.jpg)
![cccc](https://user-images.githubusercontent.com/17403815/225406498-cc9f14b3-9bd0-4830-9081-aa25ad326e7f.jpg)

**Comment by retsyo** [comment]
I am using PyScripter-4.2.5-x64 on windows 10 64 bits.
- I meet "Remote Server is not connected. Please reinitialize or disconnect the remote interpreter." often. Sometimes even I kill all python.exe in 'task manager' and restart PyScripter, it does not help. 
- I have a big dict, everytime if I try to do `print(d)` in `python interpreter` window, PyScripter crashes

However I have not coined a simplified code to reproduce the above 2 problems. I don't know whether it is because of pywin32+winword yet.

**Comment by pyscripter** [comment]
Please try the [preview](https://pyscripter.blogspot.com/2023/07/preview-of-upcoming-pyscripter-version.html).  The issue has now been fixed.
