### ISSUE TITLE
Dict keys shown not in original order

### ISSUE THREAD

**Issue by ololoe** [pyscripter/pyscripter#1201]
On variables tab, Dict keys shown not in original order. Dict is now ordered dict, so you can keep its order.

**Comment by pyscripter** [comment]
Here works as expected.

```python
>>> d = {}
>>> d[3] = 3
>>> d[2] = 2
>>> d[1] = 1
>>> d
{1: 1, 2: 2, 3: 3}
>>> print(d)
{3: 3, 2: 2, 1: 1}
```

The display uses the pprint module which sorts the keys.

```python
    def _pprint_dict(self, object, stream, indent, allowance, context, level):
        write = stream.write
        write('{')
        if self._indent_per_level > 1:
            write((self._indent_per_level - 1) * ' ')
        length = len(object)
        if length:
            if self._sort_dicts:
                items = sorted(object.items(), key=_safe_tuple)
            else:
                items = object.items()
            self._format_dict_items(items, stream, indent, allowance + 1,
                                    context, level)
        write('}')

    _dispatch[dict.__repr__] = _pprint_dict
```

If you do not want to pretty print output then uncheck the option Tools, Options, IDE Options, Python Interpreter, "Pretty print output"

**Comment by ololoe** [comment]
![programming pycharm dict key order](https://user-images.githubusercontent.com/5944139/230112382-6fdfd6be-346c-44ca-a42f-d8dd2d2be5d5.png)
![programming pyscripter dict key order](https://user-images.githubusercontent.com/5944139/230112388-e0b47b60-d04b-4290-898f-606d51eb08b4.png)

**Comment by pyscripter** [comment]
Why would you like to see the dict in insertion order?  In the variables Windows and in debugger hints, it is more useful to see the keys in sorted order.  

The standard python module pprint (pretty print) also shows the keys in sorted order.   I think it makes more sense.

The dict does maintain the insertion order when for example you iterate.

**Comment by ololoe** [comment]
Yes, as key order is important too. Do you keep order for ordereddict?

**Comment by pyscripter** [comment]
PyScripter does not keep order of anything.  Python does.

PyScripter displays dict and OrderedDict in the same way the standard python module pprint does (sorted keys).

**Comment by ololoe** [comment]
I like how your big brother Pycharm does it.

**Comment by pyscripter** [comment]
For me, when I inspect dictionaries, in most cases, the insertion order has no meaning.   A sorted view is more useful.
