### ISSUE TITLE
Language Server

### ISSUE THREAD

**Issue by groehner** [pyscripter/pyscripter#1202]
The Language Server works well with Python Version 3.7 till 3.10 but it doesn't work with Python 3.11
LspDebug.log remains empty.

PyScripter 4.2.5.0 x64
Python 3.11.2

**Comment by pyscripter** [comment]
In PyScripter autocompletion does work with Python 11.
Have you updated the lsp stuff?
Which version of Windows are you using?

**Comment by groehner** [comment]
I'm using Windows 10.
I did a fresh install of PyScripter 4.2.5 on another machine and there the language server works with Python 3.11.
So it has something to do with my configuration.
