### ISSUE TITLE
Missing Code Explorer with Python 3.11

### ISSUE THREAD

**Issue by Hiltronix** [pyscripter/pyscripter#1203]
Hello,

I'm using PyScripter v.4.2.5.0 x64 on Windows 10.  I just upgraded from Python 3.10 to 3.11.3, and the Code Explorer panel no longer displays anything.

If I switch back to Python 3.10 in the Run menu, Code Explorer works again.  I can then switch back to Python 3.11 in the Run menu, and Code Explorer continues to work.  But when I restart PyScripter, it's back to Code Explorer no longer functioning again.

I have reinstalled PyScripter, with no improvement.

What can I do to fix this issue?  

Thanks.

**Comment by Hiltronix** [comment]
No, code completion does not work either when using 3.11  But it does work if I toggle back to 3.10 in the Run menu.

**Comment by pyscripter** [comment]
Have you used the PyScripter installer or the zip distribution?
Could you please post here the python 11 version info you see in the interpreter window.

**Comment by Hiltronix** [comment]
I have used the zip version in the past, for earlier versions.  But this version I used the installer, and I used the installer yesterday to overwrite the install to see if it fixed the issue, which it didn't.

Here is the Python version info in the interpreter window I think you are asking for, showing me toggling between the two versions.


*** Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32. ***
*** Remote Python engine is active ***
>>> 
*** Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32. ***
*** Remote Python engine is active ***
>>> 
*** Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32. ***
*** Remote Python engine is active ***
>>>

**Comment by Hiltronix** [comment]
What can I do to save the settings and customized theme settings I'm using if I delete those folders?  All settings are in the User AppData folders?
