### ISSUE TITLE
console shortcuts

### ISSUE THREAD

**Issue by Quetzaal** [pyscripter/pyscripter#1205]
hi, 
i post here, because i got no access to google forum (the double validation make me lose my account)

i did a long message with little difficulties, under pyscripter(x86)from 3.2 to 4.2.5 and with python3.7 to 3.11(x86)

seeing that there were no way for me in x86 to get the new pyscripter 4.x.x in x86

i finaly pass all in x64... for the moment i'm in python9.13x64 and pyscripter3.6.4x64... and it works correctly
- **ever the shortcuts of the console (clearconsole do disapear, and must be re-import)**
- no difficulties to pass from x86 to x64 after have erase all the précédent version python and pyscripter (clean install)
- i will try to update to the last python and the last pyscripter in x64, cause all went wrong in x86(with win10, but maybe in due of a two distribution of python, 3.7 and a new one... (some popup error here and there)

test of pyscripter4.0(x64) with python3.9.13(x64) (same python than upper, new pyscripter)
- **ever shortcut console problem, i have to re-imort it every time i open pyscripter**
everything works well, but not on big files(well big 6000thousand lines, it's not enormous) (same files usualy used with the last versions of pyscrpter with no difficulties)
- **[remoter server is not connected error]**
- I read solution on this forum... and the "always used socked" is checked in tools/options/IDEoptions/python interpreter(or console python in french(change language for english ;) )
- i was having no difficulties with zonealarm before, but i went into the control program application to see the option of the firewall put all the entry in green and trustable, then reboot the PC, and re-opened pyscripter4.0 ... same popup

i do, for have tested it before, that this Error do exist also with the next 4.1/4.2.5, version of pyscripter on my Win10(x64)

**Comment by pyscripter** [comment]
> here were no way for me in x86 to get the new pyscripter 4.x.x in x86

PyScripter x86 still available at https://sourceforge.net/projects/pyscripter/files/PyScripter-v4.2/

>  ever the shortcuts of the console (clearconsole do disapear, and must be re-import)

I will have a look.



> * but not on big files(well big 6000thousand lines, it's not enormous) (same files usualy used with the last versions of pyscrpter with no difficulties)
> * **[remoter server is not connected error]**

Do you get the "remote server is not connected" error when you open, edit, run or debug on such big files?   Is there a reproducible case you can provide?  (i.e. attach the python script and provide the steprs to reproduce the error).

**Comment by Quetzaal** [comment]
hi, i went soon on 5.00 (to test)... and the errror seems to not appears anymore... 

thanks for your answer... caus' readding me again, my english is not so easy to undertsand... ;)
