### ISSUE TITLE
retain tabs when pasting in a string context

### ISSUE THREAD

**Issue by smichr** [pyscripter/pyscripter#1206]
cf #418, but I often want to run a transformation on some text copied from Excel which copies with tabs. But if the Tabs to Spaces setting is on in the options for editing, then even though I paste the text '''\<here, between quotes\>''' the tabs get converted. Would it be possible to retain tabs when pasting in a string context?

**Comment by pyscripter** [comment]
Tabs inside strings are still not good.
In python you should escape tabs inside strings e.g.

"\t sometext \t some other text"

See for instance https://www.w3schools.com/python/gloss_python_escape_characters.asp.
