### ISSUE TITLE
Updating pyscripter with new jedilsp.exe

### ISSUE THREAD

**Issue by groehner** [pyscripter/pyscripter#1208]
As I had problems with not working code completion in guipy, i found out, that jedilsp.exe wasn't exchanged with a new version durring an update. 
line 221 of the InnoSetup script pyscripter.iss should be flaged with ignoreversion:
Source: "..\Lib\Lsp\jls\jedilsp.exe"; DestDir: "{commonappdata}\PyScripter\Lsp\jls"; **Flags: ignoreversion**

**Comment by pyscripter** [comment]
Thanks!
