### ISSUE TITLE
ways to adjust fontsize of watches/callstack/variables/breakpoints window

### ISSUE THREAD

**Issue by retsyo** [pyscripter/pyscripter#1209]
well, although it is an old issues, I am stiil looking for a method to make "Watches" and other window have a bigger size font. And I am using officila PyScripter-4.2.5-x64 for windows.

When I set Tools ==> Options ==> Editor Options --> Display (tab) --> Editor font,
- "Python Interpreter" window changes its font.
- "call Stack", "Variables", "watches", "breakpoints" windows still use a very little size font
- sorry, I don't know what is "output" and "Messages" windows used for, so there is no text displays in them

thanks

![bigfont](https://github.com/pyscripter/pyscripter/assets/7960913/f7d46f7e-a312-4223-a02d-588b83316a3e)
![smallfont1](https://github.com/pyscripter/pyscripter/assets/7960913/3cdba792-d6ee-4060-9d43-2af4726cc9bf)
![smallfont2](https://github.com/pyscripter/pyscripter/assets/7960913/503a99b7-6830-4c13-95f4-e51e8a86254c)

**Comment by pyscripter** [comment]
Added new IDE option "User interface content font size in points"

**Comment by retsyo** [comment]
Thank you! Could you please supply a new binary build for windows 64 bits? Thanks

**Comment by pyscripter** [comment]
A full release will follow, but you can get the executable  from https://drive.google.com/file/d/17zALqpmPHAK1A6c5PEY1LC09PgSPHjSQ/view?usp=drive_link.
