### ISSUE TITLE
controls does not refresh after I resize windows by dragging  

### ISSUE THREAD

**Issue by retsyo** [pyscripter/pyscripter#1210]
I am using officila PyScripter-4.2.5-x64 for windows.

the attached image should say the problem clearly. What I have done, is only dragging to re-arrange the size of `coder editor` and `python interpreter`

![refresh](https://github.com/pyscripter/pyscripter/assets/7960913/c0ab9ec6-f20e-47a0-8eb6-524fe14b4c7e)

**Comment by pyscripter** [comment]
Which controls do not refresh?

**Comment by retsyo** [comment]
I made a record for your reference.
And it seems that this bad refresh only occurs on the secondary display, it has not happened on my screen display of laptop yet.

**Comment by retsyo** [comment]
[bad_refresh.zip](https://github.com/pyscripter/pyscripter/files/11600642/bad_refresh.zip)

**Comment by retsyo** [comment]
any improvements? 
[PyScripter.exe v4.2.7-x64](https://drive.google.com/file/d/1PYBvsjjwwGwLAMU4_MmByHnUevhgBgrH/view?usp=drive_link) still keeps this feature

**Comment by pyscripter** [comment]
Unfortunately, this is going to take a while.

**Comment by pyscripter** [comment]
@retsyo does [v4.2.9](https://drive.google.com/file/d/1_zko1XqzuE_xyl6DEDstx42LBI4bV1MV/view?usp=sharing) fix this?
This new version improves substantially multi-monitor support.  Please test and report any issues you may find.

**Comment by retsyo** [comment]
it seems that this issue has been fixed.

**Comment by retsyo** [comment]
it seems that this issue has been fixed.
