### ISSUE TITLE
strange NameError: name 'strOneUniqueUnit' is not defined

### ISSUE THREAD

**Issue by retsyo** [pyscripter/pyscripter#1211]
I am using officila PyScripter-4.2.5-x64 for windows 10 64 bits.

Firstly I have to say sorry, for I can't release the real code due to 2 reasons
1. This project is large, at least for me, there are many files, and the problematic and largest file is >7000 lines.
2. This project is not for public.

So I made a record, and I extracted the key frame images too

# timeline 00:00:23
`run to cursor` then pause at line 4059
as we can read from the bottom `Python Interpreter` window, line 4058 has been executed and outputs a result `['Hz']` without problem

# timeline 00:00:43
I copy the expression in line 4058, please note that this line has been evaluated without problem in 00:00:23

# timeline 00:00:49
I paste and try to execute what I have copied in last step

# timeline 00:00:54
as we can read that the once-corrected code can not been exectued 
```
>>> [i for i in lstUnitInCorrectedCase if i==strOneUniqueUnit]
Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
  File "<interactive input>", line 1, in <listcomp>
NameError: name 'strOneUniqueUnit' is not defined
```

# timeline 00:01:05
I copy `strOneUniqueUnit` in `Python Interpreter` windows, then try to execute it in `Python Interpreter` windows. There is no problem

# timeline 00:02:10
I double-click the variant in editor window to prove that there is no typo in variant name

**Comment by retsyo** [comment]
here is the record
https://github.com/pyscripter/pyscripter/assets/7960913/ac02b64f-74ef-4202-a001-32a7a9fdc87a

or the keyframe images:
![1stepto](https://github.com/pyscripter/pyscripter/assets/7960913/50fea433-e278-44b4-86a0-2ec12dc02614)
![2error](https://github.com/pyscripter/pyscripter/assets/7960913/d3b88221-2f05-4236-a327-f50347e090b9)
![3hasdefined](https://github.com/pyscripter/pyscripter/assets/7960913/a5a932cb-c209-404d-ad22-f32419694644)
![4notypo](https://github.com/pyscripter/pyscripter/assets/7960913/5a6a55d2-3677-471f-8775-45108131403b)

**Comment by retsyo** [comment]
why I said this is a strange problem?
1. what I have stated in the above image/record/text which can be re-produced **definetly** everytime with my real code

2. I have met another problem but **only once**, in other word I can't re-produce it. 
I get error in the `python interpreter` window
```
>>> strOneUniqueUnit
Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
NameError: name 'strOneUniqueUnit' is not defined
```
but you can find that often `strOneUniqueUnit` can be evaluated in my above image.

3. I know it is better to supply a simplified version when I raise an issue. Yes, I do really make one:
```python
lstUniqueUnit = ['Hz']

lstUnitInCorrectedCase = ['dB', 'Hz']

unit = 'HZ'

for strOneUniqueUnit in lstUniqueUnit:
    if strOneUniqueUnit.lower() == unit.lower():
        if strOneUniqueUnit != unit:
            print([i for i in lstUnitInCorrectedCase if i[0]==strOneUniqueUnit])
            pass
```
however, this short version **never** re-produce the issue I report here. So strange!

**Comment by pyscripter** [comment]
Surely in your code above it should be:

```python 
  [i for i in lstUnitInCorrectedCase if i==strOneUniqueUnit]
```
(It is correct in the screen shots)

Without a reproducible case I cannot do very much about it.   I am closing the issue, but if you come up with with a way of reproducing it please reopen it.
