### ISSUE TITLE
PyScripter-4.2.5-x64 randomly hangs when executing statements in the interpreter during debugging

### ISSUE THREAD

**Issue by retsyo** [pyscripter/pyscripter#1212]
I am using officila PyScripter-4.2.5-x64 for windows 10 64 bits.

It random hangs when I try to run some statement in `python interpreter` window in debug processing. I made a record for your reference. And you can find PyScripter hangs( because the mouse changes into [wait cursor](https://en.wikipedia.org/wiki/Windows_wait_cursor)) from 00:02:09 in the video. 

This time, the hang starts about 19:58, then I leaved PyScripter untouched, the hang has not been solved till 21:33, so I killed PyScripter in the `task manager`

But sorry I can't find a way or simplified code to re-produce the hang for 100%.

**Comment by retsyo** [comment]
here is the record

https://github.com/pyscripter/pyscripter/assets/7960913/4edacbdb-93e9-4071-bb4d-a3f1179f8787

**Comment by pyscripter** [comment]
The code you are executing while debugging, is executed inside the execution frame.  If it results in changes to that frame, that may crash the interpreter.

So, by its nature is a bit fragile and you should use it as a last resort and only for simple pieces of code.  Instead you can make use of the Variables window, Watches, and debugger hints (hover the mouse on top of variables) to inspect the value of variables.

**Comment by retsyo** [comment]
Thanks. But I think it is friendly if we can change the value of variable during debugging. Often during the debugging, I find that some lines of my previous code has flaw, so I try to modify the value in the `python interpreter` window, thus I can test whether the following codes are ok or not, without re-debugging and re-tracing to meet the special case that can trigger the flaw.    

And sorry to ask, is there any other IDE in which I can change variable(s) safely during debugging? Thanks

**Comment by pyscripter** [comment]
Changing variable values should definitely be safe.   Executing complex functions may be not.
Most IDEs allow you to change the values of the variables.

**Comment by retsyo** [comment]
but in my attached video, I just try to type in the variable name `strOneUniqueUnit` to show its value. I do not change its value or execute complex function, however pyscripter hangs.

**Comment by pyscripter** [comment]
> but in my attached video, I just try to type in the variable name `strOneUniqueUnit` (which is just a python string) to show its value. I do not change its value or execute complex function, however pyscripter hangs.

Hence, I keep the issue open.  It would help greatly to have a reproducible case.

**Comment by pyscripter** [comment]
I have tried to address the issue in [PyScripter.exe v4.2.7-x64](https://drive.google.com/file/d/1PYBvsjjwwGwLAMU4_MmByHnUevhgBgrH/view?usp=drive_link).   

Could you please test and report if it makes things better?

**Comment by retsyo** [comment]
I can't tell because the hang happens randomly. I have to use pyscripter for a long time to observe. So please keep this issue opened for a period.

**Comment by retsyo** [comment]
yes, the random hang is still alive even in [PyScripter.exe v4.2.7-x64](https://drive.google.com/file/d/1PYBvsjjwwGwLAMU4_MmByHnUevhgBgrH/view?usp=drive_link)

**Comment by pyscripter** [comment]
Another attempt in [PyScripter.exe v4.2.8-x64](https://drive.google.com/file/d/1mcDTGMb9fBZTr9gMtvJrpgq8983Yz5XH/view?usp=drive_link).   

Could you please test and report if it makes things better?

And by the way are your scripts using multiple threads?

**Comment by retsyo** [comment]
I will give it a try but as usual I have to use it for a period to catch the random hang

There is no multiprocess/thread in my code, hangs happen even for a simple pandas case in which there is only read_excel on filesnames gotten by glob. But since the hang appears randomly, I can't tell that pandas/glob lead to the issue.

**Comment by pyscripter** [comment]
@retsyo Any feedback on 4.2.8?

**Comment by retsyo** [comment]
I don't know since I did not code too much for months.

**Comment by MGBergweiler** [comment]
I also had regularly freezings (many a day) since version 4.1.1.0, when I started to use PySripter in Jan 2022, and must happily say that since I installed version 4.2.8  (now version 4.2.9), I have not gotten any freezing any more when checking the contents of variables in the interpreter window. Good work! 

Even more, there seems to be a bug in delphivcl, where the method __subclasses__() only works AFTER I activate delphivcl's class completion in the interpreter window!?

**Comment by pyscripter** [comment]
@retsyo  Any news?  As you see above we have some positive feedback.
