### ISSUE TITLE
Automatic syntax error checking does not work (PyScripter 4.2.5-x64, Windows 11, Python 3.11.4)

### ISSUE THREAD

**Issue by Lancewielder** [pyscripter/pyscripter#1213]
Behaviour: The IDE does not highlight errors in syntax automatically. 

Expected behaviour: If an error is present (e.g. missing colon), red squiggles should appear below the affected line

Attempted fixes: 

1. Reinstallation, following a complete wipe of appdata - failed to resolve issue.  

The feature works normally if interpreter is set to Python 3.8.17 or 3.10.11. It does not work if the interpreter is set to Python 3.11.4. 

**Screenshots**
Expected behaviour (Python 3.10.11):
![expbehav](https://github.com/pyscripter/pyscripter/assets/102469454/9d39f8bf-03e4-426c-806c-a79b94088646)

Unexpected behaviour (Python 3.11.4):
![unexpbehav](https://github.com/pyscripter/pyscripter/assets/102469454/cea5ce23-c040-423a-b92d-192697b51934)

**Comment by pyscripter** [comment]
Tools, Options, IDE Options, Language Server, "Check Syntax as you tyupe"

From the help file:

> Check syntaxas you type
> 
> If checked,when you edit Python files Pyscripter continuously check the active file for syntax errors, which are shown in a similar way in which word processors show spelling errors.  If you place the cursor on an error indicator you will see a hint explaining the problem. If this option is not checked ,the file is checked only when you open or save it.
