### ISSUE TITLE
run to cursor raise last application window to top

### ISSUE THREAD

**Issue by retsyo** [pyscripter/pyscripter#1215]
I am use [PyScripter.exe v4.2.8-x64](https://drive.google.com/file/d/1flQ3WO_1eBb8jF-jX0s6HahuljJ1yoBr/view?usp=sharing) you mentioned in https://github.com/pyscripter/pyscripter/issues/1212 with only one display

however, when I try to `run to cursor`, last application's window is raised to the top, for my case, it is a sharex windows. in other words, pyscripter's window is not the active one.

https://github.com/pyscripter/pyscripter/assets/7960913/08f432db-7ae2-461d-8db5-13d5157787aa

**Comment by pyscripter** [comment]
Cannot reproduce here.

**Comment by pyscripter** [comment]
@retsyo Do you still get this problem?

**Comment by retsyo** [comment]
no, currently I did not meet the issue
