### ISSUE TITLE
Unable to Resize Intepreter Window When Docked on Right (or Left)

### ISSUE THREAD

**Issue by Euler13** [pyscripter/pyscripter#1221]
By default, the interpreter window is docked at the bottom. If it is undocked and dragged to the right (or left), it completely fills the screen and it is not possible to resize it. In previous versions, we had the editor window on the left and the interpreter window on the right.

It is possible to work around this on a dual display by resizing the whole PyScripter window to go beyond the width of one screen. Then the editor window becomes visible and the interpreter window can be shrunk down. However, we have been enjoying using PyScripter in the school where I teach in and it is not possible to do this because they are use single display screens.

**Comment by Euler13** [comment]
Thank you for getting back.

I tried the preview of the next version, but it had the same issue. However, I've found another workaround. From the Default layout, dock it to the left first, then close the Code Explorer/File Explorer/etc, then it will dock to the right. Previously I'd been closing the Navigation windows as we try to create a less cluttered view for out students: editor on the left, output (interactive) window on the right.

It's not ideal, but at least this method works on a single display setup.

Hopefully a future iteration will fix this, but in the meantime we'll need to add the current version (using the work around) to the network image for all computers across the school for the next academic year.

Also, thank you very much for continuing to develop this IDE. It's such a lovely environment for our students to learn Python.

**Comment by pyscripter** [comment]
Please try this with the new version

Find pyscripter.local.ini in your %APPDATA%\pyscripter directory (%APPDATA % is the value of the environment variable) and delete it.  Then restart Pyscripter.

In other words, open a command prompt and do:

>cd %APPDATA%\PyScripter

>del PyScripter.local.ini 


Does this make a difference with the new version?

**Comment by Euler13** [comment]
Yes! That worked. When docked on the right it fills half the screen width now rather than the full width.
