### ISSUE TITLE
Unable to run 2 TPythonEngine per VCL application

### ISSUE THREAD

**Issue by dima72** [pyscripter/pyscripter#1222]
Dear Kiriakos,

please support me on the urgent issue. see subj.
Just let me know if that is possible by design, I'll be using it, if not we can always figure out a workaround.

Sincerely,
Dmitry

**Comment by pyscripter** [comment]
Please use the support forum for such questions.

You can only have one PythonEngine per application.   PythonEngine wraps the Python dl  and only one such dll can be loaded.   

You can destroy and re-create PythonEngine dynamically though.

**Comment by pyscripter** [comment]
**Please use the support forum for such questions.**
