### ISSUE TITLE
It is now 2023! What is your crypto wallet address for Donate?

### ISSUE THREAD

**Issue by DelphiMan68** [pyscripter/pyscripter#1223]
Hello Sir,
PayPal is not available in some countries! Therefore, I suggest that you put a crypto wallet address in the project description to support your valuable project. Today, cryptocurrencies are much more popular than in the past and should be used more.
Thank you very much for your hard work on this valuable project 🌺

**Comment by pyscripter** [comment]
You may also use the Github Sponsors to support the development of this project. 

I am not into crypto and it appears to be too much trouble to set it up.
