### ISSUE TITLE
PyScripter 4.2.5.0 does not allow Python 3.12.0

### ISSUE THREAD

**Issue by bru32** [pyscripter/pyscripter#1225]
PyScripter 4.2.5.0 x64
Downloaded from sourceforge.net/projects/pyscripter
PyScripter-4.2.5-x64-Setup.exe

Edition Windows 10 Home Single Language 64-bit
Version 22H2
OS build  19045.3448

Python 3.12.0 (64-bit)
Downloaded from python.org and installed to default folder
C:\Users\MyName\AppData\Local\Programs\Python\Python312
Folder contains python.exe and python3.dll

Environmental variables
python 3.12 path added.

Python 3.12 works on my system from VSCode, Sublime, ...

Previous python version 3.11.5 is in same root folder
and works fine in PyScripter!

**Comment by Maxim4711** [comment]
The same here, 64 bit version, 3.11.4 is recognized, 3.12 - can't add engine.

**Comment by pyscripter** [comment]
Use the [preview](https://pyscripter.blogspot.com/2023/07/preview-of-upcoming-pyscripter-version.html).
A new version is coming out soon.

**Comment by pyscripter** [comment]
Fixed with the 4.3.0 release.

**Comment by bru32** [comment]
Thanks, It's working.
