### ISSUE TITLE
Resizable Dialogs

### ISSUE THREAD

**Issue by peetm** [pyscripter/pyscripter#1227]
I often have to dig around in PyScripter's dialogs, especially in the IDE Options.  It would be useful to have this dialog, and others be resizable, and  to have them remember their sizes and last positions when later re-opened.

**Comment by pyscripter** [comment]
Made the IDE Options dialog sizeable.
For other windows please open a new issue.

**Comment by peetm** [comment]
Ah, not quite what I meant.  It now resizes, but 'forgets' its size once
closed. I really would like it to restore to however it was resized upon
reopening, even in a new session please.

Best wishes,

Peet

**Comment by pyscripter** [comment]
Fixed in version control.  The IDE Options dialog persists Width, Height and Splitter Position.
