### ISSUE TITLE
Remote server is not connected bug

### ISSUE THREAD

**Issue by peetm** [pyscripter/pyscripter#1268]
#The following seems to Kill PyScripter.

import urllib.request

sherlock = urllib.request.urlopen('https://www.gutenberg.org/ebooks/1661.txt.utf-8')
text = sherlock.read()
text = text.decode('utf-8-sig')
print(text)

![1](https://github.com/pyscripter/pyscripter/assets/1515877/1f9cbc72-bbe0-469d-b996-fc383a5552f8)

**Comment by pyscripter** [comment]
The following works:

```python
import urllib.request

sherlock = urllib.request.urlopen('https://www.gutenberg.org/ebooks/1661.txt.utf-8')
text = sherlock.read()
text = text.decode('utf-8-sig')
for line in text.splitlines():
    print(line)
```

**Comment by pyscripter** [comment]
Fixed in version control.  The fix will be included in the next release.  In the meantime please use the workaround above.

**Comment by peetm** [comment]
Yes, fixed. Thank you.

btw, clicking the link in the email resulted in this:

[image: image.png]
