### ISSUE TITLE
Codecompletion of functions and methods with brackets ()

### ISSUE THREAD

**Issue by groehner** [pyscripter/pyscripter#1269]
In code completion it's better, if the name of functions or methods are supplemented with a pair of brackets ()
This can be acomplished by these two changes:

1. Unit JediLspClient, method HandCodeCompletion 
new helper function
  function ToLabel(Item: TCompletionItem): string;
  begin
    case Item.Kind of
      TLspCompletionItemKind._Constructor,
      TLspCompletionItemKind.Method,
      TLspCompletionItemKind._Function:
      Result := Item._Label + '()'#10
    else
      Result := Item._Label + #10;
    end;
  end;

which is to be used in the for loop
InsertText := InsertText + toLabel(Item);

2. Unit frmEditor, Method SynCodeCompletionAfterCodeCompletion

begin
  Editor := ActiveSynEdit;
  if EndsStr('()', Value) then begin
    Editor.CaretX:= Editor.CaretX - 1;
    EndToken:= '(';
  end;
...

**Comment by pyscripter** [comment]
Now code completion in the interpreter consistent with the above.
