### ISSUE TITLE
Variable window and docking

### ISSUE THREAD

**Issue by MartinRaSt** [pyscripter/pyscripter#1271]
Hi,
I realized the variable window can't be docked next to the editor. 
The reason is that I am heavily working with R-Studio, and I would like to use a similar 
desktop so next to the code editor can be a variables viewer and possibly a window with graphic output and help.

Thank you for your excellent work on this project.

**Comment by pyscripter** [comment]
Fixed in version control.  The fix will be available with the next release coming out soon.  You will need to delete pyscripter.local.ini for the change to take effect.
