### ISSUE TITLE
Input Box Errors

### ISSUE THREAD

**Issue by sbharuchi** [pyscripter/pyscripter#1273]
In previous versions of the Python and PyScripter I didn't get interpreter errors. But with Python 3.12 and PyScripter 4.3.2.0 x64 
I'm getting errors. But when I run the same Python script in Idle I get no errors and the program runs. 

FYI: I'm beginner Python learner.

Here's the Python script:

#!/usr/bin/env python3
# This program isn't meant to do much. I just wrote it to get used to the IDE.
import locale

# set the locale for use in currency formatting
locale.setlocale(locale.LC_ALL, 'en_US')

# display a welcome message
print("Welcome to the Future Value Calculator")
print()

choice = "y"
while choice.lower() == "y":
    # get input from the user
    # monthly_investment = float(input("Enter monthly investment:\t"))
    monthly_investment = input("Enter monthly investment:\t")

print("Bye!")

Here's the error message:

![image](https://github.com/pyscripter/pyscripter/assets/115969063/4f282498-6617-42c0-9106-4f3b9d47439a)

**Comment by pyscripter** [comment]
Thanks for the report.  An update fixing this will be issued shortly.

**Comment by pyscripter** [comment]
Please try v4.3.3 coming out soon.
