### ISSUE TITLE
Exception in PyScripter 4.3.3-x86 

### ISSUE THREAD

**Issue by groehner** [pyscripter/pyscripter#1274]
If I start PyScripter 4.3.3-x86 it brings up these error messages:
![grafik](https://github.com/pyscripter/pyscripter/assets/53400267/0df19671-1412-4d81-b199-cc2eca8ddec9)
![grafik](https://github.com/pyscripter/pyscripter/assets/53400267/72f54f5d-bf0b-43f1-a62c-a039b5e7c7ae)
![grafik](https://github.com/pyscripter/pyscripter/assets/53400267/fdda6eef-61b8-474f-8fb3-6c0618305d2b)
Testet with Python 3.7 and Python 3.8

If I compile PyScripter 4.3.3-x86  get this error message:
![grafik](https://github.com/pyscripter/pyscripter/assets/53400267/ef2605ac-b161-436e-9203-8decdbd49727)

**Comment by pyscripter** [comment]
Thanks.  Only tested with Python 3.11 and 3.12.  Will be fixed.

**Comment by pyscripter** [comment]
Fixed in P4D.   Will need to make a new release.
