### ISSUE TITLE
IDE Tab Issues

### ISSUE THREAD

**Issue by Hiltronix** [pyscripter/pyscripter#1275]
Hello,

I'm using PS version 4.3.4.0 x64.  

When I have multiple file tabs open and arranged in the order I prefer, then close PS, and when I re-open PS the file tabs are no longer in the same preferred order as when I close the app.  I feel certain that this used to be the case, that file tab order used to be saved on closing the app.  Is there a option setting that is toggled off now for me that caused this to change?  Or is this broken in 4.3.4.0 ?  I usually have lots of tabs open, and now I have to arrange them again each time I open the app.

I'm a big fan of using mouse scroll-wheel tab scrolling.  I appreciate that this feature exists in PS.  However I find it reversed and UN-intuitive in PS.  In all the other apps I use mouse tab scrolling, like Firefox for example, when you pull the scroll wheel towards you, it takes you to the end of all the open tabs.  And when you push your scroll wheel away from you, it moves the tabs to the start.  This is reserved in PS, and I find it troublesome.  Is there a setting in PS where I can reverse the order of the file tab scroll direction?  If not, could you please consider this as a feature request?

Thanks,
Carey

**Comment by pyscripter** [comment]
Issue confirmed.   Will provide a fix in the next release.

**Comment by pyscripter** [comment]
Fixed in version control.  The fix will be available with the next release.

**Comment by Hiltronix** [comment]
Thank you! :)
