### ISSUE TITLE
The saved layout can't be load automatically!

### ISSUE THREAD

**Issue by XJJ76** [pyscripter/pyscripter#1276]
I created a new layout for my own： seperate the workspace into two half vertically, place the Debug Toolbar at the right side. It's convenient for me to monitor the running process.  I saved this layout and set the layout to it. But when I run PyScripter again, the latest version PyScripter 4.3.4 can't load this layout automatically. The old version 4.2.5 has no such a problem. I hope this issue can be solved.

**Comment by pyscripter** [comment]
Could you please provide a screen shot of the layout you want?

**Comment by XJJ76** [comment]
![layout_debug](https://github.com/pyscripter/pyscripter/assets/117890771/a55554aa-3391-4d34-a12c-dcd8723b0069)

**Comment by pyscripter** [comment]
![image](https://github.com/pyscripter/pyscripter/assets/1311616/0af95c5f-117a-45c7-9a5b-6262cc82678e)
Here this saved and restored without issues using v4.3.4.

Is it just the layout or other settings that are not restored as well?

**Comment by pyscripter** [comment]
Closed, since there is no feedback.
