### ISSUE TITLE
Apply selected "Color Theme" to one editor

### ISSUE THREAD

**Issue by groehner** [pyscripter/pyscripter#1277]
If you want a Color Theme for the current editor you uncheck "Apply to all editors" and use "Apply Theme".

![grafik](https://github.com/pyscripter/pyscripter/assets/53400267/ef823cf3-a580-4c78-9b2f-d17292f8f425)

In contrary to the other editor options, the selected theme is not stored in the options but in the highlighters.
Thus all editors change the color theme, not only the current one.

It would be a helpful enhancement, if in the list of Available Themes the current theme would be selected when the dialog opens.

**Comment by pyscripter** [comment]
> In contrary to the other editor options, the selected theme is not stored in the options but in the highlighters.

Indeed the theme is not specific to an editor.  All editors use the same theme.


> It would be a helpful enhancement, if in the list of Available Themes the current theme would be selected when the dialog opens.

This is not that easy.  The current theme may be originally based in one of the available themes, but may have been tweaked or radically changed.  The information about the original theme is not currently stored when you apply a theme.

If you have any suggestions on how to make the above more intuitive, I am happy to listen.   A PR is also welcome.

**Comment by pyscripter** [comment]
Can I close after merging your PR?
