### ISSUE TITLE
how to run .py file using cmd from pyscipter

### ISSUE THREAD

**Issue by qq2898** [pyscripter/pyscripter#1279]
If I run .py file with a long time task  in pyscripter by directly click 'run' button in toolbar, I can't continue use it at the same time, so can I  run .py file in pyscripter with a single cmd window? 
As now, after I written py file in pyscripter, I must open the cmd window, input 'python' and the .py path. if there is a simple method with pyscripter?

**Comment by pyscripter** [comment]
Run, External run
See also, Run, Configure External Run
