### ISSUE TITLE
Cursor lags behind text.

### ISSUE THREAD

**Issue by MT-276** [pyscripter/pyscripter#1281]
### Issue: 
As the title suggests. The cursor lags behind the text while typing.\
Only happens when the code's syntax highlight is in bold.

### Screenshots:
In the image, my actual cursor is at the end of the line 10.\
![image](https://github.com/pyscripter/pyscripter/assets/97303250/783a4438-56d9-4c93-86f1-75df27a3e96a)

### Temporary fix:
I found out that by simple un-bolding the syntax, it doesn't lag behind anymore.

### My system:
- On version 4.3.4.0 x64
- Windows 10 22H2
\
This error is totally nonpriority. Please don't stress yourself with this. I hope this project grows and I very much appreciate you.

**Comment by MT-276** [comment]
> What is the font you are using?
Lucidia Console 16

Maybe its a HW fault? My system is from 2011. The graphics drivers are severely outdated.

**Comment by pyscripter** [comment]
Can you try some other font?  eg. Consolas or Cascadia Code?   If you look at the second picture above, the length is the same for normal, bold and italic text.

**Comment by MT-276** [comment]
No, the cursor doesn't lag behind in both the fonts that you mentioned.

**Comment by pyscripter** [comment]
So please do not use Lucida Console.
