### ISSUE TITLE
PyScripter could not load a Python engine #881

### ISSUE THREAD

**Issue by limelect** [pyscripter/pyscripter#1285]
[delphiVCLSample.txt](https://github.com/pyscripter/pyscripter/files/13804084/delphiVCLSample.txt)
Same problem  However
Pyscripter 4.2.5.0X86 works and finds python Anconda3
Pyscripter 4.3.4.0X64 does NOT find python Anconda3
in the  configuration tool, it has  $[PythonExe-Short] the same as 4.2

also closing a demo source the first time fast the second time does not close (or too long)
python is not responding

The red indication closes the application  does not

I tested with tkinter and the application closed with no problem

**Comment by pyscripter** [comment]
Please do not mix issues.   One issue is related to finding Anaconda3

> Pyscripter 4.2.5.0X86 works and finds python Anconda3
> Pyscripter 4.3.4.0X64 does NOT find python Anconda3

Is your Anaconda3 32 or 64 bits.   PyScripter 64 bits will not find Anaconda 32 bits.  This is well documented.

Regarding the DelphiVcl issue, please submit a separate issue.

**Comment by limelect** [comment]
Would you be able to use both? As I am afraid to change to a new anaconda
all is working fine now.
can I put both 32 and 64 on the same window?.

**Comment by pyscripter** [comment]
As stated in https://sourceforge.net/projects/pyscripter/files/

> The 64-bit version of PyScripter (x64) works only on 64-bit Windows **and**
> with 64-bit versions of Python.  The 32-bit version (x86) of PyScripter works on both
> 32-bit and 64-bit Windows with 32-bit versions of Python.

**Comment by limelect** [comment]
Thanks for your help.
I will stick with the older version
However plz think about us users of 32bit too and window 7
Otherwise, we will not be able to use any updates.
Maybe 50% of the community?

**Comment by pyscripter** [comment]
> I will stick with the older version
> However plz think about us users of 32bit too

New versions always come in both 32 and 64 bit flavours.

**Comment by limelect** [comment]
OK so I will wait for your next update
To be use with 32bit too 
thanks

**Comment by pyscripter** [comment]
> OK so I will wait for your next update

Why wait?  The 32 bit flavour of the latest version is available at https://sourceforge.net/projects/pyscripter/files/PyScripter-v4.3/.

**Comment by limelect** [comment]
All fixed 32 OK
