### ISSUE TITLE
Some Pythone program problem of closing

### ISSUE THREAD

**Issue by limelect** [pyscripter/pyscripter#1286]
I found that some PY programs do not close properly after second run
This one cannot be run twice. with debug.
First run it closes fast second time the red light closes but the program hangs
I found out that it happens with other "normal" programs too.
Using Pyscripter 4.2.5.0X86 since I cannot update as per #1285

More information. After running other scripts running this one does the problem immidiatly
The same problem ocures with GuiPy

[delphiVCLSample.txt](https://github.com/pyscripter/pyscripter/files/13839900/delphiVCLSample.txt)

**Comment by limelect** [comment]
I do not know who is to blame but running this cod on Microsofy visual studio 2019 close the project witout a  problem

**Comment by pyscripter** [comment]
Add
f.Free()

as the last statement of main()

Then it should work as expected.

**Comment by limelect** [comment]
I just found out that Delphi IDE tools export to Python does not
put Application.Free()  So it is Embarcadero's problem

Try it
