### ISSUE TITLE
Using prerelease version of PYTHON and compile with different name -> python3[place-holder].dll

### ISSUE THREAD

**Issue by ArGutPL** [pyscripter/pyscripter#1287]
Is it python version / python environment configurable outside the PyScripter ?
I try using 3.13.0a2 and PyScripter is unable locate Python Version

![not-avaliable-python](https://github.com/pyscripter/pyscripter/assets/95249608/6d104cde-b3f8-427e-acf5-4396ecea0a37)

**Comment by pyscripter** [comment]
Python 13 is not yet supported.  Probably the next release will.
