### ISSUE TITLE
Error reading address when debugging delphivcl library.

### ISSUE THREAD

**Issue by fansxs** [pyscripter/pyscripter#1288]
When debugging using the Delphivcl library, stop in the click event of the control, then switch to the variables panel, click on the globals node, and a read address error will pop up, as shown in the figure. But debugging non delphivcl py files is normal.
![QQ图片20240118170706](https://github.com/pyscripter/pyscripter/assets/17403815/67c55007-2282-4dde-ab09-15c96e9c01f2)
![QQ图片20240118170629](https://github.com/pyscripter/pyscripter/assets/17403815/b203e261-3093-4670-be09-3adf037a23f9)

**Comment by pyscripter** [comment]
What is PythonStudio.exe?
Could you post a minimal sample script to replicate the error?

**Comment by limelect** [comment]
this is your source
it runs ok
![Uploading Screenshot - 19_01_2024 , 17_05_41.jpg…]()

**Comment by limelect** [comment]
![Uploading Screenshot - 19_01_2024 , 17_05_41.jpg…]()

**Comment by pyscripter** [comment]
This is a delphivcl issue.  See https://github.com/Embarcadero/DelphiVCL4Python/issues/84.

Hopefully this will be fixed in the next release.

**Comment by pyscripter** [comment]
In version 1.05 the culprit is Screen.Realign

Run the following script:
```python
from delphivcl import Screen
print(Screen.Realign.__doc__)
```
Output:
```
Traceback (most recent call last):
  File "<module1>", line 2, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 37: invalid start byte
```

Workaround:
```python
from delphivcl import *
del(Screen)
```
