### ISSUE TITLE
PyScripter can't connect to unregistered python 3.9.18

### ISSUE THREAD

**Issue by amr66** [pyscripter/pyscripter#1289]
If I try to start my unregistered Python 3.9.18 in PyScripter 4.3.4.0 (both 64bit) PyScripter seems to do nothing. I'm using the "Setup Python Version" dialog, but after activation nothing happens. Using "Test selected Python version" opens the Python shell correctly. Python 3.9.18 is new in my recent OSGeo4W-QGIS install.

**Comment by pyscripter** [comment]
Does [this](https://pyscripter.blogspot.com/2023/06/using-pyscripter-with-qgis.html)  help?

**Comment by amr66** [comment]
No, unfortunately not. This is the method I use anyway. The pitty is, that Pyscripter does nothing but saying that the python engineering could not be loaded. I checked the files of both python 3.9.18 installations, but I can't detect  serious differences. OSGEO4W has the microsoft redistributable DLL's in another bin folder, but they are in the path. And this has been working in the past.

**Comment by pyscripter** [comment]
I have just realized that this was your suggestion...
I will have a look.

**Comment by pyscripter** [comment]
Here is how I made it work:

1. Installed QGIS using the download from https://trac.osgeo.org/osgeo4w/
2. Command file:

```cmd
call C:\OSGeo4W\bin\o4w_env.bat
"C:\Program Files\PyScripter\PyScripter.exe" --PYTHON39 --PYTHONDLLPATH=C:\OSGeo4W\apps\python39
```

3. Copied zlib.dll from C:\OSGeo4W\bin to C:\OSGeo4W\apps\Python39 (This was the problem as I found with ProcMon)

Run the command file and it worked.   Importing PyQt5 etc. also worked.

**Comment by jef-n** [comment]
Python was updated, but built from source this time using the available dependencies in OSGeo4W (like zlib, lzma, sqlite3 and openssl).  That means that `python39.dll` is dynamically linked to `zlib.dll` now and that resides in a different directory, which is on PATH.   Copying `zlib.dll` to the same directory as `python39.dll` apparently helps.  I guess `python39.dll` ignores PATH and calling `AddDllDirectory` it's elements is required upfront - which is QGIS already does for other DLLs.
