### ISSUE TITLE
PyScripter seems to want Microsoft Edge WebView2 installed in user env

### ISSUE THREAD

**Issue by jpele-tis** [pyscripter/pyscripter#1291]
PyScripter seems to want Microsoft Edge WebView2 installed in user env

![image](https://github.com/pyscripter/pyscripter/assets/57767497/09abe6b9-3eac-49cc-8cb0-3a1eae206cbb)

But I already have it system wide
```
{
   "key":"Microsoft EdgeWebView",
   "name":"Microsoft Edge WebView2 Runtime",
   "version":"121.0.2277.112",
   "install_date":"2024-02-09 00:00:00",
   "install_location":"C:\\Program Files (x86)\\Microsoft\\EdgeWebView\\Application",
   "uninstall_string":"\"C:\\Program Files (x86)\\Microsoft\\EdgeWebView\\Application\\121.0.2277.112\\Installer\\setup.exe\" --uninstall --msedgewebview --system-level --verbose-logging",
   "publisher":"Microsoft Corporation",
   "system_component":0,
   "win64":false
  }
```

**Comment by pyscripter** [comment]
Indeed.  The installation file handles this.  For the zip distributions there is a link that helps you install it.

**Comment by jpele-tis** [comment]
![image](https://github.com/pyscripter/pyscripter/assets/57767497/921e6b2c-3652-4e64-a7af-63e91e2de699)
WebView2 Runtime is properly installed, I can launch an app requiring it.
Only difference is that PyScripter4 installer used is x86 and WebView2 installer used is x64.

**Comment by pyscripter** [comment]
You need to install WebView 32 bits (in addition to 64 bits) or use PyScripter 64 bits (recommended).
