### ISSUE TITLE
No code completion on compiled Python

### ISSUE THREAD

**Issue by jpele-tis** [pyscripter/pyscripter#1292]
No code completion on compiled Python (3.8.18)
We have similar issue on VSCode https://github.com/microsoft/vscode-python/issues/21265#issuecomment-1938674221
Are you using Jedi as Language Server ?
How can we debug the Python Language Server in PyScripter ?

**Comment by pyscripter** [comment]
> Are you using Jedi as Language Server ?

Yes,

Do you mean that there is no completion when source code is not available?

Then an interface file (*.pyi) is probably needed.

**Comment by pyscripter** [comment]
> How can we debug the Python Language Server in PyScripter ?

Tools, Options, IDE Options, Language Server, "Languge Server Debug Output"

If set, a log file is created in the same directory as PyScripter.ini.
