### ISSUE TITLE
compiling pyscripter

### ISSUE THREAD

**Issue by Dave-Novo** [pyscripter/pyscripter#1293]
Hello, I am trying to compile pyscripter in Delphi 11.3. 
I have downloaded/installed the Jedi libraries and run the multi-installer. Everything seems to have completed fine. 

When I compile PyScripter, I get an error jvDockGlobals has not been found. I see that file is located in 

C:\Users\davidn\Documents\Embarcadero\Studio\22.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-2023.11\run

however, the corresponding dcu is not present in 
C:\Users\davidn\Documents\Embarcadero\Studio\22.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-2023.11\lib\d28\win32

although other docking related dcu are there.
I restarted the JediVCL installer and noted that all the packages were selected for installation, including the docking ones.

I have no experience with JediVCL so just wondering if you knew what was going on. I can always dump the jvDockGlobals.pas file in the lib folder, but was wondering if I messed something up.

**Comment by Dave-Novo** [comment]
Also, it seems that when the multi-installer tool compiles the MustangPeak tools, the compiler define USE_TOOLBAR_TB2K is not included, as I am getting the error 

Undeclared identifier FillPopupMenu_TB2000 in the method

procedure TFileExplorerWindow.tbiItemBackPopup(Sender: TTBCustomItem;
  FromLink: Boolean);
begin
  VirtualShellHistory.FillPopupMenu_TB2000(tbiItemBack, TSpTBXItem, fpdNewestToOldest);
end;

This method is only defined if the USE_TOOLBAR_TB2K is present

**Comment by Dave-Novo** [comment]
Finally, after getting everthing compiling, running the program is failing because 
![image](https://github.com/pyscripter/pyscripter/assets/11635688/8ea6cb10-7e39-47b0-b134-92f1540bd7f0)

Looking in that folder, there is no file WebView2Loader.dll

**Comment by pyscripter** [comment]
When I install JVCL I use the developer install (choice in the installation GUI), so the run subdirectory is in the Delphi path.

As stated in https://github.com/pyscripter/pyscripter/blob/master/Compilation%20Instructions.txt

> E. In MustangPeak\VirtualShellTools\Include\Addins.inc define USE_TOOLBAR_TB2K.

Regarding WebView2, you need to install the "EdgeView2 SDK" from Getit.

**Comment by Dave-Novo** [comment]
Thank you so much for the instructions!!!!! You should add the note about EdgeviewSDK in the CompilationIbstructions. Also, in the compilation instructions, shouldnt step E,F be before you run the actual Multi-installer?

You may also make a note that if you install JediVCL from GetIT, then you need to do the developer install.

**Comment by pyscripter** [comment]
> Also, in the compilation instructions, shouldnt step E,F be before you run the actual Multi-installer?

Actually it has to been afterwards to avoid installation issues.

**Comment by pyscripter** [comment]
Compilation instructions updated.
