### ISSUE TITLE
ModuleNotFoundError: No module named 'beambending'

### ISSUE THREAD

**Issue by DBG333** [pyscripter/pyscripter#1295]
pip list
beambending 1.1.1

import os
from beambending import Beam, DistributedLoadV, PointLoadH, PointLoadV, x

I am using pyscripter version 4.3.4.0 x 64
ModuleNotFoundError: No module named 'beambending'

*** Remote Interpreter Reinitialized ***
Traceback (most recent call last):
File "H:\n.py", line 2, in
from beambending import Beam, DistributedLoadV, PointLoadH, PointLoadV, x
ModuleNotFoundError: No module named 'beambending'

Please Help me

**Comment by pyscripter** [comment]
Maybe PyScripter is using a different version of python from the one you installed beambending.
Try from the PyScripter menu Tools, Tools, Install Packages with pip

**Comment by pyscripter** [comment]
I am closing since there is no feedback or update.
