### ISSUE TITLE
Interpreter does not show print() befor input()

### ISSUE THREAD

**Issue by Axle-Ozz-i-sofT** [pyscripter/pyscripter#1296]
Hi team.
Not sure if this is the official branch for PyScripter or, what used to be PyScripter (adopted by Embarcadero) ?
So many different forks and version numbers I have no idea what to download or where to report bugs.

Using what I think is version 4.3.3.0 x64 Kiriakos Vlahos 2005-2024.
From "PyScripter-4.3.4-x64.zip" Embacadero Sourceforge and some other Github page that I thought was PyScripter.
Both have a SHA512:
1be01d9ea26e120e21d9a5cfb27be1fa45c0e49ffeeccb76778eb84d1fb9968cef0e870b0f14f34a2ab849a31e4d644b3c1b73fb1e58cc6fce155d58f90ef774

The Python interpreter window in the IDE does not show print() statements before input() has returned.
```
menu_item = 0
while menu_item != 3:
    print("--------------------")
    print("Sample text.")
    menu_item = int(input("Pick an item from the menu: 1, 2 or 3 "))
    print()
```
Output when run:
```
*** Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32. ***
>>> 
*** Remote Interpreter Reinitialized ***
```
After entering a value input() [Enter]
```
>>> 
*** Remote Interpreter Reinitialized ***
--------------------
Sample text.
Pick an item from the menu: 1, 2 or 3 1

--------------------
Sample text.
```

This only happens for the first print() statements. On the second loop it works as expected.
In early versions of PyScripter the print() are displayed before input().
In the console (Run External) the print() are displayed before input()

Windows 10 x64
Python 3.9.6 x64

Regards
Axle

**Comment by pyscripter** [comment]
Fixed in version control.

**Comment by Axle-Ozz-i-sofT** [comment]
Thank you,
Flush makes sense.
I am not familiar with Pascal compilers. How long until this will filter down to a binary release?
I am happy to continue using V4.2.5.0 for now.
Axle

**Comment by pyscripter** [comment]
It may take a while.

In the meantime you can download the [updated executable](https://drive.google.com/file/d/1yEBMGWvGXFVWRAjSqysNIREocal0ypAm/view?usp=sharing) and test it.   Just replace PyScripter.exe with the one in the zip file.

**Comment by Axle-Ozz-i-sofT** [comment]
Thank you, I'll give it a good workout ;)
