### ISSUE TITLE
Object properties have no code completion

### ISSUE THREAD

**Issue by fansxs** [pyscripter/pyscripter#1297]
For the code below, code completion works fine in Pycharm, but there is no code completion in Pyscripter, although Pyscripter can locate it in __init__.pyi. Any good suggestions? Maybe this problem is easy to solve.
![1](https://github.com/pyscripter/pyscripter/assets/17403815/635696ef-3aac-4c19-a7cc-40661f3a9a27)
![2](https://github.com/pyscripter/pyscripter/assets/17403815/8d2524d3-2837-4d1f-b762-5f8d643f0d34)

from delphivcl import *

img = Image.Picture.LoadFromFile('')

**Comment by pyscripter** [comment]
PyScripter uses [JEDI](https://jedi.readthedocs.io/) for code completion and this appears to be an issue.

For example with:
```python
class Picture:
    Bitmap: bytes

class Image:
    Picture: Picture

img = Image()
pic = img.Picture.
```
there is no code completion available for the last dot.

However if you change the above to:
```python
class Picture:
    Bitmap: bytes

class Image:
    picture: Picture

img = Image()
pic = img.picture.
```
code completion works.

So the problem appears to arise when the variable name is identical to the type name.   Unfortunately this is quite common in the delphivcl pyi file.

I will see whether I can get the above fixed.

**Comment by pyscripter** [comment]
Issue reported (https://github.com/davidhalter/jedi/issues/1988)

**Comment by pyscripter** [comment]
Fixed in version control.  The fix will be available with the next release.  

@fansxs In the meantime you can apply the fix described in  https://github.com/davidhalter/jedi/issues/1988 by changing the syntax_tree.py file in C:\ProgramData\PyScripter\Lsp\jls\jedilsp\jedi\inference.

**Comment by fansxs** [comment]
alright, thank you very much :).
