### ISSUE TITLE
Coloured Stderr

### ISSUE THREAD

**Issue by CuboidRaptor** [pyscripter/pyscripter#1299]
Have recently switched to PyScripter, and though it has tons of amazing features, I do have some minor nitpicks.

For one, stderr prints with the same colour of stdout. Could I possibly change it to red, or some other custom colour?

(To reproduce in interpreter:)
`import sys; sys.stderr.write("This is the same colour as a regular print() statement")`
![2024-05-20 13 54 24](https://github.com/pyscripter/pyscripter/assets/78231868/98b9e04d-c878-4e0f-84e8-dfdde83d8f47)

I also don't believe there is an option for this in Editor Options, though I may be mistaken.

**Comment by pyscripter** [comment]
Normally, python errors are printed to stderr and those are shown in red (Syntax errors and tracebacks).

![image](https://github.com/pyscripter/pyscripter/assets/1311616/4d2129b5-c527-4e11-81f3-92b73fda9676)


The  color highlighter does not know where the output came from, so it cannot highlight arbitrary strings printed in the interpreter by stderr.

**Comment by CuboidRaptor** [comment]
Is there a chance I could change the colour of stderr? For example, in IDLE, stderr is usually printed in red.

**Comment by pyscripter** [comment]
I am afraid not.
