### ISSUE TITLE
Home, Shift + Home Inconsistent behaviour

### ISSUE THREAD

**Issue by CuboidRaptor** [pyscripter/pyscripter#1300]
Another small nitpick, but pressing Home in the interpreter goes to the first character (not including the console prompt, i.e. `>>> `).
However, pressing Shift+Home, which you would expect would highlight everything from line start to the cursor, instead highlight everything from the console prompt to the cursor.

For example, with the code `>>> print("Hello, World!")`, pressing Home selects the area right before the `p` in `print()`, but pressing Shift+Home also selects the `>>> `, which prevents me from selecting the line using Shift+Home.

**Comment by pyscripter** [comment]
The fix will be available with the next release.
