### ISSUE TITLE
Compilation error: `SynEdit:eoShowSpecialChars` is missing

### ISSUE THREAD

**Issue by idanmiara** [pyscripter/pyscripter#1301]
Hi,
Trying to compile `pyscripter` for the first time.

In https://github.com/pyscripter/SynEdit/issues/89 you removed `eoShowSpecialChars`, and it's not compatible with `pyscripter`.
It looks like it's a work in progress, So I'm suggesting to make a `stable` or `pyscripter` branch in `SynEdit` and pulling that branch using `Multiinstaller.exe`.

It seems that https://github.com/pyscripter/SynEdit/commit/ce838386334099eed9a96d2075677975187d8137 does work with `pyscripter` master.

**Comment by pyscripter** [comment]
You need to update SynEdit to the latest version from pyscripter\SynEdit.   You can use the Multiinstaller for that.
See https://github.com/pyscripter/SynEdit/issues/89.

You also need to update PyScripter sounces to the latest.
