### ISSUE TITLE
The unit file is a unicode path and the function cannot be located.

### ISSUE THREAD

**Issue by fansxs** [pyscripter/pyscripter#1306]
Create a new unit and save it in the location: C:/模块1.py, Add a simple function like search().

-----------------------------------

def main():
    pass

def search():
    pass

if __name__ == '__main__':
    search()   # locate it

-----------------------------------

Put the cursor on the search function and press Ctrl+left mouse button, but the search function will not be positioned. But it is OK if the path is all English characters.

**Comment by pyscripter** [comment]
Confirmed. Working on a fix.

**Comment by pyscripter** [comment]
Fixed in version control. The fix will be available with the next version.

**Comment by fansxs** [comment]
So fast, awesome!
