### ISSUE TITLE
Pyariptor showing this and I can't run the command I'm new day 1

### ISSUE THREAD

**Issue by NOOR-BYTE-DOTCOM** [pyscripter/pyscripter#1311]
![1720193776727845558178639354180](https://github.com/pyscripter/pyscripter/assets/174818700/bb11ca9e-1a55-4660-8596-f1453be6760c)

**Comment by pyscripter** [comment]
**Before** using PyScripter, you must ensure that there is a version of Python 
greater or equal to 3.8 installed on your Windows machine.  If you do not have one 
installed, you can download one from http://www.python.org/.

The 64-bit version of PyScripter (x64) works only on 64-bit Windows **and**
with 64-bit versions of Python.  The 32-bit version (x86) of PyScripter works on both
32-bit and 64-bit Windows with 32-bit versions of Python.
