### ISSUE TITLE
Add option to set python venv as default from GUI

### ISSUE THREAD

**Issue by ManPython** [pyscripter/pyscripter#1313]
Right now is option to select active and most often only registered pythons, but venv can't be run as first.
The problem on portable to run /venv shortcut is still problematic

**Comment by pyscripter** [comment]
I am not sure I understand.  Once you create a Venv, it can be added and selected in the Python Versions dialog.

**Comment by ManPython** [comment]
But always first is priority not exist option to set as default/main.

**Comment by pyscripter** [comment]
Once you activate your venv in PyScripter, it will be used next time you start PyScripter.

**Comment by ManPython** [comment]
It's not true in my case
*** Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32. ***
*** Remote Python engine is active ***
>>> 
*** Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32. ***
*** Remote Python engine is active ***
>>> 
closed and run
*** Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32. ***
*** Remote Python engine is active ***
>>>

**Comment by pyscripter** [comment]
- If you want to open the last used python version (venv or not) do not use parameters on the command line such as --Python311.
- To run a venv directly you can use the --PYTHONxy and --PYTHONDLLPATH flags together
