### ISSUE TITLE
Reveal file in windoes explorer and internal dock widget

### ISSUE THREAD

**Issue by ManPython** [pyscripter/pyscripter#1314]
Want propose function: 
1 Reveal file in explorer - context menu on tab card in MDI if many scripts
2 Reveal file in explorer as internal dock widget to easy open tree where file is (it can be icon next to create new folder)
- also favorites as "Star" can be nice to easy switch between dirs as projects or projects

**Comment by pyscripter** [comment]
> 1 Reveal file in explorer - context menu on tab card in MDI if many scripts 2 Reveal file in explorer as internal dock widget to easy open tree where file is (it can be icon next to create new folder)
> 
> * also favorites as "Star" can be nice to easy switch between dirs as projects or projects

1.  Click on the tree in the toolbar of File Explorer. Then Browse, Active Script
2.  Not sure what you mean.  You can create subfolders by right clicking on a folder and selecting New.
3. Click on the tree in the toolbar of File Explorer. Then Favorites, Add to Favorites.
