### ISSUE TITLE
Brackets issue

### ISSUE THREAD

**Issue by ManPython** [pyscripter/pyscripter#1315]
I have often issue where eg. have code rom python27 and no brackets or just my mistake inn current new pytnon 311, eg.
`print u"test"`
- then I typing "(" and before u have ()
`print()u"test"`
- other case, where typing at end
`print u"test"`)
- then after t and completation is done in case should not be
`print()u"test")`

Can be solved in future anyway or turn of in case this often is problematic?

**Comment by ManPython** [comment]
Also this same with ' " etc..

**Comment by pyscripter** [comment]
You can turn if off by Tools, Options, IDE Options, Editor, "Auto-complete brackets".
