### ISSUE TITLE
Recent files list not displayed

### ISSUE THREAD

**Issue by jquaranta89** [pyscripter/pyscripter#1317]
I have noticed in recent versions of pyscripter that the recent file files list does not display when choosing Files/Recent Files. I just see a blank box. I have checked the pyscripter.ini file and there are 8 entries under the heading [MRU File List]. The Project/Recent Projects menu command does display a list of recent projects.  I am running version 5.0.0.0 x64 on windows 11. I have tried previous versions and  couldn't find one that worked properly until I tried version 4.3.3.0 x64 but the file explorer doesn't function properly on that version.

**Comment by pyscripter** [comment]
Works here well with 5.0.0.

Could you please post here the [MRU File List] section of your PyScripter.ini file?

## Suggested solution

Either delete the pyscripter.ini file or just the section [MRU File List],  It should then work from that point onwards.
Please report back if this works.

**Comment by jquaranta89** [comment]
Here is the info you requested.

[MRU File List]
1=F:\Classes\Current\Misc\Is_Prime_module1.py
2=F:\Classes\Current\Misc\sudoku\sudoku_ipynb_norvig.py
3=F:\Classes\Current\Misc\sudoku\killer_bruteforce_module1.py
4=F:\Classes\Current\Misc\sudoku\kenken_ipynb_norvig.py
5=F:\Classes\Docs\Norvig\Countdown_module1.py
6=F:\Classes\Current\Code\Python\Puzzles\word_games\strands_module5.py
7=F:\Classes\Current\Misc\sudoku\helpers_sudoku_module1.py
8=F:\Classes\Current\Misc\sudoku\display_sudoku_module1.py

**Comment by jquaranta89** [comment]
I deleted the [MRU File List] section of the ini file and it does seem to work now. Thanks!

**Comment by jquaranta89** [comment]
I have another question. When I select a file from the MRU list and load it in the editor, it is removed from the MRU list that is displayed. If all the files are loaded the list is emptied. Is that the correct operation? If so, the problem was with my understanding of how this works not in the operation. Thanks.

**Comment by pyscripter** [comment]
Yes, this is how it works.  When PyScripter exits, open files are added to the MRU list.
