### ISSUE TITLE
There is no Assitant item in my Edit context menu

### ISSUE THREAD

**Issue by iG8R** [pyscripter/pyscripter#1331]
Well, the title speaks for itself.
What I see:

<img name="image" src="https://github.com/user-attachments/assets/316cf902-b53c-4987-9a87-59f645b1cb20" width="350">

and what is shown in the manual here https://github.com/pyscripter/pyscripter/wiki/Assistant:

<img name="image" src="https://github.com/user-attachments/assets/327cf5d3-8554-42d1-9379-aa926282eb13" width="350">

PS. PyScript version:
<img name="image" src="https://github.com/user-attachments/assets/f417d24e-53a8-4da5-87bc-b1350f18ee9a" width="250">

**Comment by pyscripter** [comment]
The Assistant is available from the context menu (right-click) of the editor.
