### ISSUE TITLE
[OpenAI] Custom endpoint cuases the "Chat setup incomplete The LLM endpoint is missing or not supported" error

### ISSUE THREAD

**Issue by iG8R** [pyscripter/pyscripter#1332]
Hi.
When I try to use a custom endpoint (https://github.com/xtekky/gpt4free/) for the OpenAI chat I get the error "Chat setup incomplete: The LLM endpoint is missing or not supported".

<img name="image" src="https://github.com/user-attachments/assets/f27f3a40-d4ec-44c0-af4c-1cfe7c0742e7">

**Comment by pyscripter** [comment]
Only OpenAI, Gemini and Ollama are supported.   See the help file or the [wiki pages](https://github.com/pyscripter/pyscripter/wiki/LLM_Support) regarding the supported endpoints by the Chat and Assistant.

**Comment by iG8R** [comment]
Is there any way to allow custom endpoints to be used?
