### ISSUE TITLE
Problem foreground/background color in all windows

### ISSUE THREAD

**Issue by SergeyKotsyura** [pyscripter/pyscripter#1337]
Win7 Max, x32
PyScripter 4.3.4 - all right (ok)
PyScripter 5.0.1 - bad, problem exist: all area/windows (FileExplorer, ProjectExplorer, CodeExplorer, Variables, Wathes etc - are black color, not view information (information exist in window, but not look, as black symbols on black fields), see screenshot. Change styles - problem exist too. Editor window and Phyton interpreter - are ok, readable.

(?maybe problem linked with WebView2 runtime)

![PyScripterTrouble](https://github.com/user-attachments/assets/09c9be74-7fd5-468b-9320-522ed9e283ea)

**Comment by pyscripter** [comment]
Does the error exist with light color styles (e.g. Windows 10) or only with dark styles?

**Comment by SergeyKotsyura** [comment]
Hello!
My system Win7 x32, Windows theme Classic
The problem is independent of the Windows theme setting (change themes - problem exist).
The problem is independent of the PyScripter style setting (Menu-View-Styles, change styles - problem exist).
Frames: FileExplorer, ProjectExplorer, CodeExplorer, Call Stack, Wathes, Breakpoints, Messages - bad, black 
Frame Variables: area Name/Type/Value - bad, black. Area Namespaces - good
Frames: Output, Phyton Interprete - good, working ok!
PyScripter 4.3.4 - working right, good, ok!

**Comment by pyscripter** [comment]
Thanks.  This is helpful.

**Comment by pyscripter** [comment]
> My system Win7 x32, Windows theme Classic
> The problem is independent of the Windows theme setting (change themes - problem exist).

Have you tried with [Aero themes](https://www.technorms.com/5094/windows-7-aero)?

**Comment by SergeyKotsyura** [comment]
I've been thinking about it.
Aero is disabled. I can't turn it on. How to make it active I have not found a working recipe on the Internet. At the same time, release 4.3.4 works normally without Aero

**Comment by pyscripter** [comment]
> At the same time, release 4.3.4 works normally without Aero

I know.  The problem is that the treeview component I am using has dropped support for classic mode.

Did you try the fixes mentioned [here](https://superuser.com/questions/396580/windows-7-aero-themes-greyed-out-no-found-fix)?

**Comment by SergeyKotsyura** [comment]
Ok, this working (link up), solved!

**Comment by SergeyKotsyura** [comment]
The problem in the absence of Aero is not critical. I will work with PyScripter using Aero.
PS. On weak PCs with low RAM, it is necessary to optimize the use of notebook resources. Maybe there is a possibility to manually replace the new version of the component (tree-view) with the old version from release 4.3.4? I understand that this can lead to unpredictable effects, but why not try?

**Comment by pyscripter** [comment]
> but why not try?

It is not as simple as it sounds.  Win7 share of the Windows market is under 3%  and declining.  It is not supported by Microsoft. and many other editors.  Python has dropped support for windows 7 since version 3.9.  And since PyScripter is working with Aero themes, that should take core of most of the remaining Win7 users.

**Comment by SergeyKotsyura** [comment]
I am a novice Phyton programmer (more as a hobby for myself and as a tutor for schoolchildren when learning the basics of programming using Phyton), but I have been working with computers and various programs for a long time (since 1983). I like your program, it is very neat, pretty and cute. And at the same time, it is very balanced in terms of capabilities and resources consumed. I really like working with your program. I wish you success!
