### ISSUE TITLE
When remote debugging, an error will be reported when a remote file does not exist

### ISSUE THREAD

**Issue by wilikeit** [pyscripter/pyscripter#1344]
When remote debugging, an error will be reported when a remote file does not exist.  Clicking OK will result in the same message popping up again, making it impossible to use the IDE unless I create the corresponding file on the remote machine.  When a remote file does not exist, the corresponding tab should be closed.

![d6ed3bb1a0cbea2e43c8a772dfbe234](https://github.com/user-attachments/assets/0918e67e-5cec-462f-9f35-31622de73c6b)

**Comment by pyscripter** [comment]
How did you start debugging on a non-existent file?  Did you use a Run Configuration?

**Comment by wilikeit** [comment]
> How did you start debugging on a non-existent file? Did you use a Run Configuration?

I used to open the remote file from below, but then the remote file was deleted by me, and one day when I opened the ide, I reported an error, I suspect that the remote file label that was left in the editor before still exists, but the remote file does not exist, resulting in 
![image](https://github.com/user-attachments/assets/0d2d0121-abd5-4113-ab4d-23f76c6bfcb6)

**Comment by pyscripter** [comment]
Why did you close the issue?

I cannot reproduce it here. 

1. I open a remote file
2. Exit PyScripter
3. Delete remote file
4. Open PyScripter
5. I get the error message.  
6. Dismiss it 
7. Everything works OK.

**Comment by pyscripter** [comment]
@wilikeit Please also note https://pyscripter.blogspot.com/2024/11/ssh-engines-broken-by-november-12-2024.html

**Comment by wilikeit** [comment]
> 您为什么关闭该问题？
> 
> 我无法在这里复制它。
> 
> 1. 我打开了一个远程文件
> 2. 退出 PyScripter
> 3. 删除远程文件
> 4. 打开 PyScripter
> 5. 我收到错误消息。
> 6. 关闭它
> 7. 一切正常。

It might just be my delusion, but when I open many remote files and delete them, PyScripter pops up a lot of windows, which is normal logic, PyScripter Can automatically close these  nonexistent remote file tabs if there are too many remote file?

**Comment by wilikeit** [comment]
> @wilikeit Please also note https://pyscripter.blogspot.com/2024/11/ssh-engines-broken-by-november-12-2024.html

Thank you. I'll make a note of that.
