### ISSUE TITLE
Help popup on start

### ISSUE THREAD

**Issue by Cosmovoid7** [pyscripter/pyscripter#1349]
In version 5.0.1.0 x64, each time PyScripter starts, the help pops up in a window. 
I searched the options but probably overlooked the one to cancel this.
Is there a way to avoid this behavior? 
As a temporary fix I just deleted the help file.

**Comment by pyscripter** [comment]
Help should only pop-up the first time after you install an upgrade.  Once you exit PyScripter and start it again it should not show.
That is how it behaves here.

The current version is 5.1.2.  Could you please upgrade and check again?

**Comment by Cosmovoid7** [comment]
Cannot reproduce in version 5.1.2.0 x64.
