### ISSUE TITLE
Bug in Remote Debugging in PyScripter: "NameError: name 'u_index' is not defined"

### ISSUE THREAD

**Issue by ebalvis** [pyscripter/pyscripter#1352]
Dear PyScripter Development Team,

I would like to report an issue encountered while debugging remotely in PyScripter. During a remote debugging session, the following error message is displayed:

```
Project: PyScripter.exe raised exception class EPyNameError with message "NameError: name 'u_index' is not defined".

Remote Traceback:
Traceback (most recent call last):
  File "/tmp/rpyc.zip/rpyc/core/protocol.py", line 329, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/tmp/rpyc.zip/rpyc/core/protocol.py", line 590, in _handle_call
    return obj(*args, **dict(kwargs))
  File "<string>", line 437, in evalcode
  File "<string>", line 1, in <module>
NameError: name 'u_index' is not defined
```

Although this error appears during the debugging process, the script execution seems to continue functioning correctly.

I believe this may point to an internal issue in handling variable references or remote debugging logic.

Please let me know if you need additional details about the environment or steps to reproduce the issue. I’m happy to assist further in testing or debugging.

Thank you for your attention to this matter and for your excellent work on PyScripter.

**Comment by pyscripter** [comment]
**It would help enormously if you could provide some instructions for reproducing the error.**

Does this occur with the SSH engine?

From the traceback it appears that  the error occurs when evaluating some code using `evalcode` which includes the variable "u_index", which is not recognized.  Is this variable a part of the script you are running?

'evalcode` is an internal python function used by PyScripter for Call tips (hovering the mouse on a variable name while debugging), Watches and the Variables Window.  Normally errors in 'evalcode' are handled and error output is suppressed.

For example, if you hover the mouse over a variable which is not in the active debugger frame the above error will happen.    And as you say, this error would not affect the debugging process.  The bug here is that the error output is not suppressed as it should.   To fix this error it would help to find out which action triggered it.

**Comment by ebalvis** [comment]
I executed the following code remotely over SSH:


```
def imprimir_variable_n_veces(variable, n):
    """Prints a variable n times."""
    for _ in range(n):
        print(variable)
    return n  # Returns how many times it was printed, useful for testing.

# Function call
if __name__ == "__main__":
    # Quick test
    resultado = imprimir_variable_n_veces("Hola", 3)
    assert resultado == 3, "The number of prints does not match"
    print("Test passed successfully")
```
I set a breakpoint at the line:


`if __name__ == "__main__":`
and when I run the debugger, I encounter the following error:


```
First chance exception at $00007FFB1BD0B699. Exception class EPyNameError with message
'NameError: name 'u_index' is not defined

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/tmp/rpyc.zip/rpyc/core/protocol.py", line 329, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/rpyc.zip/rpyc/core/protocol.py", line 590, in _handle_call
    return obj(*args, **dict(kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 437, in evalcode
  File "<string>", line 1, in <module>
NameError: name 'u_index' is not defined
'.
Process PyScripter.exe (21084)
```
This error only occurs when debugging the code from Delphi, not in the standalone application. Moreover, the same error is triggered when I hover over a variable.

However, if I disable the error handling in Delphi, everything works correctly. Any insights on what could be causing this or how to resolve it would be appreciated.

**Comment by pyscripter** [comment]
Do you by any chance have a watch named "u_index"?  I cannot figure out where the name "u_index" comes from.

Do you get the same error when you use the remote engine (not ssh)?

Also are you saying that when you use the standalone PyScripter (i.e do not run it from the Delphi debugger) you  do see such an error?

**Comment by pyscripter** [comment]
This is as designed.
As I explained when you hover the mouse over a variable, PyScripter tries to evaluate it to show a debugger hint.  If the variable is not in the active debugger frame, this fails with a traceback similar to the one you showed above.  This is normal and when your are not debugging the Delphi code, the user does not see it.
