### ISSUE TITLE
Please add support for Code Folding. Enhancment

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#16]
```
Code folding is a great way to look at your source without being
overwhelmed by it. Please add folding (even if just at the function level
for now)

Thanks,
Josh

```

Original issue reported on code.google.com by `joshbl...@gmail.com` on 4 Dec 2006 at 10:07

**Comment by Philnext** [comment]
May consider https://github.com/bonecode/TBCEditor for editor library, code folding inside.

**Comment by drichey68** [comment]
It seems this has been a desire for about a DECADE ("Original issue reported on code.google.com by joshbl...@gmail.com on 4 Dec 2006 at 10:07"). I'd love to have this added; the lack of folding is a consistent deficit that leads me to consider other editors. Please add code folding to  PyScripter . Thanks!

**Comment by pyscripter** [comment]
Fixed in version control.  A release will follow soon.
