### ISSUE TITLE
Running Python Script input() method

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#311]
```
When you run a python script, any input(string) statements are executed with 
a dialog input box, which makes all the new lines and things messed up. I 
think it would be better to leave it normal, because I always have to use 
command prompt to test it now if I want to see what it should be displaying.

```

Original issue reported on code.google.com by `mk12...@gmail.com` on 18 Jun 2009 at 10:40

**Comment by JohanEJP** [comment]
How is this still an issue almost 10 years after first being brought up? Have I missed something are they really not going to acknowledge their fourth most discussed issue at the time of me writing this? This looks like a really nice IDE but I can't use it until an option for a more traditional input prompt is added.

**Comment by pyscripter** [comment]
Sorry for taking so long to address this.  

In the forthcoming 3.6.1 the input method in PyScripter produces the exact same output as in the standard Python interpreter in a way that allows redirection of output as well.  I think this was the main concern in this issue. You still get the dialog box for input though.  It would be hard to have the modal behaviour of a console application (you cannot move around, you cannot do other stuff) in a GUI-based interpreter without this modal dialog box.
