### ISSUE TITLE
Support debugging of multi-threaded applications

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#455]
```
Currently PyScripter does not support the debugging of multi-threaded 
applications.  The breakpoints only work in the main thread of the application. 
 This is a limitation of the Python built-in debugger used by PyScripter.  The 
debugging machinery needs to be redesigned to support the debugging of 
multi-threaded applications.  This would allow the debugging of Google App 
Engine,  Django and many other applications.
```

Original issue reported on code.google.com by `pyscripter` on 10 Dec 2010 at 11:13

**Comment by C-BERBER** [comment]
Argh!!!!! I read on another thread a way to use pyscripter to debug Django. I was so Happy!
I then installed the latest pyscripter and trashed my environment and spent hours rebuidling it. 
I finally got everything up and the debugger started only to have it repeatedly crash and here I type..

Is there any planned release or should I find a new IDE? 
I need a good debugger....
TIA

**Comment by pyscripter** [comment]
Implemented in version control
