### ISSUE TITLE
multi-caret editing in editor window 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#483]
```
What steps will reproduce the problem?
1. Try to place cursor on the few lines in the same time, to add/remove 
characters from many lines at once
2.
3.

What is the expected output? What do you see instead?
Standard multi-line editing behaviour, such as in Notepad++, Wing, Comodo etc. 

What version of the product are you using? On what operating system?
PyScripter-v2.4.1, Win7 x64

Please provide any additional information below.
It would be very nice to be able to edit many lines at once

```

Original issue reported on code.google.com by `vfxdomain` on 13 Feb 2011 at 8:01

**Comment by pyscripter** [comment]
This is a planned feature.

**Comment by dejalu22** [comment]
Any updates on the "multiple line inserts/editing" feature?

I really think of changing the IDE due to lack of this feature. It annoys me every time I would like to use it

**Comment by pyscripter** [comment]
It is planned.   Possibly in the next 6 months.
https://github.com/pyscripter/SynEdit/issues/2

**Comment by pyscripter** [comment]
[It is coming!]( https://pyscripter.blogspot.com/2024/10/teaser-multi-caret-editing-is-coming-to.html)
