### ISSUE TITLE
multi-platform support (Linux)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#487]
```
Port Pyscripter for multiplatform.
Mainly for Linux.

```

Original issue reported on code.google.com by `Phil.Pr...@gmail.com` on 2 Mar 2011 at 8:44

**Comment by kompilainenn** [comment]
> Maybe some day. But this is not going to happen any time soon I am afraid. So I am closing this for now.
> 
> Note that with the new SSH engines you can edit/run/debug scripts on remote Linux machines.

Hi. May it's time to have a Linux port now? ;-)
