### ISSUE TITLE
Started Pyscripter first time, "Python could not be properly initialized. We must quit"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#608]
```
What steps will reproduce the problem?
1. Install Pyscripter v2.4.3 on Windows XP Home Edition v. 2002
2. Started Pyscripter 3.2


What is the expected output? What do you see instead?
I expected the pyscripter IDE to start, but I received the error message 
""Python could not be properly initialized. We must quit" instead

What version of the product are you using? On what operating system?
v2.4.3 on WinXP Home Edition v. 2002

Please provide any additional information below.


```

Original issue reported on code.google.com by `sha...@gmail.com` on 28 Jan 2012 at 4:26
- Merged into: #460

**Comment by GringoA1** [comment]
I tried PyScripter-v2.6.0-Setup - it was not working. But link below is working:

http://sourceforge.net/projects/pyscripter/files/PyScripter-v2.6.0-x64-Setup.exe/download

**Comment by TechMokey** [comment]
Pyscripter not working for me. I've got Windows 10 x64, python 3.6 x64, and pyscripter 2.6 x64. Yet I still get the error "python could not be property initialized". Help please.

**Comment by av-user** [comment]
similar problem.

Windows 7 x64
python-3.7.0a4-amd64.exe
PyScripter-v3.2.0-x64.zip

on start:
"The Python engine is not properly initialized"
+
Access violation at address 0...0983D5D in module 'PyScripter.exe'. Write of addresss 0000000000000.
Details:
Exception class: EAccessViolation
Exception message: Access violation at address 0000000000983D5D in module 'PyScripter.exe'. Write of address 0000000000000000.
Exception address: 0000000000983D5D
------------------------------------------------------------------------------
PyScripter version : 3.2.0.0 x64

**Comment by pyscripter** [comment]
Please email to pyscripter at gmail doc com the bug report.
