### ISSUE TITLE
Set default directory (CWD) to that of running script

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#638]
```
What steps will reproduce the problem?
1. Open/create any script, especially one which outputs to a file without 
specifying the full path
2. Run the script
3. In the interpreter, `import os` and `print os.getcwd()`

What is the expected output? What do you see instead?
I expected that the interpreter's CWD would have been set to that of the 
script, so that files output by that script would be in the same directory as 
that script. Instead, I see that the CWD is 'C:\\Program Files\\PyScripter'.

What version of the product are you using? On what operating system?
2.5.3.0 x86 on windows 7 pro 32-bit

```

Original issue reported on code.google.com by `pckuj...@gmail.com` on 3 Apr 2012 at 5:11

**Comment by johngjertsen** [comment]
Actually, after running a script the interpreter is not brought back to the state before running the script, but the interpreter's cwd is reset to "C:\Program Files\PyScripter"

**Comment by pyscripter** [comment]
This is what it was before running the script.  You can setup a run configuration that gives you greater control on working directory environment variables etc and use that for running/debugging scripts.

**Comment by johngjertsen** [comment]
Immediately before running the script, I typed `import os` and `os.chdir("C:/Users/Name/Documents")`, the code acted on a file in that directory, and immediately after execution of the script, the working directory was reset. Could you help me understand what is meant by setting up a run configuration?

**Comment by pyscripter** [comment]
This has no effect on the next run if you using the Reinitialize before run option.   You are changing the directory on a process that will be destroyed.
