### ISSUE TITLE
can't change the "HighLight Word" color

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#690]
```
What steps will reproduce the problem?
1. In windows' display settings -> appearance -> advance, select the item 
Window, set the foreground to Yellow R: 255 G: 255 B: 0.
2. type two lines containing the same word
3. double click on one of the word, they are unreadable (background and 
foreground are same color)

What is the expected output? What do you see instead?
IDE should give a possibility to change the "HighLight Word" color.

What version of the product are you using? On what operating system?
2.5.3.0 x86

Please provide any additional information below.
Seems the "HighLight Word" color is hard coded.
See the file uSearchHighlighter.pas -> class THighlightSearchPlugin -> method 
AfterPaint -> procedure PaintHightlight (l.59):
ACanvas.Brush.Color := clYellow;

```

Original issue reported on code.google.com by `philippe...@gmail.com` on 17 Sep 2012 at 4:43

**Comment by genuinesmile29** [comment]
It's October 2017, I'm using version 3.0.2.0 and this is still a problem. This highlight feature forces a yellow background with no options to customize it and completely disregards the text color. I am using a dark text theme that uses a light grey font on a dark blue background. When word highlighting changes the background yellow but leaves the text grey, it becomes unreadable. You need to fix this by either enforcing a dark text color when you force a yellow highlight, or allow the user to customize the highlight color. Until this is fixed, you're basically forcing people away from dark themes.

**Comment by pyscripter** [comment]
Will be fixed in the next version.

**Comment by pyscripter** [comment]
Fixed in repository.
