### ISSUE TITLE
Auto-complete with one entry

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#694]
```
i type 'M', it inserts 'MemoryError' - lasted a while til i found 'Tools' -> 
'Options' -> 'IDE Options...' -> 'Auto-complete with one entry' -> (deactivate)

that entry should be  deactivated by default. Or removed, i dont see a sense at 
all in that option - how do you want to write 'MATRIX' if only 'MemoryError' is 
in Autocomplete list?

Or is there a shortcut like [ESC], which i didnt see, that undos an 
autocomplete, and does not restart autocomplete til next space?

```

Original issue reported on code.google.com by `nilshero...@googlemail.com` on 28 Oct 2012 at 2:04

**Comment by pyscripter** [comment]
With 'Auto-complete with one entry' you can press Ctrl+Z to undo the autocompletion if it is not appropriate.

So to type Matrix you need to type:
M[crrl+z]atrix

But in many other cases it can save you a lot of typing.  See  https://pyscripter.blogspot.gr/2011/08/code-completion-improvements.html for details.

I understand that for many uses, especially new users, this can be off-putting so it is now off by defalault.
