### ISSUE TITLE
Can't run pyscripter 2.5.3 64bits on Windows 2008 R2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#696]
```
What steps will reproduce the problem?
1. Install python 2.7 64bits
2. Install pyscripter 2.5.3 64 bits
3. Start pyscripter

What is the expected output? What do you see instead?
A dialog pops up saying "The application has failed to start because its 
side-by-side configuration is incorrect. Please see the application event log 
or use the command-line sxstrace.exe for more detail"

What version of the product are you using? On what operating system?
pyscripter 2.5.3 64 bits on Windows 2008 R2

Please provide any additional information below.
The analysis result of sxstrace is attached. It seems that the manifest is for 
x86

```

Original issue reported on code.google.com by `james...@gmail.com` on 5 Nov 2012 at 6:19

Attachments:
- [sxs.txt](https://storage.googleapis.com/google-code-attachments/pyscripter/issue-696/comment-0/sxs.txt)

**Comment by pyscripter** [comment]
To use PyScripter 32 bit with python 32 bit:
-  Download and install a Python 32 bit distribution from www.python.org
-  Download and install PyScripter-v3.0.2-Setup.exe from https://sourceforge.net/projects/pyscripter/files/PyScripter-v3.0/
-  PyScriper should work with the installed python 32bit without any issues.


To use PyScripter 64 bit with python 64 bit on a Windows 64 bit machine:
-  Download and install a Python 64 bit distribution from www.python.org
-  Download and install PyScripter-v3.0.2-x64-Setup.exe from https://sourceforge.net/projects/pyscripter/files/PyScripter-v3.0/
-  PyScriper should work with the installed python 64bit without any issues.

If the error persists please open a new issue
