### ISSUE TITLE
Debugger with Django does not work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#700]
```
What steps will reproduce the problem?
Please folow the steps mentioned on FAQ page.

What is the expected output? What do you see instead?
We expect the debugger to work. It acts as if we are just running Django.

What version of the product are you using? On what operating system?
Latest Pyscripter for python 2.6. Django 1.4 on windows xp and linux Suse 11

Please provide any additional information below.


```

Original issue reported on code.google.com by `mayankii...@gmail.com` on 14 Nov 2012 at 4:25

**Comment by ManPython** [comment]
@pyscripter 
Whats is actual solution for working in pyscripter and DJango?
http://codestackcatsedoc.blogspot.com/2012/09/using-pyscripter-with-django-and.html

**Comment by pyscripter** [comment]
I haven't looked at Django for a long time.
Have you tried https://github.com/pyscripter/pyscripter/wiki/FAQ#how-can-i-debug-django-applications?
Also now PyScripter supports multi-threaded debugging so this might be helpful.

**Comment by ManPython** [comment]
Yes, I tried many things without success.

**Comment by pyscripter** [comment]
I will have a look...

**Comment by ManPython** [comment]
Also in project only working: https://github.com/pyscripter/pyscripter/issues/1166#issuecomment-1046079081
