### ISSUE TITLE
Can't use '__getattribute__' in python interpreter window

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#714]
```
What steps will reproduce the problem?
1.write a class which use __getattribute__ method in python interpreter window:

>>> class A(object):
...     def __getattribute__(self, name):
...         if name == 'good':
...             return 33

2. using this class:
>>> aa = A()
>>> a        <----- get a error window

OS: Windows XP sp3
Python version: all versions
Pyscripter version: 2.5.3.0 x86

Attachments are the error windows.

```

Original issue reported on code.google.com by `xqt...@gmail.com` on 25 Dec 2012 at 9:48

Attachments:
- [eeee1.PNG](https://storage.googleapis.com/google-code-attachments/pyscripter/issue-714/comment-0/eeee1.PNG)
- [eeeee2.PNG](https://storage.googleapis.com/google-code-attachments/pyscripter/issue-714/comment-0/eeeee2.PNG)

**Comment by pyscripter** [comment]
From the Python documentation:

> object.__getattribute__(self, name) 
> Called unconditionally to implement attribute accesses for instances of the class. If the class also defines __getattr__(), the latter will not be called unless __getattribute__() either calls it explicitly or raises an AttributeError. This method should return the (computed) attribute value or raise an AttributeError exception. In order **to avoid infinite recursion in this method, its implementation should always call the base class method with the same name to access any attributes it needs, for example, object.__getattribute__(self, name)**.
> 

You should write your class instead:

class A(object):
    def __getattribute__(self, name):
        if name == 'good':
            return 33
        else:
            return object.__getattribute__(self, name)

and that works fine.
