### ISSUE TITLE
End Slash on a Raw String produces a Syntax Error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#724]
```
What steps will reproduce the problem?
1. Define a variable as a raw string: myVar = r"C:\Temp\"


What is the expected output? What do you see instead?
The raw string is not respected, and the quote is escaped, causing an error.

What version of the product are you using? On what operating system?
PyScripter 2.5.3.0 x86 (Windows 7, Python 2.7)

Please provide any additional information below.
```

Original issue reported on code.google.com by `neal.m...@gmail.com` on 22 Feb 2013 at 8:47

**Comment by pyscripter** [comment]
From the Python manual

> When an 'r' or 'R' prefix is present, a character following a backslash is included in the string without change, and all backslashes are left in the string. For example, the string literal r"\n" consists of two characters: a backslash and a lowercase 'n'. String quotes can be escaped with a backslash, but the backslash remains in the string; for example, r"\"" is a valid string literal consisting of two characters: a backslash and a double quote; r"\" is not a valid string literal (even a raw string cannot end in an odd number of backslashes). **Specifically, a raw string cannot end in a single backslash** (since the backslash would escape the following quote character). Note also that a single backslash followed by a newline is interpreted as those two characters as part of the string, not as a line continuation.
