### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#729]
```
What steps will reproduce the problem??????????? ;p
1.downloading
2.Opening the program
3.Error

What is the expected output? What do you see instead?
I see a big red X that says we must quit.

What version of the product are you using? On what operating system?
2.5.3

Please provide any additional information below.
It happens when I try to launch the application, the helpers guide, and
Icon.

```

Original issue reported on code.google.com by `pamelama...@gmail.com` on 21 Mar 2013 at 7:52

**Comment by pyscripter** [comment]
**Before** using PyScripter, you must ensure that there is a version of Python 
greater or equal to 2.4 installed on your machine. Windows.  If you do not have one 
installed, you can download one from http://www.python.org/.

The 64-bit version of PyScripter (x64) works only on 64-bit Windows **and**
with 64-bit versions of Python.  The 32-bit version of PyScripter works on both
32-bit and 64-bit Windows with the 32-bit versions of Python.

If you follow the above guidelines it should work without a problem.
