### ISSUE TITLE
msvcrt.getch() causes pyscripter to lose control of script when run.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#730]
```
What steps will reproduce the problem?
1.import msvcrt
2.msvcrt.getch()
3.Run

What is the expected output? What do you see instead?
Interpreter console should retrieve a single key press. Does not receive it and 
seems to lose control of the spawned python process. Trying to abort debugging 
fails. Must kill pyscripter to recover.

What version of the product are you using? On what operating system?
2.5.3.0 - Windows 8

Please provide any additional information below.


```

Original issue reported on code.google.com by `ro...@rferris.org` on 27 Mar 2013 at 9:55

**Comment by LightHouse6** [comment]
I have the same issue using PyScripter 2.6.0.0 x85 on Windows 7.

Here is the code:

import msvcrt
print msvcrt.getch()

Click Run, Debug from the menu. It seems to work as the buttons to run debug etc in the debug toolbar get greyed out, and the Python interpreter window the standard message that it displays when debugging: *** Remote Interpreter Reinitialized  ***

However, keystrokes don't go to the running program but to PyScripter and clicking pause or stop execution does nothing.

**Comment by pyscripter** [comment]
The Pyscripter interpreter is not a console application and it makes no sense to use msvcrt.console I/O functions in PyScripter.
