### ISSUE TITLE
problem with the text objects with pygame and pyscripter

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#738]
```
What steps will reproduce the problem?
1.run the program from pyscripter
2.it works
3.run another time the same program : error "text with zero width"

What is the expected output? What do you see instead?
a pygame window with a text

What version of the product are you using? On what operating system?
python 3.2, pygame1.9.2a0,pyscripterv2.5.3, window 7

Please provide any additional information below.

the program works whitout problems launching it from IDLE
```

Original issue reported on code.google.com by `anne.sch...@gmail.com` on 30 May 2013 at 7:08

Attachments:
- [essaitext.py](https://storage.googleapis.com/google-code-attachments/pyscripter/issue-738/comment-0/essaitext.py)

**Comment by pyscripter** [comment]
You would need to use the remote engine and reinitialize it before each run.  In recent versions of PyScripter this is done by default.
