### ISSUE TITLE
Unable to install in Windows Vista

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#745]
```
The set up runs without any issues. When i launch pyscripter, i get the message 
"pyscripter.exe has stopped working"
```

Original issue reported on code.google.com by `lovelynd...@gmail.com` on 30 Jul 2013 at 5:22

**Comment by pyscripter** [comment]
Please use the latest version of PyScripter from https://sourceforge.net/projects/pyscripter/files and if the issue persists open a new issue.
