### ISSUE TITLE
Not possible to change text foreground/background color 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#748]
```
I have not found a way to configure text colors for file types that are not 
listed in the 'Editor Syntax Language' list in the Editor Options / Syntax 
Colors tab.

I would like plain text files, and other unknown filetypes to also display with 
a dark background and light foreground as I have configured for the Python 
files.
```

Original issue reported on code.google.com by `brezht...@gmail.com` on 15 Sep 2013 at 10:26

**Comment by pyscripter** [comment]
A new highlighter called "General" has been added that can be associated with any type of text files.  You can customize this highlighter in Editor Options like any other highlighter.  In particular the Space attribute can be used to change the editor background.  See also https://pyscripter.blogspot.gr/2017/12/adjust-darkness-to-your-taste.html for related info.
