### ISSUE TITLE
Mocha highlighting

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#749]
```
Attached is a syntax highlighting configuration based on the Mocha theme 
included with the Editra editor.
```

Original issue reported on code.google.com by `brezht...@gmail.com` on 15 Sep 2013 at 10:31

Attachments:
- [MochaHighlight.ini](https://storage.googleapis.com/google-code-attachments/pyscripter/issue-749/comment-0/MochaHighlight.ini)

**Comment by pyscripter** [comment]
Fixed.  Will be added in the next version (3.1).
