### ISSUE TITLE
Error Window when I Run Program

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#750]
```
What steps will reproduce the problem?
1. Downlaoding the program
2. Runnning the program 
3. An error popping up

What is the expected output? What do you see instead?
The expected output is for Pyscripter to open, but intead an error window 
saying "Python could not be properly initialized. We must quit" pops up.

What version of the product are you using? On what operating system?
2.34 on Windows 8

Please provide any additional information below.
When I troubleshoot it, Windows says that the problem is that it is an 
incompatible program, but it worked before and I only I reinstalled it to get 
that file thing on the side since I close it when I first got it. The only 
other conflicting things I would think of would be me downloading regular 
python from python.org before getting Pyscripter or me doing first-time set up 
for Planetside 2, which does not work, either.


```

Original issue reported on code.google.com by `H.Engst...@gmail.com` on 16 Oct 2013 at 2:59

**Comment by pyscripter** [comment]
Try with a newer version of PyScripter  In general, if you install a standard Python version from Python. org PyScripter should find it and work out of the box.  There is no need for other packages to be installed.

To setup PyScripter to work with non-standard or unregistered Python distributions see [this](https://github.com/pyscripter/pyscripter/wiki/FAQ#how-do-i-use-pyscripter-with-portable-movable-python) and [this](https://github.com/pyscripter/pyscripter/wiki/FAQ#how-do-i-use-pyscripter-with-an-unregistered-version-of-python-eg-winpython)
