### ISSUE TITLE
IPython and Kivy support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#767]
```
Can IPython and Kivy support be added to Pyscripter?


```

Original issue reported on code.google.com by `dfru...@gmail.com` on 17 Mar 2014 at 4:16

**Comment by pyscripter** [comment]
Kivy support is the same as for Tk, Wx Qt etc.  You can run debug etc.
IPython support has been added through support for Jupyter (in version control currently).
