### ISSUE TITLE
Doesn't initialize on Python 3.4.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#768]
```
What steps will reproduce the problem?
1.Pyscripter doesn't initialize with Python 3.4.0, but it works fine with 3.3.4.
2.
3.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?
2.5.3.0 x86 on XP


Please provide any additional information below.


```

Original issue reported on code.google.com by `doug.tha...@gmail.com` on 18 Mar 2014 at 4:04

**Comment by benpope82** [comment]
I use multiple python verions . 2.7   3.4  3.2  and 3.5. Also activescript py 2.7 and 3.4. Along with 32 bit portable 2.7 and 3.2. I usually can use any module available. Its just weird that I hit update on pyscripter and after install it will never initialize now.
