### ISSUE TITLE
Please support high dpi

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#769]
```
What steps will reproduce the problem?
1.Install&run Pyscripter on macbook pro retina display
2.
3.

What is the expected output? What do you see instead?
I expect that pyscripter UI displays in high dpi, like most of new apps.
But it does not support dpi scaling, so all fonts are blurry :(.

What version of the product are you using? On what operating system?
windows 7 x64 sp1, dpi set to 200%, pyscripter 2.5.3.0 x64

Please provide any additional information below.
please add following to your XP_UAC.manifest, maybe it will just work:
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0" 
xmlns:asmv3="urn:schemas-microsoft-com:asm.v3" >
  <asmv3:application>
    <asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
      <dpiAware>true</dpiAware>
    </asmv3:windowsSettings>
  </asmv3:application>
</assembly>

Also fyi:
http://msdn.microsoft.com/en-us/library/windows/desktop/dn469266%28v=vs.85%29.as
px

Best Regards!
```

Original issue reported on code.google.com by `AngelJa...@gmail.com` on 8 Apr 2014 at 10:02

**Comment by pyscripter** [comment]
For me version 3.0 works well in a very high dpi screen (250% magnification).  Please report you experience here and I will look into it again.  I use the Consolas font.

**Comment by wdscxsj** [comment]
Thanks a lot for bringing PyScripter back alive, but the display is not so good in my case:

![](https://s1.postimg.org/4wqqyn0udr/pyscripter.png)

My environment: Windows 10 64-bit Simplified Chinese Edition (with latest updates); 2560x1440 with 200% magnification.

**Comment by pyscripter** [comment]
Will do, but what is not good in the picture you have posted.

**Comment by wdscxsj** [comment]
@pyscripter Thanks for your reply and great work. On my laptop, other editors (Sublime, VSCode, or even notepad) display the same code perfectly. Please compare with this screenshot to see the difference:

![](https://s1.postimg.org/4j7shzx79b/notepad.png)

**Comment by noangel** [comment]
I originally posted this issue on Google Code project page when it was available.
I tested PyScripter again, now using 3.0.2 (but somehow it displays 3.0.1 in help->about).
I agree with @wdscxsj , PyScripter GUI in latest version getting scaled by Windows on high DPI displays, such as my Macbook Pro has. I need to set Windows 7 DPI scale to 200% or  Windows UI is too small for my eyes. In that case size of PyScripter window is correct, but fonts and icons look blurry. I using default Consolas font. Look:

![seewhatimean](https://user-images.githubusercontent.com/1762260/33871720-07e9e554-df57-11e7-9c2d-433ba491e6d9.PNG)

Windows Notepad scaled correctly, but PyScripter is blurry.

**Comment by pyscripter** [comment]
This is high on the priority list and is coming out soon.

**Comment by noangel** [comment]
@pyscripter Oh, good to know it will be fixed some day. Thank You!

**Comment by pyscripter** [comment]
Fixed in version control.
