### ISSUE TITLE
Unresponsive Program when the multiprocessing module is imported

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#777]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?
2.5.3, Windows 8 Enterprise Edition

Please provide any additional information below.
1 GB RAM
1.83 Duo core processor


```

Original issue reported on code.google.com by `tjem...@gmail.com` on 30 Jul 2014 at 8:02
- Merged into: #722

Attachments:
- [pyscripter_issue.jpg](https://storage.googleapis.com/google-code-attachments/pyscripter/issue-777/comment-0/pyscripter_issue.jpg)

**Comment by pyscripter** [comment]
It is working but multiprocessing creates external processes the output of which is not captured by PyScripter.  You can always use Run, External Run to see the output.
