### ISSUE TITLE
Unable to start Pyscripter after custom parameter edit

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#779]
```
What steps will reproduce the problem?
1.Install Enthought Canopy Express 32 bit (this might not be part of the 
problem)
2.Add the following custom parameters
PythonExe=c:\users\[username]\appdata\local\canopy32\user\python.exe
PythonDir=c:\users\[username]\appdata\local\canopy32\user
PythonVersion=asdf    (I was seeing if this variable was critical
3.Exit pyscripter
4.Try to re-start it

What is the expected output? What do you see instead?
I expected pyscripter to launch, but it does nothing.  There is no process left 
running as far as I can tell.  The GUI definitely does not launch.
I tried removing these variables in the pyscripter.ini file in my APPDATA 
folder.  That did not fix it.  I uninstalled, deleted APPDATA folder, re-booted 
and re-installed.  I am still unable to launch pyscripter.

What version of the product are you using? On what operating system?
2.5.3

Please provide any additional information below.


```

Original issue reported on code.google.com by `Jesse.D....@gmail.com` on 26 Aug 2014 at 6:36

**Comment by ipstone** [comment]
Not exactly the same, but quite similar - Without tweaking anything, pyscripter would not start with my canopy python installation. I have both 64 bit and 32 bit python installed - default to 64bit. However, neither 64bit, or 32bit pyscripter will start.

**Comment by pyscripter** [comment]
PYTHONDIR and PYTHONEXE are built in parameters and you should not modify them.   PYTHONDIR is used internally by PyScripter to communicate with the python engine.

To setup PyScripter to work with non-standard or unregistered Python distributions see``[this](https://github.com/pyscripter/pyscripter/wiki/FAQ#how-do-i-use-pyscripter-with-portable-movable-python) and [this](https://github.com/pyscripter/pyscripter/wiki/FAQ#how-do-i-use-pyscripter-with-an-unregistered-version-of-python-eg-winpython)
