### ISSUE TITLE
Please add support to a diff utility

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#796]
```
Hello,

Please add support to a diff utility.

Thanks,

JM

```

Original issue reported on code.google.com by `jcrma...@gmail.com` on 13 May 2015 at 5:28

**Comment by pyscripter** [comment]
There are are many good diff utilities and everyone has their own preferences.  You easily add your favorite to PyScripter by creating an External Tool.  See the help topics under Extending the IDE in the PyScripter help file.

**Comment by pyscripter** [comment]
Another way is to install Tortoise(GIT/SVN) or WinMerge with Shell integration and use it from the File Explorer context menu.
