### ISSUE TITLE
recently installed python 2.7.10 and Pyscripter. Pyscripter not  runs, gives error: Python could not be properly initialized. We must quit

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#801]
```
What steps will reproduce the problem?
1.running the program
2.
3.

What is the expected output? What do you see instead?
opening the command screen. Error: Python could not be properly initialized. We 
must quit

What version of the product are you using? On what operating system?
Latest version of pyscriptor, for python 2.7.10 on windows 8.1

Please provide any additional information below.


```

Original issue reported on code.google.com by `aneerban...@gmail.com` on 3 Aug 2015 at 4:13

**Comment by pyscripter** [comment]
python 2.7.14 works fine with version 3.0 and 2.6.  Please use the official release from python.org.
Also note that:

The 64-bit version of PyScripter (x64) works only on 64-bit Windows **and**
with 64-bit versions of Python.  The 32-bit version of PyScripter works on both
32-bit and 64-bit Windows with the 32-bit versions of Python.
