### ISSUE TITLE
smart tab apparently not so smart (python editor)

### ISSUE THREAD

**Issue by ifmihai** [pyscripter/pyscripter#803]
I have pyscripter 2.6.0.0 x86

I checked smart tabs checkbox in Tools : Options : Editor Options : Options.
Tab spaces: 4

and then, writing python code, i bumped into this issue.

``` python
def genwords(begin, middle=None, end=None):
    # bla bla code
    # ....
    if middle is not None and len(middle) > 0:
       #cursor positioned under letter m, which is indented 3 spaces, instead of 4

```

Normally, the cursor would have been indented 4 spaces => it would be under letter **i** (of **middle**)

Then I disabled smart tab => cursor is indented ok.

bug?
or maybe i am missing something

**Comment by pyscripter** [comment]
From the Help file.
Smart tabs:
When tabbing, the cursor will go to the next non-white space character of the previous line. 

Python files get a special treatment when it comes to indentation.  So do not use the Smart Tabs option with Python files.  It could be useful with other file types.
