### ISSUE TITLE
Remote interpreter broken

### ISSUE THREAD

**Issue by tobiasli** [pyscripter/pyscripter#804]
Whenever i try to initiate the Remote Interpreter i get an error:

**Error in creating the remote intepreter: System Error. Code: 2 The system cannot find the file specified.**

I assume it is some dll that kind be found in relation to rpyc, but I can't figure out how to fix it. It worked previously, but something with in the environment broke the interpreter.

Any tips?

**Comment by pyscripter** [comment]
This is an incomplete report.  You don mention PyScripter and python version used.  In general, if you install a standard Python version from Python. org PyScripter should find it and work out of the box.  There is no need for other packages to be installed.

To setup PyScripter to work with non-standard or unregistered Python distributions see [this](https://github.com/pyscripter/pyscripter/wiki/FAQ#how-do-i-use-pyscripter-with-portable-movable-python) and [this](https://github.com/pyscripter/pyscripter/wiki/FAQ#how-do-i-use-pyscripter-with-an-unregistered-version-of-python-eg-winpython)
