### ISSUE TITLE
Python 3.5 support

### ISSUE THREAD

**Issue by liaoya** [pyscripter/pyscripter#805]
I install Python 3.5 64 bits and pyscripter 2.6.0. I find it can't find Python 3.5

**Comment by BNNorman** [comment]
Using SysInternals procmon I could see PyScripter was looking for Python versions up to 3.4 but not beyond.

I worked around this with registry editing. Create this key (if it doesn't exist):-

HKLM\SOFTWARE\Wow6432Node\Python\PythonCore\3.4\InstallPath

Then add new string values or change existing values (if any) to point to Python3.5 instead.

(Default) REG_SZ C:\Program Files (x86)\Python 3.5\
ExecutablePath REG_SZ C:\Program Files (x86)\Python 3.5\python.exe

I then reinstalled PyScripter and copied the python35.dll to the PyScripter install folder and renamed it as python34.dll

PyScripter then fires up but it's unlikely to support 3.5 extras.

**Comment by BNNorman** [comment]
Just realised you said 64bit Python - mine was 32Bit but I guess there's a similar registry workaround.

**Comment by philnagel** [comment]
Hi BNNorman,

I realize this is pretty old, but by chance do you remember anything about these steps? I am trying to follow this (I am trying to get a Conda environment to work created by ArcGIS Pro, which does not seem to place anything in the registry). I did create the keys you mentioned, and copied and renamed the DLL file. You just copied it to C:\Program Files (x86)\PyScripter?
After doing all that, I still get the error message that Pyscripter can't find python34.dll.

Thanks!

**Comment by liaoya** [comment]
Now I use Visual Studio Code and the extension https://marketplace.visualstudio.com/items?itemName=donjayamanne.python for Python. Although it lack some feature like outline, it's fast and powerful. In additional, it support Mac and Linux also

**Comment by BNNorman** [comment]
Just back from a golfing break. Yes it’s been a long time and I haven’t used PyScripter for ages as I switched to PyCharm (www.jetbrains.com) – with PyCharm you can have several versions of Python installed and choose which version to use on a per-project basis. It runs on Linux, MacOS  and Windows. (Written in Java) It’s slower to start up  but you get all the benefits of a professional IDE for free personal use.

**Comment by pyscripter** [comment]
Fixed in 3.0
