### ISSUE TITLE
PyScripter 2.6 doesn't work with Python 2.7.11 (although it does with Python 2.7.10)

### ISSUE THREAD

**Issue by RussellJohnson** [pyscripter/pyscripter#807]
With Python 2.7.10 installed, I can successfully bring up 32-bit PyScripter 2.6.

However, if I uninstall Python 2.7.10 and instead install Python 2.7.11, PyScripter 2.6 stops working.
[No error message, but attempting to open PyScripter 2.6 doesn't do anything noticeable.]

Then, if I uninstall Python 2.7.11 and re-install Python 2.7.10, PyScripter works again.

This is the 32-bit non-portable version of PyScripter 2.6, for Windows. (I'm running Windows 7, SP1.)

Since I think Python 2.7.11 is primarily a bug-fix release, it's installed to the same location (C:\Python27) as 2.7.10, has the same .dll name (Python27.dll), etc., this puzzles me.

Thanks.
- Russell J

**Comment by zeycus** [comment]
I am having the same issue with the 64-bit version.

**Comment by cjwilliams43** [comment]
Is there any work-around?
Colin W

**Comment by zeycus** [comment]
Not that I know of...

**Comment by HenkVanAsselt** [comment]
I faced the same issue, but got it eventually to run by using commandline parameters, point to another python27.dll file then the default one. I tried a few, but this specific python27.dll worked. As a reference, it's filesize is 2,480,128 bytes, and the properties says it is File version 2.7.10150.1013.

 "C:\Program Files\PyScripter\PyScripter.exe" pyscripter --python27 --pythondllpath="C:\bin\Android\Android Studio\bin\lldb\win\bin\"

**Comment by alejo099** [comment]
I think I found the solution for windows, it had the same problem that I has with ArcGIS:

1. Click Start > Run, and type 'regedit'. Navigate to 

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Python\PythonCore\2.7


2. Right-click the 2.7 folder and select Rename. Rename the '2.7' folder to '2.7-32'. 
3. When this is completed, the path must look like this: 

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Python\PythonCore\2.7-32

Enjoy!

**Comment by cjwilliams43** [comment]
Many thanks.  I'll try it.  Presumably, for a 64
      bit machine I use '2.7-64'
      
      Colin W.
      
      
    
    On 27/02/16 04:24 PM, alejo099 wrote:
    
    
      I think I found the solution for windows, it had the same
        problem that I has with ArcGIS:
      
        Click Start > Run, and type 'regedit'. Navigate to 
      
      HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Python\PythonCore\2.7
      
        Right-click the 2.7 folder and select Rename. Rename the
          '2.7' folder to '2.7-32'. 
        When this is completed, the path must look like this: 
      
      HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Python\PythonCore\2.7-32
      Enjoy!
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by cjwilliams43** [comment]
Unfortunately, the Wow6432 folder has no Python:
      
    
    
    Do you have any suggestion?
    
    Colin W.
    
    On 27/02/16 04:24 PM, alejo099 wrote:
    
    
      I think I found the solution for windows, it had the same
        problem that I has with ArcGIS:
      
        Click Start > Run, and type 'regedit'. Navigate to 
      
      HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Python\PythonCore\2.7
      
        Right-click the 2.7 folder and select Rename. Rename the
          '2.7' folder to '2.7-32'. 
        When this is completed, the path must look like this: 
      
      HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Python\PythonCore\2.7-32
      Enjoy!
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by fleytman** [comment]
I confirm the bug on windows 10

`HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Python\PythonCore\2.7-32`
does not fix a bug

**Comment by gitmeister** [comment]
I'm using Win 7 SP1 and just adding the keys above (with the corrected paths for your installation) will work. Started up and it selects 2.7.11. Selected Remote Engine and 2.7.11 Remote is active.

[pyscripter-python2711.zip](https://github.com/pyscripter/pyscripter/files/234777/pyscripter-python2711.zip)

**Comment by ololoe** [comment]
I confirm this bug on windows xp. I don't have a registry path from file here https://github.com/pyscripter/pyscripter/issues/807#issuecomment-214369004

**Comment by ololoe** [comment]
Pyscripter 2.6 suddently started working after I updated python from 2.7.11 to 2.7.12 :)

**Comment by cjwilliams43** [comment]
Thanks,  this is good to hear.

Is it with a fresh download?

I'll try it with Python 3.5.

Colin W.

**Comment by pyscripter** [comment]
Please use Python 3.0.2

To use PyScripter 32 bit with python 32 bit:
-  Download and install a Python 32 bit distribution from www.python.org
-  Download and install PyScripter-v3.0.2-Setup.exe from https://sourceforge.net/projects/pyscripter/files/PyScripter-v3.0/
-  PyScriper should work with the installed python 32bit without any issues.


To use PyScripter 64 bit with python 64 bit on a Windows 64 bit machine:
-  Download and install a Python 64 bit distribution from www.python.org
-  Download and install PyScripter-v3.0.2-x64-Setup.exe from https://sourceforge.net/projects/pyscripter/files/PyScripter-v3.0/
-  PyScriper should work with the installed python 64bit without any issues.
