### ISSUE TITLE
32-bit PyScripter 2.6's Internal Python Engine - problem with import statements

### ISSUE THREAD

**Issue by RussellJohnson** [pyscripter/pyscripter#808]
32-bit PyScripter 2.6's Internal Python Engine seems to have a problem with import statements.
1. If I run the following test script (no_imports.py) from PyScripter (using the Internal Python Engine) as it is:
   
   It works fine.
   
   Tools->Pylint is satisfied with everything except the length of the module name.
2. If I then comment out the block of import statements, and re-run the script:
   
   It works just as it did the 1st time (except possibly with a different random choice).
   It shouldn't work the same, because each of the 5 import statements is necessary.
   
   That's why Tools->Pylint (rightly) complains:
   
   ```
   [E0602(undefined-variable), main] Undefined variable 'locale'   .\no_imports.py 19      
   ... 
   [E0602(undefined-variable), main] Undefined variable 'time'     .\no_imports.py 32  
   ```
3. If I then exit PyScripter, restart it, and re-run the script:
   
   Then I get the 1st of the expected exceptions:
   
   ```
   Message         File Name           Line    Position    
   Traceback               
       <module>    .\no_imports.py     35      
       main        .\no_imports.py     19      
   exceptions.NameError: global name 'locale' is not defined
   ```

PyScripter's Remote Python Engine doesn't seem to have this problem.
If I switch to it and repeat Steps 1 and 2 above, I get the expected exception on Step 2.  
[no_imports.py.txt](https://github.com/pyscripter/pyscripter/files/60285/no_imports.py.txt)

**Comment by pyscripter** [comment]
Please do not use the Internal Python Engine since it is deprecated and I will remove it in a future release.   See https://github.com/pyscripter/pyscripter/wiki/RemoteEngines for more info.
