### ISSUE TITLE
Installing pyscripter

### ISSUE THREAD

**Issue by mikekenn** [pyscripter/pyscripter#813]
Hey guys.

Can someone lend me some guidance on installing pyscripter from github, i keep getting a "Python could not be properly initialized. We must quit" error. 

I have a windows 10 machine, with 64 bit operating system, and links to the correct python version to download from python.org would be of great help, and links to which pyscripter to download.

thanks in advance for anyones help.

**Comment by Serg191919** [comment]
Hi. Python should be not above 3.4.4 and 32-bit. Then works.

**Comment by pyscripter** [comment]
Fixed in v3.0.  Python support up to 3.7 provided
