### ISSUE TITLE
Invalid floating point operation when running ArcPy in PyScripter?

### ISSUE THREAD

**Issue by ahmadhanb** [pyscripter/pyscripter#815]
Hi,

I would like to report a bug in PyScripter as it crashes sometimes when running a python code that uses arcpy site-package of ArcGIS software.

The details of the code can be seen at Stack Exchange website as follows:
http://gis.stackexchange.com/questions/183676/invalid-floating-point-operation-when-running-arcpy-in-pyscripter?noredirect=1#comment277467_183676

When running the python code from inside ArcGIS, or from another IDLE software e.g. Spyder, it works perfectly. But, when I run the code from PyScripter, I receive the following error:

PyScripter - Application Error. 
Exception class: EInvalidOp 
Exception message: Invalid floating point operation. 
Exception address: 00000000124BA286

**Comment by pyscripter** [comment]
You should use the remote engine and reinitialize automatically before each run.  This is done by default.

Judging from the submission date, this report is about a very old version of PyScripter.  If the error occurs in the latest version please submit a new report.
