### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by blueridiculous** [pyscripter/pyscripter#816]
Hello, I apologize in advance if my question is obvious and I should be able to figure out the answer myself. 
How do you actually install this? I downloaded the zip, but all I see are files and no executables.

**Comment by GDStaff** [comment]
https://github.com/pyscripter/pyscripter/wiki/Downloads

**Comment by blueridiculous** [comment]
Thank you!
Also, does Pyscripter work with Python 3.5?

**Comment by GDStaff** [comment]
I use 3.4, all fine.

**Comment by blueridiculous** [comment]
Alright, that's what I'll do. Thanks again! We can close this issue now.
