### ISSUE TITLE
import turtle

### ISSUE THREAD

**Issue by blueridiculous** [pyscripter/pyscripter#817]
What does this mean: "ImportError: DLL load failed: %1 is not a valid Win32 application"

This might not be the right place to ask this, but I am following http://openbookproject.net/thinkcs/python/english3e/hello_little_turtles.html and typing in "import turtle" causes this error to pop up. I also see something about a "TCL library" and a "TIX library" or something, if that helps. Typing "import turtle" in also causes a "_fix.py" page to load.

**Comment by blueridiculous** [comment]
nevermind I have found the solution elsewhere

**Comment by jockster74** [comment]
@blueridiculous And if someone else came across the same issue later, it'd be nice if you had actually shared the solution.

**Comment by blueridiculous** [comment]
Oh, there seemed to be an error with my installation. I uninstalled and reinstalled, and it worked.
