### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by ololoe** [pyscripter/pyscripter#818]
Is someone developing it at all?

**Comment by Syleze** [comment]
Te te

**Comment by pyscripter** [comment]
3.0 release is imminent.

**Comment by ololoe** [comment]
Are there releases for newer python versions?

**Comment by pyscripter** [comment]
Support up to 3.7 provided.

**Comment by pyscripter** [comment]
Available now.  Download from https://sourceforge.net/projects/pyscripter/files/PyScripter-v3.0/
