### ISSUE TITLE
"Open with pyscripter" doesn't work

### ISSUE THREAD

**Issue by ololoe** [pyscripter/pyscripter#819]
If I "open with" a file, pyscripter starts, but without that file. In addition, I cannot select pyscripter for which python version it should be opened with.

**Comment by ololoe** [comment]
up

**Comment by pyscripter** [comment]
Which version of PyScripter are you using?
Are you referring to the Windows Explorer context menu?  Here when I right click on Python file in Windows Explorer, I see "Edit with PyScripter" and works fine.

**Comment by ololoe** [comment]
Ok, now open with works. But how to choose with pyscripter for what python version it should be opened? It should be at least opened with py3 if py3 shebang is present.

**Comment by ololoe** [comment]
up

**Comment by pyscripter** [comment]
It will use the highest Python version available.  No choice currently.

**Comment by ololoe** [comment]
Then "open with pyscripter" is useless since py 2 and 3 are incompatible.

Why don't you at least make a separate executable for every python version?

**Comment by pyscripter** [comment]
In the forthcoming release 3.4, PyScripter can now easily switch between python versions without exiting the program.  There are no separate shortcuts "PyScripter for Python 2.7" etc.  So if you want to work with a Python 2.x script, switch to Python 2.x.  You then open a python 3.x file, switch to python 3.x etc.
