### ISSUE TITLE
Install Problem Remains 4-Oct.16

### ISSUE THREAD

**Issue by cjwilliams43** [pyscripter/pyscripter#820]
The failure to install fails on and AMD64 Windows 10.

It seems that David Bernado was working on the problem at one time.

PyScripter was a great tool.   Much simpler to use that some of the more modern IDE's

Colin W.

**Comment by Gettyk** [comment]
I confirm: python-3.6.0b3-amd64 doesnt work with PyScripter

**Comment by pyscripter** [comment]
Fixed in v3.0
