### ISSUE TITLE
Singlestepping corrupts variable called 'nets'

### ISSUE THREAD

**Issue by hsiljedal** [pyscripter/pyscripter#825]
By single stepping this code, the variable 'nets' gets corrupted.
It appends to it self for each print. Other statements altso corrupts this variable, but only when it is a list.

Debug and single step attached code to reproduce the bug.

[test.zip](https://github.com/pyscripter/pyscripter/files/864552/test.zip)

**Comment by pyscripter** [comment]
I cannot reproduce with PyScripter version 3.x.
