### ISSUE TITLE
the breakpoint invalid and cannot debug

### ISSUE THREAD

**Issue by qq2898** [pyscripter/pyscripter#826]
it is good to use except in  mine, Win10 X64 with 32bit Python 2.7, I installed Pyscripter 2.6 X86 but it cannot to debug, even if a breakpoint exists. for a simple example:
a=1
b=2
print a+b

whenever  I set a breakpoint or use the "run to current cursor"(F4), it just run it entilely, cannot into debug.
can anyone help me?

**Comment by pyscripter** [comment]
Please use the latest version 3.0.2 from https://sourceforge.net/projects/pyscripter/files/PyScripter-v3.0/
