### ISSUE TITLE
Suggestion: Add the option "Initially expanded" to Tools\Options\IDE Options\Project Explorer (it already exists for Code Explorer)

### ISSUE THREAD

**Issue by jcrmatos** [pyscripter/pyscripter#827]
Hello,

Please consider adding the option "Initially expanded" to Tools\Options\IDE Options\Project Explorer (it already exists for Code Explorer).
I would like to be able to have my projects open always collapsed, like the Code Explorer.

Best regards,

JM

**Comment by pyscripter** [comment]
Fixed in version control
