### ISSUE TITLE
Suggestion: Please allow $[ActiveDoc-Dir] in items on [Find in Files Options\DirectoryList] of PyScripter.ini.

### ISSUE THREAD

**Issue by jcrmatos** [pyscripter/pyscripter#828]
Hello,

Please consider allowing  $[ActiveDoc-Dir] in items on [Find in Files Options\DirectoryList] of PyScripter.ini.

Best regards,

JM

**Comment by pyscripter** [comment]
Fixed in version control.
Find in Files and ToDo folders can include parameters.
