### ISSUE TITLE
Strange behaviour in Find in Files

### ISSUE THREAD

**Issue by jcrmatos** [pyscripter/pyscripter#829]
Hello,

I found a strange behaviour in Find in Files.
If I do a Find in Files Search using "search in directories" it shows the correct results, but if I do the same search using Project files (the project files are the same files *.py and the same path), it shows the results in a different way.
I enclosed 2 print-screens for you to see the difference with the respetive print-screens of the selected search options and project files.

Best regards,

JM

![projectfiles](https://user-images.githubusercontent.com/1813375/32234197-0f11159c-be54-11e7-9ffc-9e0b9bb8cb14.png)
![projectfiles2](https://user-images.githubusercontent.com/1813375/32234199-0f39032c-be54-11e7-9dd4-679cfd2899ee.png)
![searchdirectories](https://user-images.githubusercontent.com/1813375/32234203-101587fc-be54-11e7-9145-ead37a5d1580.png)
![searchdirectoriesresults](https://user-images.githubusercontent.com/1813375/32234204-103eea98-be54-11e7-897d-d4c16cd0a9f9.png)
![searchprojectfiles](https://user-images.githubusercontent.com/1813375/32234205-105eb3b4-be54-11e7-9ee4-37b554c82067.png)
![searchprojectfilesresults](https://user-images.githubusercontent.com/1813375/32234206-107c1f26-be54-11e7-89fc-0759054323ff.png)

**Comment by pyscripter** [comment]
Much as I tried I could not reproduce the problem.  What I also do not understand is that there appear to be about 40 files in the project but the first search only searches 20 files and the second 42.  As you mentioned in a private communication, the problem went away after reconstructing the project file.  Please reopen the issue if it reappears and submit a reproducible test case.
