### ISSUE TITLE
Different templates for python 2 and 3

### ISSUE THREAD

**Issue by ololoe** [pyscripter/pyscripter#831]
Python 3 files should begin with `#!python3` sheband, python 2 should not.

**Comment by pyscripter** [comment]
The sheband is optional and only applicable to python files that can be run as stand-alone scripts.  See for instance [this stackoverflow question ](https://stackoverflow.com/questions/6908143/should-i-put-shebang-in-python-scripts-and-what-form-should-it-take)

**Comment by ololoe** [comment]
Shebang is mandatory for scripts in python 3 as freetards forgot to make separate extension for python3 (in Microsoft Windows(r)(tm), documents that should be opened with different programs should have different extension). Having different templates still would be a better option; for example,you don't need imports from `__future__` in python 3.

**Comment by ololoe** [comment]
up

**Comment by ololoe** [comment]
up
