### ISSUE TITLE
[Feature request] Clear 'Python Interpreter' window with a command?

### ISSUE THREAD

**Issue by Noomene** [pyscripter/pyscripter#834]
Hello PyScripter,

In the context menu of the python interpreter window (where my code executes when I click 'Run') there is an option called 'clear all' which clears all output. Is there a way to do the same using a command? I know there is an option in the options menu which, if checked, automatically clears the output whenever I click run. But that's not practical. Having a command that does the clearing allows more flexibility : sometimes I want to see the previous output for comparison. Sometimes I want to see only the new output. So having the command at hand I will not have to open the options menu every time, I just put the command wherever I want in my code or just run it in the command line

For example if I run python in the Windows 'cmd console' I can clear the output with the following command whenever I need to :
```
import os
os.system('cls')
```
Is there anything similar for the 'python interpreter' window of PyScripter?

Also one last question: is the second window called 'output' in the GUI just used for error messages or is it supposed to show the actual output of my code?

Thank you so much for PyScripter and for your reply!

Regards,

**Comment by pyscripter** [comment]
Instead of typing something like this
```
import os
os.system('cls')
```
isn't it easier to right-click and select Clear All?
In any case I will think about this.

The Output window displays the captured output of processes run externally to PyScripter, such as Run, External Run various tools such as the [pip installer](http://pyscripter.blogspot.gr/2017/10/installing-python-packages-easy-way-and.html)  etc.

**Comment by Noomene** [comment]
Thanks a lot for your answer and for considering this request.

It's just that, in addition to being a keyboard person, there are cases where one needs to clean the output from inside the code itself, i.e the code clears the output before displaying the second page of output for example, like the ClrScr command in the good old days of Pascal!!

Thank you for the details about the '_Output window_', I'm still learning PyScripter.
And thanks again for PyScripter and for considering this request.

Cheers,
