### ISSUE TITLE
python help file

### ISSUE THREAD

**Issue by amryounis** [pyscripter/pyscripter#835]
Hi,
I downloaded the python363.chm file but I do not where to store for pyScripter to show help from help menu->python manual
I am using anaconda 3 distribution

**Comment by pyscripter** [comment]
Pyscripter looks for the Python help file:
a) in the location specified in the following windows registry key for HKEY_LOCAL_MACHINE and HKEY_CURRENT_USER
`
\SOFTWARE\Python\PythonCore\' + SysModule.winver + '\Help\Main Python Documentation'
`
if this fails then looks at 
b) sys.prefix + '\doc'.

So in the PyScripter interpreter type

```
import sys
sys.prefix
```
and place the help file in the "Doc" subdirectory.   However it is surprising the help file is not there already.

**Comment by amryounis** [comment]
many thanks to you, it is working now
