### ISSUE TITLE
Is pyscipter open to paid enhancements to pyscripter ?

### ISSUE THREAD

**Issue by vcardon** [pyscripter/pyscripter#837]
Hello, I'm happy that PyScripter has revived.

Our business relies on PyScripter and it is a fantastic piece of good software.

PyScripter feeds 15+ stomachs at my company and it keeps as many spouses and many more children happy and fed.

I have enhancements to propose to PyScripter.

These enhancements I want them and I have some cash to sponsor the devs.

pyscipter, how can we work together ?

**Comment by pyscripter** [comment]
Please email me at pyscripter@gmail.com.
