### ISSUE TITLE
How did you create all the Highlighters?

### ISSUE THREAD

**Issue by raelb** [pyscripter/pyscripter#838]
Hi,

I'm curious to know how you created all the different highlighters for pyscripter? Was this done manually or by some automatic process. If automatic, could the same be done for other SynEdit languages/highlighters?

Thanks

**Comment by pyscripter** [comment]
They were contributed by users e.g.
https://github.com/tanmayameher/PyScripter-Color-Schemes
https://github.com/jprzywoski/pyscripter-highlighters

https://github.com/RRUZ/delphi-ide-theme-editor though from Rodrigo Ruz contains hundreds of color schemes which were generated automatically.  The project contains code that automatically converts Eclipse and VS themes to the Delphi IDE and SynEdit.
