### ISSUE TITLE
Not able to run Pyscripter in Windows 10

### ISSUE THREAD

**Issue by sumandoc** [pyscripter/pyscripter#840]
Hi,

I am running 64 bit Windows 10 Home Edition.

I have my Anaconda `Python 3` installed in `C:\Miniconda3`.
I have downloaded `PyScripter v3.1.0` 64 bit zipped version and unzipped it.
While trying to run the application by double clicking in the `PyScripter` application, I get following error:

![](https://i.imgur.com/Ao0WnQE.png) 

What should I do ?

**Comment by pyscripter** [comment]
If you want to use PyScritper with your Anaconda distribution, please read https://github.com/pyscripter/pyscripter/wiki/FAQ#how-do-i-use-pyscripter-with-portable-movable-python
and
https://github.com/pyscripter/pyscripter/wiki/FAQ#how-do-i-use-pyscripter-with-an-unregistered-version-of-python-eg-winpython

Alternatively, just install a standard Python distribution from www.python.org.

**Comment by sumandoc** [comment]
I created a `.bat` file and pasted

```
SET PYTHONHOME=C:\Miniconda3 
PyScripter --PYTHON36 --PYTHONDLLPATH "C:\Miniconda3" %1 %2 %3 %4 %5
```
 inside.

But its still not working.

I have only downloaded zipped PyScripter and unzipped it in my Desktop.

Do you mean I need to download two versions of PyScripter:  one `.exe` and one `zipped`?

**Comment by pyscripter** [comment]
Which version of Python is in c:\Miniconda3?  32-bit or 64bit?  Which version of PyScripter have you downloaded? 32bit or 64bit?  They need to much.   Is Python36.dll in directory c:\Miniconda3?

**Comment by pyscripter** [comment]
Did you use the Miniconda installer from https://conda.io/miniconda.html?  I am having a look.

**Comment by sumandoc** [comment]
Yes my PyScripter is **64 bit** and Miniconda3 is also **64 bit**.

I have `Python36.dll` in `C:\Miniconda3` as shown here

![ ](https://i.imgur.com/97ZEV0T.png)

And I can access `Python` from terminal as shown here

![ ](https://i.imgur.com/me1z6eA.png)

Still not able to use `PyScripter` !!

**Comment by pyscripter** [comment]
I have tried on two machines the following and it worked once with 32bits and the other 64 bits
a) Downaloded miniconda from https://conda.io/miniconda.html and installed for local user without modifying the path or registering the installation.
b) Downloaded marching version of PyScripter (zip file) and extracted to a some folder.
c) Within the PyScripter folder that contains PyScripter.exe I created a file "PyScripter.cmd" with the following commands:
```
SET PYTHONHOME=F:\Miniconda3
PyScripter --PYTHON36 --PYTHONDLLPATH "F:\Miniconda3"

```
d) Double-clicked PyScripter.cmd from Explorer and it run fine

![image](https://user-images.githubusercontent.com/1311616/34588390-6063167c-f1b5-11e7-81aa-ee406b78d4b7.png)

**Comment by pyscripter** [comment]
Confirmed that the above instructions also apply to unregistered WinPython installations.

**Comment by sumandoc** [comment]
After changing
```
SET PYTHONHOME=C:\Miniconda3 
PyScripter --PYTHON36 --PYTHONDLLPATH "C:\Miniconda3" %1 %2 %3 %4 %5
``` 

to

```
SET PYTHONHOME=C:\Miniconda3 
PyScripter --PYTHON36 --PYTHONDLLPATH "C:\Miniconda3"
```

in my `.cmd` file its working.

Thanks!!

**Comment by sumandoc** [comment]
Currently the PyScripter doesn't open at all without configuration **first** !!

Personally I believe it would be better the other way round:
1. let the IDE open first then
2. configure your python executable afterwards.

**Comment by pyscripter** [comment]
I agree.   This a planned feature.   It  will also allow you to switch Python version without restarting PyScripter.
