### ISSUE TITLE
PyScripter 3.2 x64 ruins line breaks on Windows

### ISSUE THREAD

**Issue by msalaev** [pyscripter/pyscripter#846]
I have a project (main development on Windows) and it runs at Debian VPS
Got an error after editing it in PyScripter: line breaks were set to Windows instead of Unix. 
Tried to change it in Edit -> File Format -> UNIX then Save
Reopened it again and see DOS/Windows again... 

Could you check it, please?

**Comment by pyscripter** [comment]
I can confirm this.  This is a serious regression and I will provide a hotfix release later today.

**Comment by pyscripter** [comment]
Fixed in 3.2.1
