### ISSUE TITLE
Inconvenience regarding changing color in highlighter

### ISSUE THREAD

**Issue by tanmayameher** [pyscripter/pyscripter#849]
In the Tools > Options > Editor Options (Syntax Colors Tab), it is really inconvenient to only use color picker to change the color of a element. I mean, it's not taking the Hex code i copy paste to it or write it in there. 

If someone know the color hex value, why do he/she go to search that value in internet and then only be able to change the element's color with color picker and also he need to keep both browser / color generator program and PyScripter side by side on the screen for that. Color picker should be a option but not the only option. 

Both copy, pasting hex code and color picker should work. It's really annoying to use the color picker all the time for a keyboard guy :).

Correct me if i am wrong or doing something wrong in this context. (try it first though)

**Comment by pyscripter** [comment]
$bbggrr works but red and blue are reversed than in #rrggbb
Fixed in version control.
Since you are working on syntax themes I can email you a ziped version of PyScripter.exe.  Just ask at pyscripter gmail.

**Comment by tanmayameher** [comment]
ooh, you mean that color red is #0000ff and blue is #ff0000 which is exactly opposite lol xD

So, if you have released new version even beta ones, then i will get that on my system, since i got the beta update on. So, it's ok. Otherwise, i will get one zipped version. 

It would be nice to correct the order / corrected it to RGB  since it will be counter intuitive.
Thanks

**Comment by pyscripter** [comment]
The current version would accept $0000FF instead of #FF0000 for instance (same color Red).  

The issue has been fixed and the next version will accept HTML constants as expected.  If you want an early preview please email me.

**Comment by pyscripter** [comment]
You can get executatbles (32bit and 64bit) that fix this issue from https://drive.google.com/drive/folders/18d4gutXCpbw3ldfpyLK2_O8I7bAF21dt?usp=sharing

The color edits accept both:
1. Color constants starting  with # (HTML color constant syntax)
2. Color constants starting with $ (Hexadecimal numbers corresponding to Windows color values)

e.g.  #0000FF and  $FF0000 are both accepted and represent the same color (blue)
