### ISSUE TITLE
Trying to compile on 10.2.1

### ISSUE THREAD

**Issue by limelect** [pyscripter/pyscripter#850]
1.   on AsyncCalls   2212  FatalException := AcquireExceptionObject;
Exception and tobject
2. found an OLD MPCommonUtilities, but compilation is a mess
   so i cannot compile
   May be more error ???

**Comment by limelect** [comment]
I know But a lot of problem more
TSynIdentChars is not known
tried to {$DEFINE UNISYNEDIT} to {.$DEFINE UNISYNEDIT} 
but the in another place same problem  TSynIdentChars is not known

**Comment by pyscripter** [comment]
Compiliation instructions:
https://github.com/pyscripter/pyscripter/blob/master/Compilation%20Instructions.txt
To be on the safe side get:
Synedit from
https://github.com/pyscripter/SynEdit-2
mustangpeakcommonlib 
https://github.com/pyscripter/mustangpeakcommonlib
mustangpeakeasylistview (not used but you may need it to compile virtual Shell tools.)
https://github.com/pyscripter/mustangpeakeasylistview
mustangpeakvirtualshelltools 
https://github.com/pyscripter/mustangpeakvirtualshelltools
sptbxlib
https://github.com/pyscripter/sptbxlib

**Comment by luebbe** [comment]
I'm just wondering if we could set up git submodules (or a powershell script) that pulls all the dependencies into a (lib|ext|whatever) folder, to get newcomers up and running quickly.

**Comment by pyscripter** [comment]
Another great idea!

**Comment by pyscripter** [comment]
Multiinstaller.exe is provided in the Components\ThirdParty folder for one-step installation of almost all dependencies.
Simplified compilation instructions provided.
Please try again and open a new issue if there is a problem.
