### ISSUE TITLE
Code snippets in translations

### ISSUE THREAD

**Issue by luebbe** [pyscripter/pyscripter#851]
It looks like there are a lot of code snippets (e.g. from Strings properties in dmCommands.dfm) in the translations. Maybe it would be better to store them in consts and assign them to the strings properties upon dmCommands.Create?
I can't compile pyScripter (yet), so I can only create a PR for you to review.

**Comment by luebbe** [comment]
I found a nice solution using ggexclude. As an example I included TJvMultiStringHolder (as class to exclude), which gets rid of the code snippets that I stumbled across and AsyncCalls.pas (as unit to exclude).
If we pursue this path, we can get rid of a lot of single entries in ignore.po

**Comment by luebbe** [comment]
We should generally review ignore.po. Several entries seem outdated, some look like they should be translated. More components or files could be added to ggexclude.cfg.
I got rid of all the TJvMultiStringHolder and AsyncCalls.pas entries in ignore.po

**Comment by pyscripter** [comment]
I use TJvMultiStringHolder to store Python scripts PyScripter needs to run.  I often modify these scripts and this creates the issue.  It is more convenient to use TJvMultiStringHolder  than a string constant, because it makes much easier to update.    

`TP_GlobalIgnoreClass(TJvMultiStringHolder); 
`
is used so dxgettext is not trying to translate these strings, however this is not recognized by dxgettext's parsing code.  How does ggexclude work?  It sounds like the appropriate solution.

**Comment by luebbe** [comment]
Yes, that's why I excluded TJvMultiStringHolder from extraction via ggexlude.cfg

ggexclude.cfg is a file that is stored in the base folder (like ignore.po). It contains different sections for different types of objects to ignore. It supports wildcards for properties, but not in any combination.
So you can exclude all of TEdit with TEdit.*, but you can't exclude all Name properties with *.Name. This would be cool for *.Font.Name for example.
The documentation can be found at: https://sourceforge.net/p/dxgettext/code/HEAD/tree/trunk/dxgettext/docs/

**Comment by pyscripter** [comment]
Great work.   Out of curiosity, is ggexclude.cfg used by dxgettext.exe in update-pot.ps1?

**Comment by luebbe** [comment]
yes, automatically. The file just hast to be there. Unlike ignore.po it is not necessary to specify it on the command line.
BTW I switched plain Portuguese for Portuguese Brazil + Portuguese Portugal, since two guys expressed interest in maintaining both variants.

**Comment by pyscripter** [comment]
Ok I am closing this then.
