### ISSUE TITLE
Translation terminology question

### ISSUE THREAD

**Issue by luebbe** [pyscripter/pyscripter#852]
Are "Theme" and "Style" the same thing in PyScripter? If yes, we should use the same word in both cases. If not we should point out the difference, which is used when.

**Comment by pyscripter** [comment]
I am using themes for the editor syntax highlighting schemes and styles for the user interface aka Vcl Styles.
The user can independently choose in the Editor Options dialog box a syntax highlighting theme and from the View menu an Application Style.   Another name used for styles is skins in English.

I know this is a translators nightmare.  Thankfully theme is a Greek word with a direct translation and style is also used (στυλ).

**Comment by luebbe** [comment]
OK, I'll add this to the terminology in transifex. In German there is no good distinction.

**Comment by pyscripter** [comment]
Syntax highlighting scheme is also used instead of theme.
The term "theme" is used in https://github.com/RRUZ/delphi-ide-theme-editor for the same function.  If you have any better suggestions I am happy to consider.
