### ISSUE TITLE
Translator credits

### ISSUE THREAD

**Issue by luebbe** [pyscripter/pyscripter#853]
I would suggest to separate the names from the languages and in the translator credits and all language credits into a separate string. Then insert the names like:
```
const
  cItalianTranslators = 'Peter, Paul, Mary';
  cGermanTranslators = 'Hans, Wurst';

sTranslatorCredits := 
  format(_('Italian translation: %s'),[cItalianTranslators]) + sLineBreak +
  format(_('German translation: %s'),[cGermanTranslators]);

```
Right now, every time I add a translator to the credits, this string has to be re-translated in every language.

**Comment by pyscripter** [comment]
Please go ahead,

**Comment by luebbe** [comment]
Done, but please be aware that this is (almost) completely untested, since I can't compile PyScripter.

**Comment by pyscripter** [comment]
Compiles fine.
Thanks!!
