### ISSUE TITLE
[Issue(or I just didn't understand)][Project]Unable to start a new project, unless...

### ISSUE THREAD

**Issue by TheAdventist** [pyscripter/pyscripter#854]
This one might be because of shortage of knowlegde in Python's/PyScripters ways to save folder/projectstructure's, but... I am unable to open a new project. No error messages, no warnings. Nothing.

That is; unless you uncheck Relative Paths (right click on Untitled project). Is this normal or might this be a bug?

If not; feel free to delete :)

Tested on PySc 3.2.2.0 x86

**Comment by pyscripter** [comment]
You can either open an existing project or create a new project.  When you start PyScripter and go the Project Explorer a new project is already there for you to add content.  So, the command Project, New Project does no do anything.  

To learn how to work with the Project Explorer, please consult the help file (IDE Windows, "The Project Explorer window" topic).  Once you save a project (Project, Save Project) the base name of the file becomes the name of the project.
