### ISSUE TITLE
Grow dialog sizes to accomodate translations.

### ISSUE THREAD

**Issue by pyscripter** [pyscripter/pyscripter#858]
Many dialogs need to grow in size to accommodate translations.

**Comment by luebbe** [comment]
Almost all dialogs under Tools -> Options. Also the buttons have to grow in size to accomodate text and a little space around the icons.
Tools -> Options
- IDE Shortcuts
- Editor Options
- Custom Parameters
- Code Templates
- File templates

**Comment by pyscripter** [comment]
Done
- IDE Shortcuts
- IDE Options

**Comment by pyscripter** [comment]
Fixed all the above.
