### ISSUE TITLE
"Maximize Editor" twice, "Restore Editor" won't recover

### ISSUE THREAD

**Issue by seaspeak** [pyscripter/pyscripter#861]
If I execute "maximize editor" twice in a row, "restore editor" won't work anymore.
The editor stays in maximizing mode.

**Comment by pyscripter** [comment]
You can always go back to the default layout.  View, Layouts, default.

This is what Maximize editor does.
-  Saves the existing layout.
-  Change the layout to a "Maximized" one.

-  Restore changes the layout back to the saved one.

If you Maximize twice (why would you do this?), the saved layout becomes the maximized, so restore does not have any visible impact.

**Comment by seaspeak** [comment]
I thought "maximize editor" is something like "full screen (F11)" so that I can toggle between the two states. Actually I still think it is more intuitive to act that way (hide/show all panels/(toolbars)).

Sometimes I get confused about the hotkeys, so I mistakenly Maximize twice. Ha ha.

Thanks for your explanation.

**Comment by pyscripter** [comment]
You can also double-click on the editors' tab bar to Maximize/restore.
