### ISSUE TITLE
Maximizing Window doesn't fill up whole desktop

### ISSUE THREAD

**Issue by seaspeak** [pyscripter/pyscripter#862]
Look at the right edge of the window. The window is not maximized.
![image](https://user-images.githubusercontent.com/8821870/37962551-0aac8d0c-31ee-11e8-973c-d621cfe6652e.png)

**Comment by pyscripter** [comment]
I cannot reproduce here and sure what I can do about it.
What is you display resolution?
Are you on Windows 10?

**Comment by pyscripter** [comment]
Which style are using? (View Styles..,)

**Comment by seaspeak** [comment]
Changing styles doesn't make any difference. I also restore the layouts. My current style is 'light'.
My system is Windows 10 Pro and the resolution is 1024 x 768.

I don't recall I have this problem with pyscripter2.

**Comment by pyscripter** [comment]
The style engine has changed in version 3.0.

**Comment by pyscripter** [comment]
A new IDE Option "Style Main Window Border" has been introduced.  In the next release set it to False to resolver this issue.
