### ISSUE TITLE
python engine

### ISSUE THREAD

**Issue by z954134** [pyscripter/pyscripter#865]
new version python engine have no 本地 .
ther have no error in english language .but have error in chines language
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)

**Comment by pyscripter** [comment]
Could you please provide some more details:
-  Pyscripter version
- Python version
- Instructions for reproducing the error

**Comment by pyscripter** [comment]
No feedback, so I am closing this issue.
Please see http://pyscripter.blogspot.com/2012/02/dreaded-unicode-encodedecode-errors.html.
See also the PyScripter help topic "Encoded Python Source Files" for details and info on how to fix this problem.
