### ISSUE TITLE
Request: Close all tabs to right (when right-click a tab)

### ISSUE THREAD

**Issue by gibberishbc** [pyscripter/pyscripter#866]
In Editor, with multiple files open, when right-click on any tab we see options: "Close", "Close All"  and "Close All Other"

In Notepad++, I frequently use "Close All Tabs To Right"  - which closes all tabs to the right of the right-clicked tab. This is particularly useful when stepping through code and additional files are auto-opened as part of the debugging process.

BTW, is there an option to not open/step-into system modules that are not specifically part of my project -- such as _bootlocale.py, codecs.py, cp1252.py, etc - which get opened/stepped-into when debugging with F7? That would be a handy checkbox option. "Blackbox system modules" or some such.

**Comment by pyscripter** [comment]
Regarding stepping through the code, there is the __traceable__ variable you can set.

Type the following into a new module.
```
import time
import inspect
print(inspect.ismodule(time))
```
and then press F7 repeatedly.   You will trace into the inspect.ismodule function.

Now modify the code:
```
import time
import inspect
inspect.__traceable__ = 0
print(inspect.ismodule(time))
```
and again press F7 repeatedly.   You will notice that the debugger will not trace into the inspect module.  So you can make your code debug faster by making some of the module imports non traceable.

**Comment by pyscripter** [comment]
Implemented in version control.
