### ISSUE TITLE
Spyder-like variable explorer

### ISSUE THREAD

**Issue by kapil-iitk** [pyscripter/pyscripter#867]
Is there any possibility, to include the variable explorer similar to "Spyder" in PyScripter?

**Comment by pyscripter** [comment]
Note to myself.  https://github.com/dmnfarrell/pandastable

**Comment by kapil-iitk** [comment]
any update?

**Comment by pyscripter** [comment]
Implemented debug inspectors which addresses this issue as well.
See https://pyscripter.blogspot.com/2023/10/feature-preview-debug-inspectors.html
