### ISSUE TITLE
Error 126: Could not open Dll "python27.dll"

### ISSUE THREAD

**Issue by ManPython** [pyscripter/pyscripter#868]
The issue is back for Pyscript 3.3.2
https://github.com/pyscripter/pyscripter/issues/643
https://github.com/pyscripter/pyscripter/issues/860

..and the solution is stupid imho 
https://github.com/pyscripter/pyscripter/wiki/FAQ#how-do-i-use-pyscripter-with-portable-movable-python

I want sugest the config.ini file or config.json with vars for each custom version of Python
Then in shortcut just call the right version of Python, eg. we can have Python27 but in fact are Python278 Python279 and this trend is going next for Python34/36 etc.
Soo.. in config we setting Python278 and in shortcut we calling right var as --Python278 etc.

The config.ini is/can be the source for external Engine that we can change live the Python interpreter.

**Comment by pyscripter** [comment]
See https://pyscripter.blogspot.gr/2018/05/new-feature-switching-python-versions.html.

**Comment by ManPython** [comment]
@pyscripter unfortunaly any of new version downloaded from https://sourceforge.net/projects/pyscripter/ not working to me (I mind the pyscripter is not opened, just blink on task manager and closed). I back to the previous versions.

After troubles with this all I moved to the Visual Studio Code, but I prefer small fast pyscripter.

**Comment by pyscripter** [comment]
It will be in version 3.4.  Not out yet.

**Comment by pyscripter** [comment]
Try the version 3.4 and see https://pyscripter.blogspot.gr/2018/05/new-feature-switching-python-versions.html.  It works the way you described it.

**Comment by ManPython** [comment]
@pyscripter  Thx, now all working aceptable on x64 : )

**Comment by ManPython** [comment]
The edit to path (in setup options) must be repaired to as editline to edit not only path tree when adding - it's frustrating to click and click to select path. The adding must be as editline to easy add path, not clicking folders..
The dialog window must be auto-resizable and similary the treewidget.
Maybe we can change ver of py by shift+f1..f2..f9

The selected python version should be visible in status bar. I often don't know which is selected and checking in Run > PyVer wasting time.

File explorer should have path adress like win explorer.
