### ISSUE TITLE
Change default Ctrl+Y from delete line to redo to be Windows compliant

### ISSUE THREAD

**Issue by gibberishbc** [pyscripter/pyscripter#869]
By default in Pyscripter, Ctrl+Y is delete line. It should be "Redo". This is a common, long-time, Windows key mapping across all Windows applications and users will expect Ctrl+Y to redo last edit, not delete the line. Although a very minor edit, and quickly fixed by individual users (remap key) I suggest rolling this one out asap as it immediately impacts new users (in a most unhappy way). 

See 
https://en.wikipedia.org/wiki/Control-Y
https://support.microsoft.com/en-ca/help/12445/windows-keyboard-shortcuts
https://www.pcmag.com/article/355400/windows-10-guide-essential-keyboard-shortcuts
https://www.quora.com/Keyboard-Shortcuts-What-is-more-common-as-an-redo-button-Ctrl-Shift-Z-or-Ctrl-Y
https://superuser.com/questions/1265836/when-did-the-redo-keyboard-shortcut-change-from-ctrl-y-to-ctrl-shift-z

**Comment by pyscripter** [comment]
I will think about it.  For my generateion...

> Ctrl+Y deleted the current line in the WordStar word processor for CP/M and MS-DOS.[3] In the 1980s, many text editors and word processors mimicked the WordStar command set, making Ctrl+Y a common synonym for "delete line. 

It is the same with Borland and now Embarcadero IDEs.

PyScripter has the ability to import export editor keymaps.  If you look at https://github.com/pyscripter/pyscripter/wiki/Customization someone created Vim like keymaps.   If you or some else is prepared to produce alternative editor keymaps, I could include them in the distribution, in the same way I include styles and editor themes.

**Comment by pyscripter** [comment]
I am convinced, but what is your suggestion for delete line?

**Comment by gibberishbc** [comment]
I would suggest using the most common shortcut key for the majority of the other most popular IDE packages:

Ctrl + Shift + L ----- Notepad++
Ctrl + Shift + K ----- VSCode
Ctrl + Shift + K ----- Atom
Ctrl + Shift + K ----- Sublime Text

Although I'm a Notepad++ guy myself, I would suggest Ctrl + Shift + K for maximum compatibility with prevailing muscle memory. UPDATE: Belay that - I just checked the existing shortcuts and see:

Ctrl+Shift+K would not be a good choice b/c it is now the Unfold trigger, which is popular as it is
Ctrl+Shift+L also would not be a good choice b/c it is now Line Select mode
Ctrl+Shift+M appears to be unused, and would fit well into the NPP/Atom/Sublime/VSCode pattern.
Ctrl+Shift+N is Normal Select mode

So, my thought is that if NPP can get away with Ctrl+Shift+K, then PyScripter should be fine with Ctrl+Shift+M. What do you think?

**Comment by pyscripter** [comment]
Thanks for the thorough search. Unfotunately Shift-Ctrl+M is an IDE short cut (parameter completion).

Interestingly Ctrl + K is the fold trigger in VS Code as in PyScripter, but there are no shortcuts for unfolding.  So Shift+Ctrl +K can be used.


Shift+Ctrl + D is unassigned in the editor and the IDE.  Does this make sense to use?

**Comment by gibberishbc** [comment]
Shift+Ctrl + D sounds like a great choice for the delete line shortcut.

In Notepad++, Ctrl+D is the shortcut for duplicate line, so Shift+Ctrl + D would follow logically as the opposite function.

**Comment by pyscripter** [comment]
Fixed in version control.
