### ISSUE TITLE
Code Folding - please add "Toggle Unfold/Refold entire function/class/region" shortcut key

### ISSUE THREAD

**Issue by gibberishbc** [pyscripter/pyscripter#870]
[Ctrl] + [Shift] + [-] ===> Folds all regions in Editor
[Ctrl] + [Shift] + [+] ===> Unfolds all regions in Editor

Could there be a shortcut to unfold/refold the entire function ("region"??) the cursor is in? It is time-consuming to unfold each (?range?) within the function manually, especially since code folding has to be re-done each time the document is saved or run (upon save, all folded sections unfold).

The help file mentions [Ctrl] + [Shift] + [/] as unfolding the nearest range (is that a single [+] section in the gutter-margin?) , but this only unfolds the first level - in my functions, there are typically 20+ folded sections within a normal function.

Folding/Unfolding individual levels via keyboard is not as useful as folding/unfolding an entire function/class/module.

Perhaps if the entire function/class/module under the cursor is folded,  [Ctrl] + [Shift] + [/] can toggle folding just that one function/class/module?

I apologize for not using the correct help-file terminology, but am not 100% sure what is meant in the help file by "region" and "range" and do not wish to mistake the terms by using them.

**Comment by pyscripter** [comment]
https://stackoverflow.com/questions/8265583/dividing-python-module-into-multiple-regions
```
#region My Block of Code
def f1():
    pass
def f2():
    pass
#endregion
```
Range is anything can can be collapsed or expanded.

**Comment by gibberishbc** [comment]
Okay, thanks for that explanation. So, then, is it possible to toggle folding for an entire indented range (i.e. function), including all levels within that range? That is, from start of indent to end of that level indent, and all ranges in between?

Toggling the "level 1" indent ([Ctrl]+[K] [Ctrl]+[1]) will only unfold ALL the level-1 folds within ALL folded defs (functions). There are two problems with this:

1) I need all levels unfolded underneath _this_ def, and
2) I don't want any other folded defs to be changed

**Comment by pyscripter** [comment]
What you can do now 
1.  If say you want to fold/unfold whole functions.
A. Unfold All
B  Fold functions
Now when you unfold a function it appears fully unfolded.  If you want to fold it back just fold it with the mouse or with cursor on the function def select Fold Nearest.

2.  Another good way to have a bird's eye view of your code is.
A.  Fold All.
B  Unfold classes

3.  You are inside a heavily nested function. Just press Ctrl+/ (Fold Nearest) a few times until you fold up to the level you want.  

What I think you ask for is something like Unfold Nearest but working recursively.

**Comment by pyscripter** [comment]
I am closing this since there is no feedback.
