### ISSUE TITLE
Fail to switch remote "Wx" engine

### ISSUE THREAD

**Issue by tapdo** [pyscripter/pyscripter#872]
"Wx" engine is not work. 
When I sellect "remote (Wx)" from right crick menu on interpreter, the below message is shown.

[ Error ]
Could not connect to the remote Python engine server. The remote interpreter and debugger is not available.
[ Abort ]

My PyScritor is 3.3.2.0 x64 on Windows 7.
Python is 3.6.3 64bit,  Wx version is 4.0.1 msw (phoenix).

In my memory, when Python 2.7 environment of some years ago , I can use wx engine...maybe.
Can anyone use Wx engine now?

**Comment by pyscripter** [comment]
I will have a look regarding wx 4 compatibility.
However let me say that you can still use the standard Remote engine to run or debug your wx scripts.  The Tk and Wx python engines are specialised ones allowing you to interactively build and test GUI applications from the command prompt.

**Comment by tapdo** [comment]
Yes, I use standard remote engine. However there is another problem. I attached tiny sample code.
Please run on standard remote engine, after that, Reinitialize engine. Then  "PyScripter is waiting for the remote engine..." message is shown but cannot escape running state. So I should kill PyScritor process in this case.
I often use "Reinitialize engine" when my application hung-up especially multi-thread.

[tiny_sample.zip](https://github.com/pyscripter/pyscripter/files/1943924/tiny_sample.zip)

**Comment by pyscripter** [comment]
It works fine if you close the wxApp normally first.
The next version of PyScripter will allow you to Reinitialize without problems even without closing the wxApp.  (it will "kill" the running wxApp).  This has already been implemented.

**Comment by pyscripter** [comment]
Fixed in PyScripter 3.4.
