### ISSUE TITLE
Using autocomplete suggestion changes leading spaces

### ISSUE THREAD

**Issue by RedSpiderMkV** [pyscripter/pyscripter#876]
Hi.  I'm using the latest version of PyScripter (version 3.3) on Windows 10 Pro.  Running Python 2.7.11.

If I press enter to accept an autocompletion suggestion, the leading spaces on the line are replaced with just two spaces... so then I have to hit shift + home, delete, tab tab tab to the correct place again...

These niggling issues are preventing me from using what's turned out to be a bloody brilliant Python IDE.. hoping it gets fixed soon :) thanks!

**Comment by pyscripter** [comment]
Although not recommended, if you want to stick with Tabs, this issue will disappear if you turn "Trim trailing spaces off"
