### ISSUE TITLE
Cursor can go farther than the EOL when you click on a position

### ISSUE THREAD

**Issue by masoudim** [pyscripter/pyscripter#878]
I don't know if this is a feature or a bug (I assume it is the former but I think it is really annoying). Imagine you are editing a code in the editor. and There is the following line in the editor:

blah blah blah() blah

This line has 20 characters. Now if you click on (say) column 30, the cursor will stay on column 30. While in almost all other text editors, no matter on which column of that line you click, if it is after the last character in the line, your cursor goes to the end of the line. Please fix this.

P.S. I was wrong. There is an option to turn this off. I don't know how to delete this issue from here! any body knows?!

**Comment by pyscripter** [comment]
Editor option:  Scroll past End of Line.  Switch off if you do not like.
