### ISSUE TITLE
loading file warning, error in decoding file

### ISSUE THREAD

**Issue by pqwer99** [pyscripter/pyscripter#879]
when start pyscripter( restore open files->True).
warning message: error in decoding file xxxx.py from 'cp936' | 'gbk' encoding.

but from file->open no problem.

the file first line: # -*- coding: gbk -*- or # -*- coding: cp936-*-

**Comment by pyscripter** [comment]
Thanks for the report.  It will be fixed in the next version.  Just ignore the warning for the time being.

**Comment by pyscripter** [comment]
Fixed in version control
