### ISSUE TITLE
PyScripter could not load a Python engine

### ISSUE THREAD

**Issue by flo025** [pyscripter/pyscripter#881]
I have installed python but there is a error message "PyScripter could not load a Python engine" and when I click "OK" there is no python versions in registered versions AND unregistered versions...

**Comment by pyscripter** [comment]
You can add your python versions to PyScripter in that dialog.  Just press the + key and select the directory that contains python.exe and pythonxy.dll.

PyScripter doesn't come with python.  You need to have some python distribution installed.  Just remember:  

The 64-bit version of PyScripter (x64) works only on 64-bit Windows **and** with 64-bit versions of Python.  The 32-bit version of PyScripter works on both 32-bit and 64-bit Windows with the 32-bit versions of Python.

**Comment by UnderJollyRoger** [comment]
I downloaded python 3.7 (32bit) and attempted to load it in PyScripter, but got this same message. It's placed in Unregistered Versions. Python 2.7 (32 bit) works fine.
![image](https://user-images.githubusercontent.com/32503258/48095056-5aa95600-e1d9-11e8-92cc-1f4d2c3c2c8f.png)

**Comment by pyscripter** [comment]
Is this a standard Python distribution for python.org?
Are you on Windows 64bit?
Are you using PyScripter 3.4.2?

**Comment by UnderJollyRoger** [comment]
Yes, the 3.7 download was from python.org
Yes, I'm using Windows 10 Pro 64 bit
I can't figure out what version of PyScripter I'm using?

**Comment by UnderJollyRoger** [comment]
I've updated to 3.4.2 and continue to see this message when attempting to switch versions.
![image](https://user-images.githubusercontent.com/32503258/48097989-0a35f680-e1e1-11e8-9e2e-00571f74d56a.png)
![image](https://user-images.githubusercontent.com/32503258/48097997-10c46e00-e1e1-11e8-8bef-8e753e74bb9d.png)

**Comment by pyscripter** [comment]
What happens if you press the test button?  Are you sure you have installed the 32-bit version of python 3.7?   Enter the python shell and have a look at the top line.

**Comment by pyscripter** [comment]
Also check the registry. Does the key Computer\HKEY_CURRENT_USER\Software\Python\PythonCore\3.7-32 exist and does Computer\HKEY_CURRENT_USER\Software\Python\PythonCore\3.7-32\InstallPath point at the correct directory?

**Comment by UnderJollyRoger** [comment]
I hit the test button for both versions of 3.7 you see in the screen shot and they are 32 bit.
Yes and Yes. The install path folder contents point to where I put them/where I set PyScripter to find them.
![image](https://user-images.githubusercontent.com/32503258/48138671-6b55dc80-e26a-11e8-9a5d-611c6abaf9ba.png)

**Comment by pyscripter** [comment]
Strange. PyScripter works fine here with 3.7.0 and 3.71.  
I see that is listed in the list of registered versions, but I guess activating that fails as well. (?).
If you open a command prompt, do you see any python related variables? (PYTHONHOME or something similar)?

**Comment by UnderJollyRoger** [comment]
Yes, I tried activating both registered and unregistered. They both give you the same message. 

Yes, I did get a whole bunch of variables after typing `>Set`. 
![image](https://user-images.githubusercontent.com/32503258/48204816-5b083500-e330-11e8-803f-dc2c2f5c78aa.png)

**Comment by pyscripter** [comment]
This PYTHONHOME=  looks very suspicious to me.  Normally when an environment variable is empty it does not show.  Try to get rid of it.

Windows 10 and Windows 8
- In Search, search for and then select: System (Control Panel)
- Click the Advanced system settings link.
- Click Environment Variables. In the section System Variables, find the PATHHOME environment variable and delete it.

**Comment by UnderJollyRoger** [comment]
I don't see a PATHHOME variable in the Environment Variables menu?

**Comment by UnderJollyRoger** [comment]
In Tools >> Python Path I noticed there was no path pointing to the 3.7 version. Do I need to add that path here?
![image](https://user-images.githubusercontent.com/32503258/48212535-6d3e9f00-e341-11e8-8acc-3de19d1aef1e.png)

**Comment by UnderJollyRoger** [comment]
I browsed to 3.7-32 in this window and the Added it. Then I closed out of PyScripter, opened it again and went to this same menu, but the path was no longer there?

**Comment by pyscripter** [comment]
- The Python path dialog  is for temporary changes to the python path.  Not useful here.
- In Windows 64 bit, 32 bit applications are installed in c:\program files (x86).  So it is normal that PyScripter 32bit is installed in that folder.

What might be causing the trouble is the PYTHONHOME (not PATHHOME) environment variable.  If you look at the image with the output of the SET command it has a line:

`PYTHONHOME=
`
This is indicates that the PYTHONHOME environment variable is defined with a non blank value (could be a space for example) .

What I told you above is to remove this environment variable.  You can do so by following the instructions.

**Comment by pyscripter** [comment]
In addition or instead you can check the registry entries:

HKCU\Environment
HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment 


to see whether PYTHONHOME is defined there.

**Comment by pyscripter** [comment]
I am sorry.  I am running out of ideas.

**Comment by UnderJollyRoger** [comment]
Thanks for the help. It'll get figured out at some point. The thing is, ESRI is pretty much turning people away from ArcMap and towards ArcPro in the proprietary GIS world. And that means Python 2.7 will go too, because ArcPro uses 3.x. This is the reason I need to get 3.7 set up in PyScripter. It's my favorite IDE!

**Comment by pyscripter** [comment]
I had no problems getting pyscripter to work with ArcPro.  See
https://pyscripter.blogspot.com/2018/10/using-pyscripter-with-arcgis-pro.html.


Just one last thing.  I don't think is relevant, but in you regedit impage I see there is another python 3.7 installed.  This must be the 64 bit.  Is that right?  ArcPro is 64bit only.  Have you tried using the 64bit version of PyScripter with a 64bit version of Python?

**Comment by UnderJollyRoger** [comment]
Ok, thanks for that.

Yes, that's correct. The Python37 folder is 64bit. No, I have not-- worth a shot, however. I will try next week and post what happens.

**Comment by UnderJollyRoger** [comment]
Indeed. I prefer QGIS. But, they prefer ESRI. 

I installed PyScripter 64 bit. It opened with Python 3.7. So, that's a good back-up. It'd still be nice to have only one version of PyScripter.

**Comment by olfyy784** [comment]
> 
> 
> I downloaded python 3.7 (32bit) and attempted to load it in PyScripter, but got this same message. It's placed in Unregistered Versions. Python 2.7 (32 bit) works fine.
> ![image](https://user-images.githubusercontent.com/32503258/48095056-5aa95600-e1d9-11e8-92cc-1f4d2c3c2c8f.png)

plz how can i download pyscripter  32 bt ?

**Comment by pyscripter** [comment]
@olfyy784 

- Is this a distribution from www.python.org?
- Is Python 37 registered?  Does the registry key HKEY_CURRENT_USER\Software\Python\PythonCore\3.7\InstallPath exist and properly set up?
- Does the procedure reported at the bottom of #938 work?

**Comment by CopperyMarrow15** [comment]
Hello. I seem to have a similar problem with PyScripter 64 bit.
Instead of a problem with clicking on a version, I can't get the versions to appear in the version window in the first place.
No matter what path I use, PyScripter says it didn't find Python at that path. It was mentioned at the beginning that...
> You can add your python versions to PyScripter in that dialog. Just press the + key and select the directory that contains python.exe and pythonxy.dll.

The path I use contains python.exe but not pythonxy.dll. I did a search for it and found no results. Might that be the reason?

Also, if this helps, `PYTHONHOME` did not appear when I typed `set` in the directory.

Let me know if you can help.

**Comment by pyscripter** [comment]
Yes, normally the dll is in the same path as the exe (virtual environments are a special case that is handled by pyscripter).  Which version of python have you installed?

**Comment by CopperyMarrow15** [comment]
currently 3.4.4

The following are in my "Python34" directory:
DLLs
Doc
include
Lib
libs
Projects [where I keep my projects]
Scripts
tcl
Tools
venv1 [a virtual environment I created]
LICENSE.txt
NEWS.txt
python.exe
pythonw.exe
README.txt

no pythonxy.dll...
I also searched the entire directory for such a file...but none was found.

**Comment by CopperyMarrow15** [comment]
I just got the newest distribution (3.8.1) and neither PyScripter 64 bit nor PyScripter 32 bit recognized it. Perhaps, it would work if I used another path? I use C:\Python3-8-1 now...

**Comment by pyscripter** [comment]
- Is this distribution from www.python.org?
- Have you installed it for all users or for a single user?
- Is it 32-bit or 64-bit?

Please open the python interpreter and type in the prompt
>>> import sys
>>> sys.version

What do you get?

Find pyscripter.local.ini in your %APPDATA%\pyscripter directory (%APPDATA % is the value of the environment variable) and delete it.  Then restart Pyscripter (same bitness as the python installation).   It should find and load python 3.8.1 automatically if the python installation is registered.

**Comment by CopperyMarrow15** [comment]
Yes, it is from python.org.
I installed it for all users.
It is 32 bit.

I got:
`'3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)]'`

I'm afraid to ask...but where is %APPDATA% ?

**Comment by pyscripter** [comment]
Open a command prompt and type 
>set
See the value of APPDATA

**Comment by pyscripter** [comment]
You need to use PyScripter 32-bits

**Comment by CopperyMarrow15** [comment]
I've deleted PyScripter.local.ini in the AppData\PyScripter folder successfully. Yet, PyScripter still gives this error message...
![image](https://user-images.githubusercontent.com/58375366/72895192-d615fb00-3cea-11ea-92e3-48a5618bee73.png)

I use Windows 8... Might it only work with 10?
The OS is 64 bit.
I have 32 bit and 64 bit PyScripter.

**Comment by StandartX** [comment]
doesnt work

**Comment by ZePorro811** [comment]
Until now PyScripter did not detect WinPython versions, which meant that I had to indicate the Python version as “unregistered” inside PyScripter.

I have discovered that this happens because WinPython creates the registry key as:

\HKEY_CURRENT_USERSoftware\Python\WinPython\.... 

But renaming the above key to:

\HKEY_CURRENT_USERSoftware\Python\**PythonCore**\....

The problem is solved since, once renamed, PyScript correctly detects the Python version and registers it as “registered Version”.

Regards,
