### ISSUE TITLE
Choose python branch from shebang on open file

### ISSUE THREAD

**Issue by ololoe** [pyscripter/pyscripter#882]
Does pyscripter already has this feature? python3 = python 3, python, python2 or empty = python2

**Comment by pyscripter** [comment]
Look at the help file, command line options  e.g. --PYTHON27 etc.   However since Pyscripter 3.4 this is no longer needed since you can now switch between versions at any time without exiting Pyscripter.
https://pyscripter.blogspot.gr/2018/05/new-feature-switching-python-versions.html

**Comment by ololoe** [comment]
That's not what I meant. I wanted pyscripter to automatically choose right python version for a file.

**Comment by pyscripter** [comment]
Is it so much trouble to switch manually after Pyscripter opens.  You may have multiple version 3 and version 2 Pythons.  How should Pyscripter choose?

**Comment by ololoe** [comment]
The same way as pylauncher does.
