### ISSUE TITLE
Readonly mode

### ISSUE THREAD

**Issue by ololoe** [pyscripter/pyscripter#883]
Is there such an option? If yes - add please. Files from python's dir should be opened in readonly by default.

**Comment by pyscripter** [comment]
Good suggestion,  Will be implemented.

**Comment by ololoe** [comment]
I often ctrl+click on items or click on stacktrace. This feature can protect 3rd party code from unintentional edits.

**Comment by pyscripter** [comment]
Fixed in version control.
Files opened by PyScripter from the Python directory during debugging are read only by default to prevent accidental changes.

**Comment by ololoe** [comment]
Is it already released?

**Comment by ololoe** [comment]
There is no visual difference if readonly mode if enabled or not.

**Comment by pyscripter** [comment]
When the file is active "Read-only" is displayed in the status-bar.

**Comment by ololoe** [comment]
that's not the place I look at. Take a look on Notepad++ e.g.

**Comment by ololoe** [comment]
Now you added an icon near file name, as I mentioned.
