### ISSUE TITLE
debugging with modules,  location lost after editing 

### ISSUE THREAD

**Issue by jodyhey** [pyscripter/pyscripter#884]
When debugging line by line,  or with breakboints.

If the module has not been edited since the pyscripter session started,  then stepping or running to a line of source code in the module works fine. 

However if the module has been edited since the last time the debugger was started in the current session,  then pyscripter goes to the wrong location in the module when stepping into or running to a line of source code in a module.

**Comment by pyscripter** [comment]
I am afraid Pyscripter does not support changes to the source code file during debugging.  If you want the execution to reflect changes you made to source code then you should start a new debugging session.

**Comment by jodyhey** [comment]
ok, I probably was not clear.  If I am debugging,  and then stop the run, and edit an imported module,  I cannot start a new debugging run and have it run correctly.   Currently I have to close pyscripter to end the session and then open the files again.

**Comment by jodyhey** [comment]
noticed it happens with I use an internal python engine,  but not when using remote

**Comment by pyscripter** [comment]
For such reasons, the internal python engine is deprecated and hidden by default.  Please use the remote python engine.  

You can try to use reload for the changed modules but this is not without problems.

**Comment by jodyhey** [comment]
ok, thanks
