### ISSUE TITLE
cursor to end line

### ISSUE THREAD

**Issue by Quetzaal** [pyscripter/pyscripter#886]
hi,
on win10, the cursor do not shift nomore to the end of the line, and stay where it have been click

this new way to insert cursor in a text is funny 10secondes... i do think now that something went wrong...

cursort should glue the end of line 

i went in options if there was something about it... but or it exist and i don't find it, or something went wrong...

thanks for readding

**Comment by pyscripter** [comment]
Disable this feature by going to the Editor Options and uncheck the option "Scroll past End-of-Line".

**Comment by Quetzaal** [comment]
hi,
i went, itried, but i falled ;)

its finally just an option three line under

x scroll hint follow mouse <= wich is checked, and is not on 2.6 (i've reinstall 2.6 to have a look about these options)

veni, vidi, vici (i've dreamt to say it, then whe not today ;) ))

thanks a lot

**Comment by pyscripter** [comment]
The Editor option is called "Scroll past end of line".

By the way Pyscripter version 3.4 is available.  The version you are using is very old and unsupported.
