### ISSUE TITLE
too many treeviews on left side

### ISSUE THREAD

**Issue by Quetzaal** [pyscripter/pyscripter#887]
hi,
well, i don't know what i did... but, the three view which use in "pinned" mode to stay in only one windows split in one treeview by "option" 
and only come back in one window/menu only unpinned... 

it makes hards my days... but may be somebody knows the ways in pinned mode to not have many windows, but still many optionnal treeview available ?? 

but, as it a surprising mode, the facultie to see two or three of them openned in the same time, as for more, this way to show them, is a "bit short"

thanks a lot

**Comment by pyscripter** [comment]
I am not sure I understand the issue.  You can make any layout you want.  You can hide the different views through View, IDE Windows. You can pin them or unpin them.

Can you post a screenshot to help understand what you mean.

**Comment by Quetzaal** [comment]
file:///C:/Users/Alain/Desktop/py_multi_treeview.PNG

as you can see, this is pinned mode, in multi treeview, i got two, but it could be more
i'm surpised, because this is the first time in quite 10year now that i fall on this faculty

my used was to only got one windows whatever pinned or not pinned... modality wich seem to not exist no more ??? one widows with Tabs in unpinned mode, and noTabs and many windows treview in pinned mode... nice with two treewiew, but uncomfy with more... where tabs are easier to use in this case...

**Comment by Quetzaal** [comment]
as you can see, this is pinned mode, in multi treeview, i got two, but it could be more
i'm surpised, because this is the first time in quite 10year now that i fall on this faculty

my used was to only got one windows whatever pinned or not pinned... modality wich seem to not exist no more ??? one widows with Tabs in unpinned mode, and noTabs and many windows treview in pinned mode... nice with two treewiew, but uncomfy with more... where tabs are easier to use in this case...

**Comment by Quetzaal** [comment]
as you can see, this is pinned mode, in multi treeview, i got two, but it could be more
i'm surpised, because this is the first time in quite 10year now that i fall on this faculty
https://s22.postimg.cc/6im82r99t/py_multi_treeview.png

(sorry for the image, but the github way seems to be a few fancy for me)
my used was to only got one windows whatever pinned or not pinned... modality wich seem to not exist no more ??? one widows with Tabs in unpinned mode, and noTabs and many windows treview in pinned mode... nice with two treewiew, but uncomfy with more... where tabs are easier to use in this case...

**Comment by Quetzaal** [comment]
PS: i used pyscripter 3.4.1 (downloaded yesterday) but still got a 2.6 version somewhere

**Comment by pyscripter** [comment]
You can always go back to the default layout by using the menu option View, Layouts, Default.
You can dock one view inside another (tabbed layout) by drag-and-dock.  Just drag one window over another and drop it in the middle.
