### ISSUE TITLE
Unable to locate file in Pyscripter

### ISSUE THREAD

**Issue by drpreeti3628** [pyscripter/pyscripter#888]
I have installed Python 3.5.4 and 3.4.1 Pyscripter.

I am able to open a file via command line prompt of python but the same code says file not found in Pyscripter. Pyscripter has been linked to the Python environment

**Comment by pyscripter** [comment]
This is an incomplete description but I guess you are doing something like:
```
with open('xyz.txt'):
    dosomething
```
and when you do that from python it works and from the PyScripter prompt it doesn't.


Is this the case?   Please provide a better description of the problem.

You would need to specify the full path to your file.  The current directory may be different when you use the python prompt and when you use PyScripter.

**Comment by drpreeti3628** [comment]
Thanks for the reply. Yes my problem is same I am trying to open a file stored in my local drive with following command 
with open('xyz.txt','r'):
    dosomething

it works in python but does not work from PyScripter. As suggested by you gave full path albeit with \\ it worked.
 Thank you so much

**Comment by drpreeti3628** [comment]
Sorry with \\ it worked
