### ISSUE TITLE
using command line parameters sometimes adds an empty string to the end of argv

### ISSUE THREAD

**Issue by jodyhey** [pyscripter/pyscripter#889]
finding that using the command line parameters form under the run menu causes an empty string to be added to the end of  argv 
e.g. with this string in the command line parameters form 
"sim2_argseed_11_mutseed_33.vcf --map sim2_map.txt --mut 1e-6 --t0 --region-mode --t0 --force --outest r3"

then 
def main(argv):
    argv[-1] == ''   is true

**Comment by pyscripter** [comment]
This would happen if there is a space at the end of the command line parameters string.   
I am now trimming the string before parsing it.  i.e. spaces at the end would have no effect.
