### ISSUE TITLE
User defined key stroke not work in the pre-opened file when pyscripter launch

### ISSUE THREAD

**Issue by tapdo** [pyscripter/pyscripter#890]
The key strokes I defined not work only in the file opened automatically in pyscripter launching.
In the file opened after stating pyscripter, it's work and no problem.
And this issue is only editor window, interpreter window is worked.

**Comment by pyscripter** [comment]
Which version of PyScripter are you using?

**Comment by pyscripter** [comment]
Fixed in version conrol.
