### ISSUE TITLE
Get underlying C code standard out to PyScripters console

### ISSUE THREAD

**Issue by TotteKarlsson** [pyscripter/pyscripter#891]
I'm using various python modules, using underlying C/C++. The C/C++ code have log statements that can be redirected to stdout or stderr, etc. When this code is executed in PyScripter, such log messages are not visible. When running standalone Python, they are.

It would be great to allow a user to setup the streams in order to get output to the console, as it would help debugging of C/C++ code greatly. Not sure how that could be done though??

-tk

**Comment by pyscripter** [comment]
Implemented in version control.
