### ISSUE TITLE
Code Folding and Word Wrap settings do not save

### ISSUE THREAD

**Issue by JRosh33** [pyscripter/pyscripter#892]
Code Folding is always enabled when opening the program, despite disabling it. Also, word wrap is never enabled from launch, despite enabling it in the options.

Thanks!

**Comment by pyscripter** [comment]
If you right-click in the Editor and uncheck code-folding, this only affects the current file.  The choice is persisted, so if you close and reopen PyScripter it will remember that the specific file should not have code folding.

There is an IDE option (Tools, Options, IDE Options) that controls what happens with new files. Under Editor you will see an option "Code folding enabled by default".  If you uncheck it files you open or you create will not have code folding.

Finally, word-wrap is not compatible with code folding.   If you want to set word wrap first disable code folding for the specific file and then specify the word-wrap editor option.
