### ISSUE TITLE
Code folded is unfolded after run

### ISSUE THREAD

**Issue by papin1** [pyscripter/pyscripter#894]
Steps to repeat:
1. Fold several classes and functions
2. Run code
All code is unfolded, losing all benefits of code folding.

Pyscripter 3.4.1. portable on Win7x32

**Comment by pyscripter** [comment]
I can not reproduce here.   I run a script with folded sections and folding is preserved.   Code is unfolded only when you debug and the program stops in in a statement with a breakpoint inside a folded region.

Can you post a simple script with specific instructions for reproducing the issue please.

**Comment by pyscripter** [comment]
No feedback.  I am closing the issue, but you can reopen it if you  provide a reproducible case.
