### ISSUE TITLE
Unable to dock on the right side

### ISSUE THREAD

**Issue by papin1** [pyscripter/pyscripter#895]
With version Pyscripter version 2.6 I could manage (but it wasn't straightforward) to dock the interpreter and debug windows on the right side instead of the bottom of the main window.

I cannot to the same with the new version 3.4.1. Am I missing something or it is impossible ?

Thanks for an answer and/or help.

**Comment by pyscripter** [comment]
I cannot reproduce here.   PyScripter uses drag and dock.  You can drag any IDE window either from the title bar if it is docked on its own, or from the tab if it is docked in tab set with other windows.   You get visual hints as you drag about the new docked position if you drop the window.

**Comment by EEJoshua** [comment]
I have the same problem on the latest version
Variables window cannot be docked on left/right sides, can be docked on upper/lower side.
All other windows (file explorer, output, breakpoints, watches, call stack, python interpreter, messages) can be docked on all 4 sides with no problem.
I'm using a main 2560x1440 monitor with a secondary 1920x1080 reverse portrait. Same problem on both screens

**Comment by pyscripter** [comment]
Regarding the variables window, this was by design.  The window requires a lot of horizontal space, so it was deemed not very functional to dock it left or right.
