### ISSUE TITLE
Search highlighting not preserved when some code is folded.

### ISSUE THREAD

**Issue by laszlo-nandor** [pyscripter/pyscripter#896]
The syntax highlighting stops working correctly when some random code is folded, for example:

![image](https://user-images.githubusercontent.com/41633900/43141225-b2f244b0-8f55-11e8-9723-771eb4692a7a.png)

**Comment by pyscripter** [comment]
This is not syntax highlighting but search highlighting.   Issue title changed.

**Comment by pyscripter** [comment]
Fixed in version control.
