### ISSUE TITLE
message window stay blocked opened

### ISSUE THREAD

**Issue by Quetzaal** [pyscripter/pyscripter#897]
well, this window was already a few ennoying... but now after somes code, it's last funny way is to not disapear and to beautifully stay on-top on everything... 

certainly nothing, whatever i have to close/open pyscripter to unblock the situation...

then, should it not be the good moment to add a kind of "disable the message window" or "please, do not opened the message window for all and anything" option ??

thanks a lot Mr.Kiriakos... 

PS: i do this message because i'm to the point of reinstall all and see if comes better...

**Comment by pyscripter** [comment]
Could you please specify which window you are referring to?  A screenshot would be helpful.

**Comment by Quetzaal** [comment]
yes, i see what you say... but as i said in the message upper, i was at the point to reinstall pyscripter, python and other annex features...
all goes well now... its turning on win10 64x and it's the last version of pyscripter(3.4.1.0) but in x86 ??? not in x64(it surprise me, but... may the old used to only download x86 version) 
(it's the first time that it happened) but still and sometime i got a message error when lauching pyscripter?? (py can't be loaded, if i remember well, caus of an exception occurs(somewhere) (it's an usual error) but today do not prevent pyscripter to be correctly lauched... (then who cares ;o) )
