### ISSUE TITLE
Invisible text in popup balloon when using the 'radiant' stlyle.

### ISSUE THREAD

**Issue by laszlo-nandor** [pyscripter/pyscripter#898]
When using the radiant style, the popup help balloon has some invisible text, probably due to using the same foreground text color as the background.
Compared with another style for reference:

![image](https://user-images.githubusercontent.com/41633900/43579704-42e05072-9653-11e8-95a0-b48328544ac7.png)

**Comment by pyscripter** [comment]
Fixed in version control.
