### ISSUE TITLE
PyScripter - application error

### ISSUE THREAD

**Issue by sidsal** [pyscripter/pyscripter#900]
I am getting this error on launching PyScripter. 
Access violation at address 005CFDCF in module 'PyScripter.exe'. Read of address 00000288.
Exception class: EAccessViolation
Exception message: Access violation at address 005CFDCF in module 'PyScripter.exe'. Read of address 00000288.
Exception address: 005CFDCF
------------------------------------------------------------------------------
PyScripter version : 3.4.1.0 x86
Python DLL : python27.dll
Python Engine : peRemote

**Comment by pyscripter** [comment]
I am closing this since it does not provide sufficient information to address this issue.  Will reopen once additional information is provided.
