### ISSUE TITLE
[suggestion] Add link to Fossil SCM

### ISSUE THREAD

**Issue by Shohreh** [pyscripter/pyscripter#902]
This is not a bug, just a suggestion: Provide a way to use Fossil for source control.

It's a server-less, open-source, single EXE so is 1) very easy to install and 2) certainly good enough for a single user. It'd be an easy way to add source control to PyScripter.

My $0.20

--
Edit: Is there a way so that a tool uses the directory of the currently opened Python script as the work directory?

![db553280-0ed4-42e7-a2ad-12d1ddd1e3ba](https://user-images.githubusercontent.com/1541861/44517370-cb0b0580-a6c7-11e8-9c92-b939e4f116a4.png)

--
Edit: Found it by checking how "Command Prompt" was configured. Use "$[ActiveDoc-Dir]" instead.

**Comment by pyscripter** [comment]
PyScripter offers support for GIT and SVN via TortoiseGIT and TortoiseSVN.  These are nicely integrated with PyScrpipter's file explorer.   I am not planning to implement any other version control system.

By the way you can have the full list of parameters and modifiers such as $[$[ActiveDoc-Dir] by selecting Help, PyScripter, Parameters
