### ISSUE TITLE
[suggestion] Add a "Console" tab to run OS commands

### ISSUE THREAD

**Issue by Shohreh** [pyscripter/pyscripter#904]
Hello,

As a suggestion, I think it'd be useful if the app had a Console tab at the bottom so the user could type commands to interact with the OS.

![d4851361-b3bb-404b-b351-553d2e2c9527](https://user-images.githubusercontent.com/1541861/44618939-cab56a80-a87f-11e8-98a4-1c9ebe3635cb.png)

Cheers,

**Comment by pyscripter** [comment]
No need for a new window.
Added support for executing system commands in the interpreter with ! as in IPython.
e.g.
>>> !dir
Supports parameter substitution.
