### ISSUE TITLE
Multiple instances of pyscripter

### ISSUE THREAD

**Issue by ManPython** [pyscripter/pyscripter#908]
I realy need sometimes to run clones and diffrent instances of pyscripter eg 2 with python27 ot one with py27 and second with py36 but can't do this.
Is possible to solve this?

**Comment by pyscripter** [comment]
From the Help file - Command-line options topic

--NEWINSTANCE or -N

If set a newinstance of Pyscripter is started.  This to prevent the default behaviour which is to activate an existing instance of PyScripter is one is running.
