### ISSUE TITLE
Shortcut for "unindent block" becomes None after restart

### ISSUE THREAD

**Issue by sk-Prime** [pyscripter/pyscripter#912]
1. i set ctrl+shift+, as shortcut for "unindent block" (actually shift+, = <)
2. but when i restart pyscripter after closing it, the shortcut become None.
3. all other shortcut is working except it.
---
maybe pyscripter is not saving it.
![screenshot](https://user-images.githubusercontent.com/26684644/47891366-f3646c80-de8d-11e8-8adf-7ac745733f93.png)

**Comment by pyscripter** [comment]
Cannot reproduce here.  I can set the shortcut of this command to Shift +Ctrl+, and it stays after restarting.  Anything special about the keyboard?

However please note that you can Indent/Unindent code with Tab/Shft Tab.   So you do not need to set a shortcut for this command.

**Comment by sk-Prime** [comment]
oh, yes, tab/shift tab is better.
but i double check about unindent block shortcut assignation, still value becomes none. maybe something wrong in my pc. thank you
