### ISSUE TITLE
[Suggestion] show variables value in tooltip

### ISSUE THREAD

**Issue by sk-Prime** [pyscripter/pyscripter#913]
here, this code will produce this "TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int'" error. because 3rd element of the list is 'p' which is not a number.

![sample code](https://user-images.githubusercontent.com/26684644/47959909-8b975880-e02a-11e8-8a59-3561a5500259.png)
------
this is run-time scenario, error has indicated successfully with red-line. but my suggestion is, it will be good for debugging if the tooltip show the value of that variable alongside those information.

![runtime](https://user-images.githubusercontent.com/26684644/47959933-2f810400-e02b-11e8-9f63-7a2b4ace93bc.png)
------
in wing ide they have this feature. for example look at the image below

![wing ide number value](https://user-images.githubusercontent.com/26684644/47959958-29d7ee00-e02c-11e8-9863-b3b87c937337.png)

they also show other values too, data list also showed in tooltip. if the list is huge, it shows deprecated version of that list.

![wing ide list](https://user-images.githubusercontent.com/26684644/47959973-8509e080-e02c-11e8-90bb-1e4600e0bf07.png)

i hope this will dramatically improve debugging process of pyscripter.

**Comment by pyscripter** [comment]
PyScripter does the same.  During debugging it also shows the value of the variable at the bottom of the hint.
- Put a breakpoint at line 4.  
- Press F9.  
- Try the hints

Am I missing something?

**Comment by sk-Prime** [comment]
in debugging mode, it is obvious and it shows the value in tooltip as like you said.
but if the list is huge then it will be difficult to know the value. it will be time consuming to check the value by using pause/continue.

so my suggestions are
1. Introducing an option in debug menu, this option act like debugger but continue to execute the program until error occur. so we don't need to press f9 all the time and we can see the value which is causing the error.

2. no need any extra option, implementing the function in 'Run' command. if any error occur it will trigger the function and take snapshot of entire program and variables. so we can see all the values of that particular moment by hovering cursor over variables.

**Comment by pyscripter** [comment]
Run, Post Mortem does exactly that.   If an error is occurred it restores the state at which the error has occurred and you can all the above.

**Comment by pyscripter** [comment]
There is also an IDE option to automatically do Post Mortem on exception.

**Comment by sk-Prime** [comment]
so far, Pyscripter is awesome, lightweight and fully featured as commercial ide available in market. one question is why pyscripter is not available for linux?

**Comment by pyscripter** [comment]
I am afraid not.  However the next version will allow you to remotely run/debug scripts running on Linux machines.  See the PyScripter blog  https://pyscripter.blogspot.com/
