### ISSUE TITLE
PyScripter 2.6.0 not working

### ISSUE THREAD

**Issue by thomasbalstroem** [pyscripter/pyscripter#915]
Hi,
My PyScripter 2.6.0 (32 bit) installation on Win10 doesn't work properly. 
The environment looks okay from a first glance where the Interactive Window says: 
*** Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32. ***
*** Remote Python engine  is active ***
Meanwhile, when executing an import statement in the Interpreter Window nothing happens. 
Also, I can load an existing script, but can't insert new lines into it.
Please assist.
Kind regards, Thomas Balstrøm

**Comment by pyscripter** [comment]
The version you are using is ancient.  PyScripter has been updated to version 3.4.  You can download compiled version 3.4.2 from https://sourceforge.net/projects/pyscripter/files/.  See also https://pyscripter.blogspot.gr/.
