### ISSUE TITLE
pyscripter x64 can't see Conda 3.7 python installation after installing SDK7.1

### ISSUE THREAD

**Issue by bouziot** [pyscripter/pyscripter#923]
I have a Win 10 x64 system with PyScripter v3.5.1-x64 and a conda 3.7 python distribution installed in it. Everything was working properly until I installed Microsoft SDK7.1 in order to be able to compile some older programs. Before installing it, I removed the C++ 2010 x86/x64 Redistributable, as they would be installed over again with SDK and I needed the version provided by SDK7.1. The installation went fine, but now PyScripter can't 'see' the conda distribution anymore. 

![image](https://user-images.githubusercontent.com/45633556/49881160-f90a8600-fe2d-11e8-9152-924d2eda579b.png)

The funny thing is that once you click 'OK' the conda 3.7 python version comes up as registered, but still cannot be seen or activated.

![image](https://user-images.githubusercontent.com/45633556/49880793-2e62a400-fe2d-11e8-80b8-e081a978c490.png)

 I have also tried adding it as an unregistered version but if I try to activate it I end up with the same error (see the picture below). Note that the python command line and folder opens without problems from relevant icons in the Python Versions window.

![image](https://user-images.githubusercontent.com/45633556/49881283-425ad580-fe2e-11e8-8c56-fe30e43eb38a.png)

Other remarks: 
- These problems persist if I run as administrator. 
- The conda distribution hasn't been affected and other IDEs (e.g. Jupyter Notebook and Spyder) run and see python fine.
- A clean reinstall of both Anaconda and Pyscripter haven't resolved the issue.
- I have tried the same steps in another computer (Win10 x64 as well) and the problem appeared there as well, i.e. it's not bound to the specific system.
- I have tried placing `.bat` files in the directory of pyscripter.exe but this hasn't solved the problem

**Comment by pyscripter** [comment]
Please see https://github.com/pyscripter/python4delphi/wiki/P4DPython26
PyScripter is using a similar manifest file.  This was introduced a long time ago to allow working with Python 2.6 2.7 and 3.1.  I am not sure this is needed with recent versions of python but after some research I found the following in http://www.py2exe.org/index.cgi/Tutorial

>  Python 2.6, 2.7, 3.0, 3.1
> For Python 2.6, the DLL you need is called MSVCR90.dll. Py2exe is not able to automatically include this DLL in your dist directory, so you must provide it yourself. 
> To complicate things, there is more than one version of this DLL in existance, each with the same filename. You need the same version that the Python interpreter was compiled with, which is version 9.0.21022.8. Through the remainder of these instructions, hover your mouse over the dll file (or the vcredist_x86.exe installer executable) to confirm which version you've got. You'll need the vcredist_x86.exe that contains the [Microsoft Visual C++ 2008 Redistributable Package](https://www.microsoft.com/en-us/download/details.aspx?id=29) published 29-11-2007, so not the VS2008 SP1 one (tested with Python 2.7.1). 

You have probably unistalled this DLL, so could you please try to reinstall it using the above Redistributable Package link?  It will not do any harm since it is a side-by-side assembly and it does not affect the installation of newer versions of the same dll.

**Comment by pyscripter** [comment]
To be on the safe side and since you are in Win64 you can try installing the following as well:
https://www.microsoft.com/en-us/download/details.aspx?id=15336
Again it does not do any harm since it a side-by-side installation and can safely coexist with other versions of the same file.  It does not overwrite existing versions newer or older.

**Comment by bouziot** [comment]
Thanks for the swift reply Kyriakos!

I have tried to reinstall the distributables, including the links that you provided, but this also didn't help. I also think it's a missing dll issue; also some drivers can't find their own dlls now in C:/Windows/System32.

I have also tried cleaning up the Registry after the reinstallations but that also didn't help. I will try some other workarounds as well because I'm now used to working with Pyscripter and I'd really like to have it as my IDE over other things.

**Comment by pyscripter** [comment]
I have done some work to ensure compatibility of PyScripter with Anaconda.  Please replace the PyScripter.exe file with the one residing in this [zip file](https://drive.google.com/file/d/1ZP21N0mLfmyCnFXvWLUhMFZWvDcveCCD/view?usp=sharing) and report whether it works.  See also my [blog post](https://pyscripter.blogspot.com/2019/07/pyscripter-and-anaconda.html) on this issue.

**Comment by bouziot** [comment]
Ευχαριστώ πολύ για τη βοήθεια Κυριάκο!

I have since then solved the issue* by fully removing Python 3.7 and reverting to an Anaconda Python 3.6 distribution, which PyScripter is able to see without any issues. I will however test your solution as well and let you know!

*I have reverted to a previous Python version also due to some library dependency issues.

**Comment by pyscripter** [comment]
PyScripter 3.6.1 should work with Anaconda in a much smoother way.
