### ISSUE TITLE
Installer (Inno Setup) improvements

### ISSUE THREAD

**Issue by bovirus** [pyscripter/pyscripter#926]
@pyscripter 

Please if you can update Inno Setup iinstallrr to a recent version.

Current used by you: 5.5.7
Latest available. 5.6.1

For Italian language please update the Italian language got from here

https://mega.nz/#!ycRixSoL!h4Kq9ZbinLcRb0GKDo7xcUXuftCKia61rsLT-Bz2FbQ

I sent an email with some feedback. Please check it.

Thanks.

**Comment by pyscripter** [comment]
I have installed Inno Setup 5.6.1.  The next release will use that.   Does this provide automatic translations of the installer UI?  Do I need to do something?

**Comment by pyscripter** [comment]
Regarding the Italian translation, could you sync it with  Transifex?  Altenatively I can make the change directly in the PyScripter master?

**Comment by bovirus** [comment]
@pyscripter 

Inno Setup 5.6.1 use the latest translation for standard UI.

Of course you need always the changes that I pulled about the additional struing/icon description in your application.

**Comment by pyscripter** [comment]
@bovirus Yes sure thanks.
