### ISSUE TITLE
Translation - Language template with empty line

### ISSUE THREAD

**Issue by bovirus** [pyscripter/pyscripter#927]
@pyscripter 

The language template seems to have an empty line (empty for source text).

Could you please check?

Thanks.

**Comment by pyscripter** [comment]
I have added " " to ignore.po and updated the default.pot.   This should take care of it.

**Comment by pyscripter** [comment]
Yes that is what I added to ignore.po.  If you look at defaut.pot in the master branch is should not contain this string.
