### ISSUE TITLE
pyscripter with anaconda 2018.12

### ISSUE THREAD

**Issue by LouisLamarche** [pyscripter/pyscripter#938]
I am using pyscipter and anaconda for years. When I installed the new version of Anaconda 2018.12, pyscripter does not work. It opens and then disapears. It does the same for all my students either on Windows 7 or 10.

**Comment by pyscripter** [comment]
Python 2 or Python 3?

**Comment by pyscripter** [comment]
Just tried Miniconda latest with Python 3.7 64 bits.   Installation for current user and not registered as default Python.
In Run, Python Versions, Setup Python Versions...  I added a new  unregistered python version be selecting the installation directory of Miniconda.
Works fine.

**Comment by pyscripter** [comment]
Please provide some more info.

**Comment by fizban99** [comment]
Same issue here. Installed Anaconda x64 on Windows 10. Then, installed pyscripter 3.7.
Pyscripter starts and then disappears. Solved using a batch file:
```
SET PYTHONHOME=<path to anaconda>
start PyScripter --PYTHON36 --PYTHONDLLPATH "<path to anaconda>" 
```
 Pyscripter will start fine, but remote engine does not start and it switches automatically to internal engine (hidden by default). Solved by going to Tools-Options-IDE Options-Python Interpreter-Always use sockets.

**Comment by morxs** [comment]
> 
> 
> Python 2 or Python 3?
> 32bits or 64 bits?
> Miniconda or Full Anaconda?
> Registered or not? For All users or for current user (install option)?

Hi, 

I also getting this issue, pyscripter 3.6 (64 bit), python 3.7 (64 bit), Miniconda 3, for current user, registered as default python.

Try to what @fizban99 suggest and it works.

```
SET PYTHONHOME=C:\Users\xxx\Miniconda3
"C:\Program Files\PyScripter\PyScripter.exe" --PYTHON37 --PYTHONDLLPATH "C:\Users\xxx\Miniconda3" 
```

**Comment by pyscripter** [comment]
"Always Use Sockets" IDE option defauts to True to avoid this issue..
