### ISSUE TITLE
Formatting problem for functions with a very long list of parameters

### ISSUE THREAD

**Issue by Talinf** [pyscripter/pyscripter#939]
In code editing, when displaying the docstring of a function with many many parameters, the first line containing the parameters is truncated at both ends and the docstring is placed off screen.

The functions in the package pysimplegui could be used as an example of this behavior.

**Comment by pyscripter** [comment]
Thx for the report. Is it possible to provide a screenshot?

**Comment by Talinf** [comment]
When creating the screen shot, I observed that I was on my secondary screen (to the left of the main screen). I try to reproduce on the main screen, and now I could see the docstring but not the end of the parameter list. See the enclosed screen shots. First one from the secondary screen, 
second one from the main screen (by dragging pyscripter from one screen to the other).

![secondaryscreen](https://user-images.githubusercontent.com/6250474/51938674-ac7a0a80-23db-11e9-88d7-648e17bfc0d4.png)

![mainscreen](https://user-images.githubusercontent.com/6250474/51938698-bdc31700-23db-11e9-9cd5-a518b5109d0c.png)

**Comment by pyscripter** [comment]
Thx.  I will look into it.  By the way nice syntax color theme.  Which one is it?

**Comment by pyscripter** [comment]
The signature window does not overflow now to the left or the right.
