### ISSUE TITLE
Pyscripter and ArcGIS Pro not activating

### ISSUE THREAD

**Issue by morgangrundy** [pyscripter/pyscripter#940]
Hi, I seem to be having a similar issue to number #881. I followed the instructions on your blog post https://pyscripter.blogspot.com/2018/10/using-pyscripter-with-arcgis-pro.html but I am still having issues. I have a new install of ArcGIS Pro 2.3. I cloned my python environment and it is located at C:\Users\Morgan\AppData\Local\ESRI\conda\envs\geog378. I press the test button in pyscripter's Python Versions dialog and it opens python in a command prompt. I press activate and I get the Pyscripter could not load a python engine error. 
Pyscripter version 3.6.0.0 x64
windows 10 x64
arcGIS Pro 2.3
Python 3.6.6 x64
Any ideas? 
Thanks so much for a great IDE!

**Comment by pyscripter** [comment]
What do you mean by "cloned my python environment".  Used venv, virtualenv, conda?  From the directory I can tell this is a conda environment. 
Does this directory contain both pythonxx.dll and python.exe?
Does pyscripter work with the original Argis Pro installation?
Are there any Windows environment variables set?  (e.g. PYTHONHOME, PYTHONPATH)?

**Comment by morgangrundy** [comment]
Sorry I wasn't clear. ArcGIS Pro now comes with a python package manager.
You are prevented from adding packages to the core python so you have to
clone your environment and it is stored in the path I posted. That folder
contains a full copy of the Pro python install including python36.dll and
python.exe.
I could not get pyscripter working with the original ArcGIS Pro
installation ether.
Following our ideas in the other post I ran a >set a the command
prompt. PYTHONHOME,
PYTHONPATH are not in the environment settings.
I really appreciate the quick response!

**Comment by pyscripter** [comment]
When you start PyScripter does it load any Python version or it fails at this stage?

**Comment by morgangrundy** [comment]
It fails on startup. I get the error right away.

**Comment by morgangrundy** [comment]
I tried starting pysctipter from the command line using
pyscripter --PYTHONDLLPATH C:\Users\Morgan\AppData\Local\ESRI\conda\envs\geog378
It launches but I still get the error message and the pop up to activate python. I see my install of python in the unregistered versions, but now the activate button is not there. It's blacked out.
I appreciate your help with this. Looking through the issues on this thread it seems that ArcGIS is installing python in such a way as to make it hard for pyscripter to use.

**Comment by pyscripter** [comment]
Unfortunately, I do not have ArcGIS Pro installed and I have used my free trial.  I have posted a {message}[https://groups.google.com/forum/#!topic/pyscripter/S4fMNXQV3g0] at the news group to see if other users have similar experiences.

**Comment by morgangrundy** [comment]
I completely uninstalled ArcGIS Desktop 10.6.1 including all the registry keys and now PyScripter works with the python that ArcGIS Pro installed. No idea what the issue was but it seems you can't have both ArcGIS programs installed and use PyScripter. Thanks for looking into this issue.

**Comment by pyscripter** [comment]
Great to hear that you find a solution.  Does Pyscripter work with the conda envs that ArrGIS Pro creates?
Puzzling why the ArcGIS Desktop interferes with PyScripter.

**Comment by morgangrundy** [comment]
Yes, it seems to be working fine. I have access to all the libraries that
ArcGIS pro installed. No idea why desktop interferes with pro’s python.

**Comment by pyscripter** [comment]
I just came across [this link] (https://community.esri.com/docs/DOC-8359) that talks about folder permission issues with ArcGIS Pro.  Maybe running PyScripter as Administrator could help.
