### ISSUE TITLE
Pyscripter could not connect to the remote Python engine server

### ISSUE THREAD

**Issue by duyduc27** [pyscripter/pyscripter#944]
At first, I used pyscripter 3.5 version. But It was frequently hanging. So I reinstalled the most current version (3.6 x 64) and then it keep saying "Could not connect to the remote Python engine server. The remote..."
My python version: 3.7.0 x 64, My OS system: win 7 ultimate x64 SP 1
[https://i.imgur.com/b0W78h7.png](url)

**Comment by pyscripter** [comment]
Do you have pywin32 installed?  For instance does import pywintypes work?

**Comment by duyduc27** [comment]
I don't know if pywin32 was installed. But I can do "import pywintypes"

**Comment by duyduc27** [comment]
Updated: I have removed Anaconda then set new path to Python. And it work properly now..

**Comment by pyscripter** [comment]
It sounds like an installation conflict issue.

**Comment by Ciber-SLasH** [comment]
Similar error: Remote Server is not connected.
RPyC package install, but problem not solved.

**Comment by Ciber-SLasH** [comment]
PyScripter: 4.1.1.0 x64
Python: 3.8.1

**Comment by pyscripter** [comment]
- I take it your python is 64 bits.   
- Which python distribution are using?  Does it come from python.org?
- Does the python directory contain python38.dll?  
- Go to Tools, Options, IDE Options, Python Interpreter.  Is "Always use sockets" checked?

**Comment by Ciber-SLasH** [comment]
Python 64 bit from python.org, contain python38.dll.
IDE Options \ Python Interpreter \ Is "Always use sockets" checked: yes
>> Is your computer under strict firewall policy not allowing local sockets?
PyScripter run from VMware Workstation 7.1.4 with configure: Network Adapter \ NAT.

**Comment by Ciber-SLasH** [comment]
It work, I run Sphinx Windows8 Firеwall Control and allow all for python.exe and pyscripter.exe.
Thanks!

**Comment by oreg-bandi** [comment]
I checked all the tips above and I get the message "Could not connect to the remote Python engine server. The remote interpreter and debugger is not available." when I try to set the remote engine to wx. My configuration is Anaconda with Pyscripter 4.1.1.0.x64. Couldn't we make life easier if we would have a simple Python script that checks what is needed and we would run it from Pyscripter?

**Comment by Shohreh** [comment]
I have the same issur after upgrading to the latest and greatest (4.1.1.0) on a 32-bit Windows host. The previous version (3.x) worked OK.

Python 3.8.

Closed, re-started app: Still NOK.
Re-initialized engine: Still NOK.

**Comment by retsyo** [comment]
on my windows 10 64bits, after I set the unregistered python's path, I can debug in both PyScripter-3.6.4-x64 and PyScripter-4.0.0-x64 without problem.

however PyScripter4.1.1.0-x64 will say 'Remote Server is not connected. Please reinitialize or disconnect the remote interpreter.' On the same time, 'python interpreter' window shows that python has finished reinitialization, which is so strange.
```
*** Python 3.6.10 |Anaconda custom (64-bit)| (default, Jan  7 2020, 15:18:16) [MSC v.1916 64 bit (AMD64)] on win32. ***
*** Remote Python engine is active ***
>>> 
*** Remote Interpreter Reinitialized ***
[Dbg]>>> 
[Dbg]>>> 
[Dbg]>>> 
>>> 
*** Remote Interpreter Reinitialized ***
>>> 
*** Remote Interpreter Reinitialized ***
[Dbg]>>> 
```

**Comment by retsyo** [comment]
same here
PyScripter-3.6.4-x64 and PyScripter-4.0.0-x64 work fine on my windows

howveer PyScripter-4.1.1.0-x64 says "Pyscripter could not connect to the remote Python engine server"

**Comment by tellts** [comment]
I have the same error too.
Python 4.1.1.0 x64
Windows 10
`name = input(str('Input name')) # Ввод имени
print('Hello, ', name) # Вывод приветствия
# comment

#print('Hello')`
