### ISSUE TITLE
 SynCodeCompletion.OnCodeItemInfo

### ISSUE THREAD

**Issue by chuanshan68** [pyscripter/pyscripter#945]
In frmPythonII.pas  FormCreate: 
 SynCodeCompletion.OnCodeItemInfo := SynCodeCompletionCodeItemInfo;
but TSynCodeCompletion have no such event

**Comment by pyscripter** [comment]
It does in the version of SynCompletionProposalincluding in PyScripter 
https://github.com/pyscripter/pyscripter/blob/master/Source/SynCompletionProposal.pas
