### ISSUE TITLE
remote (SSH) debugging can't import a local .py file in the same folder where debugged file is

### ISSUE THREAD

**Issue by ThetaGHun** [pyscripter/pyscripter#947]
I do have a pretty complex remote file to import at startup.

After I started debugging, the python through SSH wasn't able to import (see) those file to be imported. It is a local file, not a standard library or anything similar.
(Btw, that file imports a lot of other files too. E.g. Selenium.)

The error message is this: ImportError: No module named XFS
(XFS.py is in the same folder as the debugged file.)

**Comment by pyscripter** [comment]
Are you SSHing to Linux or Windows?  Are you using OpenSSH or putty?

**Comment by pyscripter** [comment]
The file would need to be on the python path or the current directory.

**Comment by pyscripter** [comment]
I am closing this issue since there is not much info and no feedback.

**Comment by ThetaGHun** [comment]
O.K. No problem. I didn't use it due to that error (it can't import certain
modules).

Anyway the error still exists in the system and if someone wants to debug
remotely, it won't work. However, running it locally in PyScripter is still
working.

(In a few months, I'll make a Paypal payment for you for PyScripter. At the
moment, more urgent items are in the way, one is 10+ years old.)
