### ISSUE TITLE
logging.debug() too slow

### ISSUE THREAD

**Issue by ololoe** [pyscripter/pyscripter#948]
logging.debug() is much slower than print. This doesn't occur if I start program outside of pyscripter.

**Comment by TotteKarlsson** [comment]
I have the same problem. Thanks.

**Comment by pyscripter** [comment]
The problem was that logging calls flush on the error stream (sys.stderr) after each message, and this slowed down things with the remote interpreter.

**Comment by ololoe** [comment]
So is it fixed? In what version?

**Comment by pyscripter** [comment]
Fixed in version control.  Not released yet.

**Comment by ololoe** [comment]
Please tell me when it's released. Do you have something like release email subscription with "whats new"?
