### ISSUE TITLE
Awaiting input blocks debugger

### ISSUE THREAD

**Issue by ololoe** [pyscripter/pyscripter#950]
I have a program with 2 threads, one awaits input() in endless loop. I can't debug second thread because of input window.

**Comment by pyscripter** [comment]
Could you please provide a simple script reproducing the problem?

**Comment by ololoe** [comment]
def readline_loop(wait_event):
        while True:
            input()
    
    
    def main():
        input_thread = threading.Thread(target=readline_loop)
        input_thread.daemon = True
        input_thread.start()
    
        # here comes the code
    
    if __name__ == '__main__':
        main()

**Comment by ololoe** [comment]
Why wontfix?
