### ISSUE TITLE
API documentation is not displayed for __init__

### ISSUE THREAD

**Issue by ololoe** [pyscripter/pyscripter#951]
If I point a mouse on a construct call, neither __init__ api doc nor even parameter list is displayed.

**Comment by pyscripter** [comment]
The parameter list is displayed when you type the constructor call.

e.g. with the following code:

```
class Celsius:
    """ Class for storing Celsius temperatures"""
    def __init__(self, temperature = 0):
        """Initialize Celsius instance"""
        self._temperature = temperature

    def to_fahrenheit(self):
        return (self.temperature * 1.8) + 32

    @property
    def temperature(self):
        print("Getting value")
        return self._temperature

    @temperature.setter
    def temperature(self, value):
        if value < -273:
            raise ValueError("Temperature below -273 is not possible")
        print("Setting value")
        self._temperature = value
```
When you type 
`c = Celsius(`

you get 
![image](https://user-images.githubusercontent.com/1311616/65824093-2e704b00-e26b-11e9-9341-a6f8cb16ce38.png)

So I am not sure what you are after.

**Comment by pyscripter** [comment]
Note that you can also invoke parameter completion when you press Shift+Ctrl+Space.

**Comment by ololoe** [comment]
IDE like Eclipse would display help if you point the mouse on `Celsius` in `Celsius()`

**Comment by pyscripter** [comment]
In the forthcoming version 4.1, code hints and completion will be provided by the JEDI language server, so you will get the same type of completion and hints as with other python IDEs.
