### ISSUE TITLE
The 'rpyc' package is not availble

### ISSUE THREAD

**Issue by amyclaire1976** [pyscripter/pyscripter#952]
I have just installed PyScripter and upon startup I get this error:

"The 'rpyc' package is not available.  Please restart PyScripter and try again.  If the error persists reinstall PyScripter."

I have restarted and reinstalled several times but I still get this error.  What do I do to get rid of this error?

**Comment by pyscripter** [comment]
Which version of PyScripter are you using?

**Comment by pyscripter** [comment]
I am closing this since there is very limited information provided and there is no response to the request for more information.
