### ISSUE TITLE
stop the execution of a program

### ISSUE THREAD

**Issue by suibaf** [pyscripter/pyscripter#954]
I'm testing a py file and I press EXECUTE. Then I want to stop the execution of the program?
how you do it?
If I press stop debug the program continue to work (a telegram bot)!
Only if I close pyscripter the program stop to work.
And in the last, whta is the difference Excuse and Debug?
BR

**Comment by pyscripter** [comment]
If nothing else works you can try to reinitialize the Remote Engine.  Run, Python Engine, Reinitialize.

**Comment by pyscripter** [comment]
I am closing this, since it is a question and not a proper bug report.
