### ISSUE TITLE
Problem with blue line when debugging

### ISSUE THREAD

**Issue by ocarillo** [pyscripter/pyscripter#955]
I am using python 3.7 64Bit on Windows 7 64 bit. When I run a script in debug mode and the code stops in the break point, the blue line dissapears when do something in Python Interpreter Tab. Then, if I scroll the script code to stop watching the debug line and scroll again to see the line, the blue line appears. 

Any solution to this?

Thank you

**Comment by pyscripter** [comment]
Fixed in version control.
