### ISSUE TITLE
Access violation on 64-bit Pyscripter

### ISSUE THREAD

**Issue by 0x5c3e** [pyscripter/pyscripter#956]
Access violation at address 00000000006D7AD8 in module 'PyScripter.exe'. Read of address 0000000000000468.

Currently using latest non-beta version of Pyscripter as of **14/06/2019** and using **Python 3.7.3**

**Comment by 0x5c3e** [comment]
Nevermind, to enable word wrap, code folding has to be turned off.

**Comment by pyscripter** [comment]
This is not a useful report.  Without any instructions for reproducing the error or at least the call stack at the time of access violation, there is not much I can do.
