### ISSUE TITLE
Cannot run Pyscripter

### ISSUE THREAD

**Issue by gitdrewgreen** [pyscripter/pyscripter#958]
I'm unable to run Pyscripter.  When I install  and launch it, I immediately get an error message that an unspecified problem has been encountered.  I tried reinstalling, but it didn't help.  I have read the readme files, and I have a 64 bit OS and a 3x version of Python.

**Comment by marshall-ucsd** [comment]
Just ran into the same issue when I installed Python 3.7.4 (previously on 3.6.8). I fixed the problem with this procedure - probably excessive, but it worked!

1. Uninstalled PyScripter.
2. In the AppData/Roaming folder, I renamed PyScripter to Pyscripter.old - configuration is a likely cause of the problem, renaming allows you to copy/paste stuff you want to keep into the new installation.
3. I then uninstalled all versions of Python, and ensured their folders were removed.
4. My PATH includes Python, so I cleaned that up as well.
5. Now my system is clean. I re-installed Python 3.7.4, then PyScripter 3.6.0 (both x64). Pyscripter now runs fine.

You might get away with just step 1 & 2 and re-install PyScripter, but this method does ensure you have a "clean" Python+PyScripter environment to work with.

You can use `pip --freeze > requirements.txt` before step 3 to save a list of your installed packages for re-installation.

**Comment by pyscripter** [comment]
I have done some work to ensure compatibility of PyScripter with Anaconda.  Please replace the PyScripter.exe file with the one residing in this [zip file](https://drive.google.com/file/d/1ZP21N0mLfmyCnFXvWLUhMFZWvDcveCCD/view?usp=sharing) and report whether it works.  See also my [blog post](https://pyscripter.blogspot.com/2019/07/pyscripter-and-anaconda.html) on this issue.

**Comment by pyscripter** [comment]
PyScripter 3.6.1 should work smoothly with Anaconda.  Please try and open a new issue if it is still a problem.
