### ISSUE TITLE
Cannot import local .py module/script in PyScripter 

### ISSUE THREAD

**Issue by Meg720** [pyscripter/pyscripter#959]
Hi again, 

I am trying to create modules in PyScripter and import them. I've looked over some of the related issues, and I couldn't find one that matched my problem. I did try restarting PyScripter. The files will open in Python. I tried saving the files in several different locations to see if that might make a difference, (I tried saving in: general c-drive, desktop, locale, and lib files, _pychache_, my user files, public, and general PyScripter). I cannot get any of them to work for PyScripter. I am hoping someone recognizes what I am doing wrong and can help.

I made a very simple example to illustrate my question. 

![help1](https://user-images.githubusercontent.com/51974025/61235811-5a683f80-a704-11e9-8604-643009409648.PNG)
![help2](https://user-images.githubusercontent.com/51974025/61235812-5a683f80-a704-11e9-9cda-5c373f694ee2.PNG)
![help3](https://user-images.githubusercontent.com/51974025/61235813-5a683f80-a704-11e9-959c-240cbd35342e.PNG)

Thank you for your help!

**Comment by pyscripter** [comment]
I see that you are trying to import testi from an unsaved module.
You need to save the second module in the same directory as the your testi module.  Then the import will work.
Alternatively your testi module needs to be on the python path.  To see your python path do
>>> import sys
>>> print sys.path
