### ISSUE TITLE
Python Interpreter Window, font color problem

### ISSUE THREAD

**Issue by ocarillo** [pyscripter/pyscripter#960]
I have noticed there is a problem when manually change font color (output item) in Python Interpreter Window. I set the color I want but It ignores the selection.

I have discovered that by manually editing the file Dafault.ini in Hightlighters directory in Pyscripter installation path, if I add the following lines, then It works (clLime is the color I wanted):

[Highlighters\Python Interpreter\OutputAttri]
Background=clNone
Foreground=clLime
Style=[]

I have selected DarkHighlight2 color theme, but I think the problem persists with other color themes.

Thank you for your amazing work.

**Comment by pyscripter** [comment]
Which  version of PyScripter are you using?

I cannot reproduce with PyScripter 3.6.1:
1. Right-click on the Interpreter Window.
2. Select Interpreter Editor Options..
3. In Tab Syntax Colors I select Output in Element list.
4. I type clLime or #00FF00 in the ForgroundColor ColorEdit box.
5. I click some other element for the color to be entered.
6.  Press the "OK" button.

The above steps changed the output color to Lime and is persisted when I exit and re-enter PyScripter.

**Comment by ocarillo** [comment]
I tested with several versions including the last one 3.6.1 and I always have the same problem. I open the program, change the Output item as you suggest, and the color of the output text remains unchanged. I took some captures to show the problem:

In picture one I change the color of the output and set to clLime (#00FF00)
In picture two, you can see that the color of the font remains in default color #008080 when type something
In picture three, I open the dialog again and the color doesn't remain in clLime, It has changed to the default color.

![image](https://user-images.githubusercontent.com/50459080/61687757-76329d80-ad23-11e9-8ca2-693d1a73fa14.png)

![image](https://user-images.githubusercontent.com/50459080/61687789-88144080-ad23-11e9-9c98-4d4b548dfbee.png)

![image](https://user-images.githubusercontent.com/50459080/61687815-9cf0d400-ad23-11e9-97b6-04949bd99265.png)

**Comment by pyscripter** [comment]
Are you doing step 5

> 5. Click some other element for the color to be entered.

before pressing OK?
