### ISSUE TITLE
Cannot connect to Remote Python

### ISSUE THREAD

**Issue by BobPalank** [pyscripter/pyscripter#965]
Running Win  10   + PyScripter 3.6.1 + Python 2.7.15
App starts , ends, and I repeat – all ok.
Cursor in Pyscripter starts blinking  then stops ====>  why?
Click on a literal :   Cursor moves and stops blinking again after 5 blinks.
I hit backspace to make change and Pyscripter aborts    .  code follows
=============================================
import wx
# import wx.Calendar             Running PyScripter 3.6.1
class Example(wx.Frame):
    def __init__(self, *args, **kwargs):
        super(Example, self).__init__(*args, **kwargs)
        self.InitUI()
    def InitUI(self):
        wx.CallLater(400, self.ShowMessage)
        self.SetSize((300, 200))
        self.SetTitle('Message Box B ')
        self.Centre()
    def ShowMessage(self):
        wx.MessageBox('Download completed 04', 'Text Change',
            wx.OK | wx.ICON_INFORMATION)
def main():
    app = wx.App()
    ex = Example(None)
    ex.Show()
    app.MainLoop()
if __name__ == '__main__':
   main()
========================================
Any suggestions?
TIA 
      Bob

**Comment by pyscripter** [comment]
Are you using the Remote interpreter?  (Run, Python Engine, Remote)?

**Comment by BobPalank** [comment]
No , I don't think so since  I see
Error  Could not connect to Remote Python Engine Server
I abort this dialog , display my code and click the green start icon..
My app will run any number of times if I make no code change
I also see
*** Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)] on win32. ***
*** Internal Python engine is active ***

**Comment by pyscripter** [comment]
Ok.  This explains the issues you are facing.  You should be using the Remote Python Engine, especially when working with GUI apps.  See the [Wiki page](https://github.com/pyscripter/pyscripter/wiki/RemoteEngines) for details.

The issue now is why the remote python engine fails to load.
- Which Python distribution are  you using?  Is it from www.python.org?
- Are there any firewall restrictions in your PC blocking local TCP/IP connections?
- If you go to Tools, Options, IDE Options, Python Interpreter, what is the value of "Always use sockets"?

**Comment by BobPalank** [comment]
“Which Python distribution are you using? Is it from www.python.org?”
Not sure, How would I check ?

Are there any firewall restrictions in your PC blocking local TCP/IP connections?
    Not sure how to check this.

Always use sockets  is true

Is there an older pyscripter  
version you might recommend ?
Bob

**Comment by pyscripter** [comment]
a) Python Version
```
>>>import sys
>>>print sys.version
```
Also check whether
>> import win32 
works

b) Firewall restrictions
Go to Control Panel\System and Security\Windows Defender Firewall\Customise Settings and make sure the "Notify me when Windows Defender blocks a new app" is checked. It is checked by default.

c)  Tools, Options, IDE Options, Python "Always use sockets"

**Comment by pyscripter** [comment]
No feedback.  So I am closing it.
