### ISSUE TITLE
'Search->Find References' does not work with static methods (regression)

### ISSUE THREAD

**Issue by JeanGoncalves54** [pyscripter/pyscripter#967]
'Search->Find References' from the context menu or Search menu dont'work in Pyscripter 3.6 and Pyscripter 3.5 but work in Pyscripter 3.4

I found that static method references were not found with Pyscripter3.6 or Pyscripter3.5 (It return 'References not found') but references are found with Pyscripter3.4

Here is a small code example:

"""
class MyClass:
(tab)    state = 'On'
(tab)    def doSomething():
(tab)(tab)        print('MyClass.Something do')

def doSomewhat():
(tab)    print('Somewhat do')

myVar = 1
print(myVar)
doSomewhat()
print(MyClass.state)
MyClass.doSomething()
print('End')
"""

References to doSomething are found with Pyscripter3.4  but not Pyscripter3.6 or Pyscripter3.5
References to state are found in all versions.
References to doSomewhat are found in all versions.
The definitions are always found.

I am using Windows8.1 64 bits and Windows7 64 bits

I made tests with:
- Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)] on win32  and Pyscripter 3.4.1.0x86
- Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32  and Pyscripter 3.4.1.0x64
- Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32 and Pyscripter 3.6.1.0x86
- Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32 and Pyscripter 3.6.1.0x64

**Comment by pyscripter** [comment]
Fixed in version control.
