### ISSUE TITLE
Colors of "True" and "False" words are different

### ISSUE THREAD

**Issue by ocarillo** [pyscripter/pyscripter#968]
I don't know if this was overlooked, but the color of the words "True" and "False" are different, and just the opposite in Interpreter window and the Editor window.

I have attached examples of what is happening. You can see how the word "True" is purple in Interpreter and the word "False" is orange.

In Editor, just the opposite: "True" is orange and "False" is purple.

![image](https://user-images.githubusercontent.com/50459080/64967395-b6844700-d8a0-11e9-9760-0d7223aa1856.png)

![image](https://user-images.githubusercontent.com/50459080/64967472-dae02380-d8a0-11e9-8826-a2c94f0f4b02.png)

**Comment by pyscripter** [comment]
Fixed in Version Control.  Thanks for reporting it.
