### ISSUE TITLE
Pyscripter on boot, will not respond 

### ISSUE THREAD

**Issue by JordanJ1998** [pyscripter/pyscripter#969]
Upon opening pyscripter the application will freeze and not respond. When looking into Windows Event Viewer the error that is being produce is Application Hang. Our Students are unable to use pyscripter due to this error. Is there any solution?

**Comment by pyscripter** [comment]
Could you please provide some more details about your setup?
- Which version of PyScripter are you using?
- 32bit or 64bit?
- Which version of python are you using?
- Which distribution did you use for installing python (for python.org,, Conda etc)

**Comment by JordanJ1998** [comment]
We are using the version version 3.3.2 pyscripter 
64bits
python 3.3.1
We downloaded from python.org and yes it is

**Comment by JordanJ1998** [comment]
Any chance you can provide me with a MSI package for pyscripter so we can distribute it on all machine within the school.

**Comment by pyscripter** [comment]
PyScripter 3.3.2 is old.  You can download a newer version 3.6.1 from https://sourceforge.net/projects/pyscripter/files/.

Python 3.3.1 is also very old.  Why are you not using a newer python (3.7 or 3.6)?

Could you please try the latest version of PyScripter and report whether it works?

**Comment by JordanJ1998** [comment]
Ok, i will try that but the only problem is we need the MSI package so we can distribute it all computers at once.

**Comment by pyscripter** [comment]
You can use https://www.exemsi.com/ to convert the installer (exe file) to an MSI package.

**Comment by JordanJ1998** [comment]
ok thank you
