### ISSUE TITLE
parameter with store and delete modifier

### ISSUE THREAD

**Issue by tfelden** [pyscripter/pyscripter#971]
I want to use a template like this:
Start of template text>>>
\#\# @var $[type=toBeChangedToRealType?Enter type of var] $$[varname-s=newVar?Enter variable name]
\# Description of $[varname]
$[varname-d] = None
<<<End of template text
The -s (parameter modifier) will store the value in varname.
The -d will remove the value in varname after usage.
In that case one can use the identical template to declare and document a python variable in pyScripter and with doxygen.

**Comment by pyscripter** [comment]
In the fortcoming version existing syntax has been extended in the following way:

When the Parameter contains the equal sign, the its value is defined for the current session, e.g. $[proc=Test] will define the Parameter "proc" with the value "Test".  Or  $[proc=?Enter proc] with prompt for a value and defined the Parameter "proc" with the provided value.  To remove a parameter use the equal sign without any value or question, e.g. $[proc=]  will remove the parameter proc if it exists.

For example try the following in an editor.

```
$[proc=aaa] $[proc] $[proc] $[proc=]
$[proc=bbb?Question] $[proc] $[proc] $[proc=]
```
Select and press Shft+Ctrl+R (Replace Parameters)

**Comment by tfelden** [comment]
I checked with version 3.6.2 the described feature as of 25.11.2019 post and it is working perfectly.
Many thanks!
