### ISSUE TITLE
Unable to start in windows 8.1 64

### ISSUE THREAD

**Issue by DefenderLab** [pyscripter/pyscripter#978]
> After installation pyscripter UI gets closed immigiatly

**Comment by marshall-ucsd** [comment]
Just installed 3.6.2.1 over 3.6.1 - same exact problem - launches, then closes immediately. No error messages or other diagnostics.
Windows 10 (1903) x64, Python 3.7.4 x64.
I'm going to try removing the configuration files, let it rebuild them, see if that helps.
