### ISSUE TITLE
how to open ipynb document ?

### ISSUE THREAD

**Issue by qq2898** [pyscripter/pyscripter#980]
File--->Open--->Type: JSON Files， after that can select and open ipynb document, but which shows a json code like this :
{
 "nbformat": 4,
 "nbformat_minor": 2,
 "metadata": {
  "language_info": {
   "name": "python",
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "version": "3.7.4"
  },
  "orig_nbformat": 2,
  "file_extension": ".py",
  "mimetype": "text/x-python",
  "name": "python",
  "npconvert_exporter": "python",
  "pygments_lexer": "ipython3",
  "version": 3
 },
......
dose there have any thing need to do ?

**Comment by pyscripter** [comment]
You then need to do Tools, Source Code Views, Web Preview.
