### ISSUE TITLE
Separate PyScripter.ini files for 32 anbd 64 bit versions

### ISSUE THREAD

**Issue by philnagel** [pyscripter/pyscripter#981]
When both a 32 and 64 bit version of PyScripter is installed on a system, they both store their settings in the same .ini file under APPDATA/PyScripter.  It would be nice to have them use 2 separate ini files as to be able to preserve different open files etc.
Or maybe there is some workaround to this to change the default path of one of the versions?

**Comment by pyscripter** [comment]
You can achieve this by using the "registry-free" versions of PyScripter.
**If pyscripter.ini is in the same directory as the pyscripter.exe** then PyScripter does not use any files outside the PyScripter directory.  The zip distributions do that by packaging pyscripter.ini with pyscripter.exe.
