### ISSUE TITLE
Editor keys disabled with both 32 and 64 bit versions installed

### ISSUE THREAD

**Issue by kimollivier** [pyscripter/pyscripter#984]
I  have Python 2.7 32 bit to integrate the IDE into ArcMap. (c:/python27/ArcGIS10.7)
(Esri has a hack that runs 2.7 64 bit when running scripts in the background, so I actually have a 64 bit installed in a parallel folder called ArcGISX6410.7) This has been running well for years.

Now I need to have Pyscripter 3.6 64 bit to integrate the IDE into ArcGISPro which uses Python 64 bit 3.6 as well while I transition to the New World. Hooray, Pyscripter has been upgraded to handle 64 bit, 3.6+ and virtual environments. There are extra function long on the wish list such as collapsing functions. Its all good and avoids having to change my IDE.

Pyscripter works well if only one version of Pyscripter is installed, but not if both 32 and 64 bit are installed, event though they are in "Program Files (x86)"and "Program Files" respectively.  Everything is nominally separate and cannot be confused, but I am suspicious that when I open up each one, the last script is remembered. Ha! so they are sharing some common status! Where? Can I separate the two systems better?

There seems to be something that is not switched so that I cannot edit properly using Pyscripter 2.7. I cannot Backspace. Del or enter a Newline. But I can use Ctrl-X, Ctrl-V and so on. The editor opens and most things work except for these critical keys.

If I open the script in Pyscripter 64 (outside ArcMap) then I can edit  using all the keyboard keys (and run it because my code is set up to be 32/64 and 2/3 compatible.) The 32 bit version is run by ArcMap internally, so I should be using that for my editor debugging. In fact if I don't ArcMap complains.

If I delete the 3.6 64 bit version then the 2.7 32 bit version works just fine.

**Comment by pyscripter** [comment]
You would need to have PyScripter 32-bits installed to use with python 2.7 32 bits and PyScripter 64-bits to use with Python 3.6 64-bits.

Different versions of PyScripter would share settings stored in PyScripter.ini and PyScripter.local.ini if you install PyScripter using the installer.  The location of these files is typically in the %APPDATA% user folder, where %APPDATA% is the directory pointed by the APPDATA environment variable.  (typically C:\Users\

To isolate each version of PyScripter you need to use the registry-free installation from SourceForge (which comes in a zip file) at least for one of the two installations.  In registry-free installations, settings are stored in the same directory as the PyScripter executable.  If you do that the two PyScripter installations would be entirely separate.

The presence of two or more python installations should not affect PyScripter unless these installations interfere with each other (e.g. there are environment variables such as PYTHONHOME or PYTHONPATH pointing to one version, or the Windows path contains paths pointing to one or more of these installations).  In a command prompt you can issue the command "SET" to see if this is the case.

**Comment by kimollivier** [comment]
Yes, that worked, thanks
