### ISSUE TITLE
Feature request: C++ integration

### ISSUE THREAD

**Issue by kapil-iitk** [pyscripter/pyscripter#986]
Because many of us are using pyscripter a lot for python and other ide for C++ for computing, is it possible to integrate simple interface to compile/code C++ program in pyscripter with (gcc)?

Thanks you.

**Comment by pyscripter** [comment]
You can produce your custom external tools to do that (Tools, External Tools).   But you will missing code completion, debugging etc. in C++ which would available in other IDEs and is outside the scope of PyScripter.
