### ISSUE TITLE
Problem when multiple lines of code are copied to the console

### ISSUE THREAD

**Issue by wangjiabc** [pyscripter/pyscripter#987]
I currently use version 3.6.0, and I hope to fix the problem when multiple lines of code are copied to the console: the following lines are invalid, and only the line to line can be copied to the console

**Comment by pyscripter** [comment]
Could you please provide an example.

**Comment by pyscripter** [comment]
If you want to execute a selected block of code you do not need to paste it to the interpreter.   You use  Edit, Source Code, Execute selection.

**Comment by wangjiabc** [comment]
I'm doing this mainly for convenience, you can look at the paste situation, I think it is a bug[http://lzxlzc.com/2020-02-23_101301.png](url),For comparison, I used pycharm's console to paste without this problem.[http://lzxlzc.com/2020-02-23_101811.png](url)，Because my habit is to copy the code from the Internet and paste it directly into the console, I hope you can find a way to modify the command line processing method, which will have better results

**Comment by wangjiabc** [comment]
There is also a bug. I found it from the beginning using pyscript. The arrow on the console has a space from the first character. This has not happened in other IDEs.[http://lzxlzc.com/2020-02-23_102526.png](url)，This space will make the operation inconvenient after there are more lines of code. Although it is not a big problem, I still hope to fix it sometime.

**Comment by wangjiabc** [comment]
I usually use java in my work. Python is used for calculation by amateur. Generally speaking, I am quite satisfied with pyscripter. I hope that the improvements can be made to the console problems mentioned above, 2 text area. When writing code, the method of introducing a third-party library cannot be completed automatically. 3 The program sometimes crashes, and the file is lost after restarting without saving.

**Comment by pyscripter** [comment]
The space after >>> is standard in python.  Just look at a python console.

**Comment by wangjiabc** [comment]
Thank you for looking at my comments,I highly respect your answer. After all, you have developed this software. I know the difficulty of development. However, I tested in the cmd. Python >>> has no spaces. This problem is mainly by pressing the up key. Will appear, although it does not affect the use, but a bit inconvenient, the user experience will not be good for long-term use of this software
