### ISSUE TITLE
Ukrainian language doesn't appear in selection

### ISSUE THREAD

**Issue by VBoden** [pyscripter/pyscripter#988]
It is not possible to change interface language to Ukrainian as it doesn't appear in languages list.
Version 3.6.3

**Comment by pyscripter** [comment]
The compiled default.mo file was missing.   It is now fixed in version control.  In the meantime you can add the contents of this zip file to the Ukrainian language directory (uk) and you should see the language.
[default.zip](https://github.com/pyscripter/pyscripter/files/4366256/default.zip)

**Comment by VBoden** [comment]
Thanks a lot!
