### ISSUE TITLE
Editor Options: Show Line Numbers Not Working  (version 3.6.3.0 x64)

### ISSUE THREAD

**Issue by ShadyMBA** [pyscripter/pyscripter#989]
Editor Options: Show Line Numbers Not Working  (version 3.6.3.0 x64)
The option to show line numbers is not working.

![image](https://user-images.githubusercontent.com/58062696/78468500-aa4dc300-76e6-11ea-869e-d0ec9e786d91.png)

![image](https://user-images.githubusercontent.com/58062696/78468507-b5085800-76e6-11ea-9fe1-e7114b43392a.png)

**Comment by pyscripter** [comment]
This mimics the way Delphi show line numbers (every 10 and the current line).

If you want to show all line numbers go to Tools, Options IDE Options, Editor and uncheck "Compact Line Numbers"

**Comment by ShadyMBA** [comment]
Perfect! That worked, thanks!! I love your product.
Is there a way to turn off those blue dots?

![image](https://user-images.githubusercontent.com/58062696/78507879-f2a1cb00-7750-11ea-8eeb-766e912a99d0.png)

**Comment by pyscripter** [comment]
Go to Tools, Options IDE Options, Editor and uncheck "Show executable line marks"

**Comment by ShadyMBA** [comment]
Awesome...the editor looks exactly as I want it to be.
One final question that I couldn't find in the help file: When creating a new file, there's a Jupyter Notebook option which sounds super exciting...can PyScripter actually run Jupyter Notebooks inside the editor? It seems to me that it only edits the Json only? can you clarify this please because I'd love to use it as my Jupyter Notebook IDE!

![image](https://user-images.githubusercontent.com/58062696/78510478-5f25c580-7763-11ea-9e73-658cb23eb764.png)

Also as a token of appreciation I've put a recommendation on Stack-overflow! :-)

![image](https://user-images.githubusercontent.com/58062696/78510554-ea9f5680-7763-11ea-8cdf-b755fce82e29.png)

Thanks so much for your patience and support!

**Comment by pyscripter** [comment]
You need to do Tools, Souce Code Tools Web Preview. Over here when I create a new Jupiter file PyScripter starts the notebook server automatically and loads the file into Web preview.
You need to have all the Jupiter, notebook related libraries installed.

**Comment by ShadyMBA** [comment]
Great that worked, thanks! :-)
