### ISSUE TITLE
Suggestion: New Icons design

### ISSUE THREAD

**Issue by ShadyMBA** [pyscripter/pyscripter#990]
Great product - love the simplicity and speed but the icons and gui in general looks really ugly and outdated as if it was made in year 2005. A little bit of polishing would be awesome!

**Comment by pyscripter** [comment]
Happy to accept contributions in this area.

**Comment by ShadyMBA** [comment]
My artistic skills are not great but I can give it a try :-). Where are the icons stored to see if I can edit them?

**Comment by pyscripter** [comment]
Under Art :)

**Comment by ShadyMBA** [comment]
hahahah how ironic! :-)
By where's that art folder? I can't find it?

![image](https://user-images.githubusercontent.com/58062696/78519374-2270c300-7791-11ea-8a3a-837b2a8b1749.png)

**Comment by pyscripter** [comment]
It is on the GitHub repository.  Either clone or download the zip file.

**Comment by adrianrb** [comment]
Adding to this issue, in Dark Mode (Win 10 Pro), some icons wont show:

![image](https://user-images.githubusercontent.com/12686959/102393330-f9a6fb80-3fb6-11eb-9ac4-79b0a3ff9a20.png)

**Comment by pyscripter** [comment]
The don't show only when they are disabled.

**Comment by pyscripter** [comment]
New material icons in the coming version.
Preview at https://github.com/pyscripter/pyscripter/tree/master/Art/Icons/default/Scalable-Material
