### ISSUE TITLE
More fonts for Code-Editor (ClearType problem)

### ISSUE THREAD

**Issue by DrCKYHC** [pyscripter/pyscripter#992]
PyScripter allows select font for Editor-Window (i.e. code), but the list of fonts is quite limited (I have combined all available fonts on screenshot, usually you can't see all of them at once):

![image](https://user-images.githubusercontent.com/63731934/79356196-ee3e9480-7f3e-11ea-848f-c43664cc8dd2.png)

The ClearType option is disabled at my PC (Win 7 64) and standard-windows are shown with clear readable font. But the code in PyScripter being shown not that clear (i.e. it looks like if ClearType would be active) and there is also no possibility to use a standard windows font at least for Editor-Window. The fonts are available for PyScripter (see the PyScripter menu, File-Explorer content and search-field on screenshot below):
![image](https://user-images.githubusercontent.com/63731934/79356769-9bb1a800-7f3f-11ea-8956-9232a5b35cdb.png)

It would be good to have option use windows standard font (similar as by python window) or to be able select more fonts for the PyScripter Editor-window.

I also saw an option "fpNonAntialiased" by the CodeCompletion->Auto completion font->Quality , but there is no such option by Editor-Font.

**Comment by pyscripter** [comment]
The list shows only monospace fonts because pyscripter and most code editors cannot work with variable-width fonts.   The Consolas font works well.  For more choices have a look at https://www.elegantthemes.com/blog/wordpress/best-programming-fonts  (or similar if you google "programming fonts")  and download/install the fonts of your choice.

**Comment by DrCKYHC** [comment]
The "Source Code Pro" font from link named above brought significant improvement.
Thanks!
