### ISSUE TITLE
umm

### ISSUE THREAD

**Issue by twistcharlie** [pyscripter/pyscripter#994]
the abort button don't work sometimes(maybe because of the code is not responding but still) also if i do
```
def loop():
      print("loop")
      loop()
loop()
```

pyscripter would do it but not as a loop(just like when u open a .py file(as command propt) but in python idle if press run or f5 it won't crash so maybe do a similar system to python idle for run(debug thing u know)

**Comment by pyscripter** [comment]
This is not a good example, because it crashes with a max recursion limit reached.

But say

```python
def loop():
    while True:
        print("loop")

def main():
    loop()

if __name__ == '__main__':
    main()
```

You can still break out with Run, Python Engine, Reinitialize.  (assumes you use the default Remote Python engine).
