### ISSUE TITLE
sorry sorry but i got a video this time to say it 

### ISSUE THREAD

**Issue by twistcharlie** [pyscripter/pyscripter#995]
https://www.dropbox.com/s/43unetd4rs8aeaz/2020-04-19%2015-01-00.mp4?dl=0

**Comment by pyscripter** [comment]
Recursion limit:

- Default 1000.
- Same in PyScripter and Python interpreter.
- See https://www.pythoncentral.io/resetting-the-recursion-limit/
-  PyScripter crahes after exactly the same number of loops as Python.

Line numbers:
From the toolbar
![image](https://user-images.githubusercontent.com/1311616/79695547-20722e00-8280-11ea-87fc-76f3f5b6b268.png)

Editor Options
![image](https://user-images.githubusercontent.com/1311616/79695579-56171700-8280-11ea-83af-ce02a5c8e857.png)

Related option
Tools Options IDE Options, Compact line numbers (see help file)
![image](https://user-images.githubusercontent.com/1311616/79695606-852d8880-8280-11ea-8296-37721ca25055.png)

**Comment by twistcharlie** [comment]
i learnt idle had a limit via testing today lol and ooh so i can get line numbers :)

**Comment by twistcharlie** [comment]
im dumb
