### ISSUE TITLE
Interpreter freeze after reading a large file

### ISSUE THREAD

**Issue by tapdo** [pyscripter/pyscripter#998]
I'm attaching the file at that time. 
![pys_intpr_freeze_1](https://user-images.githubusercontent.com/5471106/83268199-37515c00-a200-11ea-94f6-70327ec985ce.gif)

Here's the code I used.
```
with open(r"C:\Users\kawar\Desktop\abc.mp4", "rb") as f:
    data = f.read()
print
```
A couple of minutes later, I got the next error.
<img width="480" alt="after_freeze" src="https://user-images.githubusercontent.com/5471106/80909987-8a520380-8d67-11ea-99d6-43f1c3a3b379.png">

"abc.mp4" is a binary file of about 50MB.
It's not a problem if it's a few MB, but it seems to occur even if it's about 20 MB.
It seems to be triggered by some kind of complementary work.

**Comment by pyscripter** [comment]
Have you tried this with the standard python interpreter?
How does that respond.

**Comment by tapdo** [comment]
I tried it with IDLE, but I didn't have any problems.
![image](https://user-images.githubusercontent.com/5471106/80916141-e29dfb00-8d91-11ea-958c-a5a63b0971bc.png)

**Comment by pyscripter** [comment]
Ok I see.  I will look into this.

**Comment by pyscripter** [comment]
If you want to try replace lib\rpyc.zip with the one from master.  Please report if you have any issues.
